/**
 * 更新日志条目配置
 * 每次更新后在此数组头部添加新版本记录
 */
export const CHANGELOG = [
    {
        version: '2.3.58',
        date: '2026-05-18',
        isLatest: true,
        highlights: [
            '粮食、布料价格上限大幅放开，饥荒时价格能真正反映稀缺',
            '补贴政策全面打通迁移决策，加税减税不再"无人响应"',
            '关键生产者保留锁上线，自耕农不再攒够钱就升级跑路',
            '生存危机迁移机制重做，缺粮时工匠也会回去种田',
        ],
        changes: [
            { type: 'fix', text: '修复必需品价格信号失灵：粮食 maxPrice 从 150 提升到 500、布料从 325 提升到 750（饥荒时"米斗万钱"级），并移除危机段写死的 5× 上限，改为按 maxPrice/basePrice 推导真实上限，库存归零时价格能真正逼近上限；同时把库存极低（<0.1）时的价格平滑速度从 ~10-20 tick 提升到 0.3-0.7（约 2-3 tick 到位），避免目标价飙升而成交价仍卡在低位的"价格信号失灵"。' },
            { type: 'fix', text: '修复必需品在低供需权重下的危机价格压制：粮食 supplyDemandWeight 从 0.4 调高到 0.6，且当 essential 资源库存比 < 0.3 时按危机深度逐步把权重抬升至 1.0，避免补贴/紧缺时价格被"必需品权重低"反向削平，让玩家能看到真正的稀缺信号。' },
            { type: 'balance', text: '调整资源分类：spice（香料）、coffee（咖啡）从 essential 改为纯 manufactured 奢侈品定位，避免危机时这些贸易品被错误纳入"生存必需品"逻辑触发不合理的价格爆涨与迁移压力。' },
            { type: 'fix', text: '修复"宁愿饿死也不去种田"问题：生存危机（食物/布料严重短缺）时，工匠、工人、书吏等非紧缺生产角色即使收入正常也允许作为迁出源，且按 pop 优先疏散富余劳动力；同时把降级到紧缺生产角色的阻力 clamp 至 1.0（与升 tier 同等严格度），让高 tier 富余人口能真正下沉到农田。' },
            { type: 'fix', text: '修复"自耕农攒够钱就升 tier 跑路再次缺粮"循环：新增关键生产者保留锁（peasant 等），三层单向阻止迁出——危机锁（出现紧缺时绝不迁出）、岗位空缺锁（自家在岗率不足 95% 不迁出）、补贴依赖锁（补贴占收入比 ≥ 25% 且仍有空缺则视为政策维持中）。三锁仅阻止迁出，不影响迁入，避免补贴反成为升 tier 燃料。' },
            { type: 'fix', text: '修复补贴政策对迁移决策"无声"的核心 BUG：把人头税补贴和业务税补贴的人均到账金额显式上报为 subsidyPerCapita 字段（口径与 taxes.js 实际银币流完全一致：人头税补贴 = |headRate| × effectiveTaxModifier；业务税补贴 = Σ |buildingRate| × count × effectiveEfficiency / 在岗分母）。补贴拉力（×2.8 迁移速率）、同 tier 阻力削减、单向冷却才能真正生效。' },
            { type: 'improve', text: '重写补贴拉力机制：当目标角色补贴显著（potentialIncome ≥ 平均值 × 1.5）时启用迁移加速（介于普通与紧急之间，约 2.8× 速率），并仅对源角色设迁移冷却，让目标岗位下一 tick 仍可继续迁入，避免一次冷却屏蔽连续补贴拉力；同 tier 阻力按补贴强度（占源收入比 ≥ 0.3）线性削减至 1.0，下放工业到农田/手工业到工业等"政策导向"流动更顺畅。' },
            { type: 'fix', text: '修复业主收入信号被全阶层稀释问题：netIncomePerCapita 分母从总 pop 改为本 tick 实际在岗 pop（三级回退：在岗→岗位数容量→总 pop 兜底）。例如农田 0/42 时业务税补贴不再被全国失业 peasant 稀释成 4 银/人，而是按真实岗位容量计算，让 peasant 收入信号在补贴政策下真正高于工匠、迁移决策能正确响应。' },
            { type: 'improve', text: '把"明显落后于最佳机会"的源候选门槛从 0.6 放宽到 0.85（保留 15% 容差避免微小差距引发不必要迁移）；空岗位冷启动工资预估在建筑享受业务税补贴时，按"利润分润 40%"路径并入估算工资，让从未有人涉足的紧缺岗位也能因补贴而显示有吸引力的工资信号。' },
            { type: 'improve', text: '新增 7 个补贴/危机迁移可调常量（SUBSIDY_PULL_MULTIPLIER、SUBSIDY_RESISTANCE_REDUCTION_THRESHOLD、SUBSIDY_HIGH_ATTRACTIVENESS_RATIO、CRISIS_SUBSIDY_SIGNAL_MULTIPLIER、CRITICAL_SHORTAGE_ATTRACTIVENESS_MULTIPLIER、CRISIS_DOWNGRADE_RESISTANCE_CAP、SUBSIDY_DEPENDENCY_LOCK_RATIO 等），统一收敛到 utils/constants.js 并附带文件级 sanity check（开发模式 console.warn，不抛错），便于后续平衡调优。' },
        ],
    },
    {
        version: '2.3.57',
        date: '2026-05-13',
        isLatest: false,
        highlights: [
            '理念涌现升级为五选一，抽卡选择空间更大',
            '游戏百科新增理念体系专栏，可直接查看每张理念的分级与触发细节',
            '理念卡牌与百科共享同一套文案格式化逻辑，展示口径更一致',
        ],
        changes: [
            { type: 'improve', text: '理念涌现候选数量从 3 提升到 5，并同步优化弹窗网格布局与出场动效节奏，减少“这一轮全都不想选”的挫败感，让玩家更容易拿到符合当前阵容的理念。' },
            { type: 'new', text: 'Wiki 新增“理念体系”分类与完整理念条目：支持按时代与稀有度检索理念，展示每级增量效果、继承效果、触发事件与出现倾向，降低理念系统的学习门槛。' },
            { type: 'improve', text: '新增 ideologyFormatter 共享工具并让理念卡牌与 Wiki 详情页复用同一套描述函数，统一了 converters / ruleMods / triggerEffects 的中文说明，避免不同界面出现同一效果不同文案的理解偏差。' },
        ],
    },
    {
        version: '2.3.56',
        date: '2026-04-30',
        isLatest: false,
        highlights: [
            '业主工资责任按实际所有权分摊，本国业主不再为外资/官员私产/国有建筑买单',
            '官员私产、国有、外资建筑的雇员工资各自由对应账户支付',
        ],
        changes: [
            { type: 'fix', text: '修复严重的工资责任错配 BUG：本国阶层业主曾被错误地承担同类型全部建筑（含外资/官员私产/国有）的非业主雇员工资。例如 10 栋同类建筑只有 1 栋为本国业主持有，原逻辑下这 1 个本国业主要为另外 9 栋建筑的全部雇员发工资，导致业主财富瞬时透支与外资/官员部分双重计费。' },
            { type: 'improve', text: '工资支付逻辑按建筑业主类型分摊：本国阶层业主部分仍按生计/业主双底线由 wealth[业主阶层] 支付；官员私产部分按 officialOwners 详情从对应官员私人 wealth 扣除；国有/代经营部分由国库 silver 支付（不足时降额）；外资部分不再扣本国账户（外资侧 processForeignInvestments 已在 wageCost 中扣过外资利润，此处视为外资从海外汇入）。' },
            { type: 'improve', text: '在 ownerJobsAdjust 阶段缓存 buildingOwnershipMap，统一记录每种建筑的 stratum/official/foreign/state 数量及业主明细（officialOwners、stateManagedBy），供工资支付与后续财务统计共享，避免分散计算导致的口径漂移。' },
        ],
    },
    {
        version: '2.3.55',
        date: '2026-04-23',
        isLatest: false,
        highlights: [
            '官员政治主张满足状态统一计算，列表与详情展示口径一致',
            '官员面板复用判定结果，减少重复计算带来的界面抖动',
        ],
        changes: [
            { type: 'fix', text: '修复官员面板中“政治主张是否满足”在列表卡片与详情面板之间可能出现口径不一致的问题：改为在 OfficialsPanel 父层统一计算并按官员 ID 透传，避免同一官员在不同位置显示不同状态。' },
            { type: 'improve', text: '优化官员主张满足判定链路：列表与详情复用同一份 memo 结果，仅在必要时兜底重算，减少重复调用带来的额外渲染开销，提升官员列表浏览稳定性。' },
        ],
    },
    {
        version: '2.3.54',
        date: '2026-04-22',
        isLatest: false,
        highlights: [
            '人头税“税/补”切换默认值修正，重置后不再误跳 100% 税率',
            '取消“富裕性挥霍”机制，财富只由真实收支流动变化',
            'AI 多战线军团分配修复，避免玩家战线与 AI 战线双重计战力',
            '存档失败提示文案修复，错误反馈不再乱码',
        ],
        changes: [
            { type: 'fix', text: '修复政治页人头税“税/补”切换时默认值错误：征税模式改为回落到 5% 默认税率（headPercentToMultiplier(5)），避免从补贴切回征税后被误设为 100% 税率。' },
            { type: 'remove', text: '移除“富裕性挥霍（Wealth Decay）”机制及其收支展示：不再按生活水平对财富做额外蒸发扣减，相关账本分类与面板条目同步清理，阶层财富只由消费、税收、投资与贸易等真实资金流动变化。' },
            { type: 'fix', text: '修复自动/手动存档失败日志提示乱码：失败时会正确记录“自动存档失败/存档失败 + 错误信息”，便于玩家与排障日志准确识别问题。' },
            { type: 'fix', text: '修复 AI 战争军团分配在玩家战线与 AI-AI 抽象战线间重复计入的问题：已部署军团优先归属玩家战线，空闲军团再按威胁权重分配到 AI 战争，避免同一军团被双重计战力导致战局失真。' },
        ],
    },
    {
        version: '2.3.53',
        date: '2026-04-16',
        isLatest: false,
        highlights: [
            '自动存档调度重构为“空闲时执行”，高速档卡顿与误超时风险明显下降',
            '存档系统升级为分片 + Worker 序列化，主线程存档抖动显著减少',
            '存档全链路新增性能埋点与回退监控，后续定位卡顿和失败更精准',
            '新增存档 Worker 与可选 gzip 压缩通道，为后续大存档优化打好基础',
        ],
        changes: [
            { type: 'improve', text: '重构自动存档调度策略：useAutoSave 从固定 setInterval 改为 setTimeout + requestIdleCallback 链式触发，并补充 inflight 防重入与页面可见性补偿，避免存档与渲染关键帧抢主线程，降低高倍速下的卡顿和 worker timeout 风险。' },
            { type: 'new', text: '新增 save.worker 分片序列化链路：将 state/nations/history/market/social 五个分片的 JSON.stringify 从主线程迁移到专用 Worker，并支持队列合并覆盖与 superseded 快速跳过，减少连续自动存档时的主线程阻塞。' },
            { type: 'improve', text: '存档格式升级到 v2 分片存档：IndexedDB 优先写入 shard 数据，localStorage 仅保存轻量 stub；加载侧新增分片合并与兼容读取（含旧版 v1 / 外部存储路径），删除存档时会同步清理所有 shard，降低大存档场景的写入压力与碎片残留。' },
            { type: 'new', text: '新增存档性能观测埋点：补充 Save:Duration / Save:Bytes / Save:Path / Save:WorkerFallback / Save:Skip 事件，支持按手动/自动来源、分片字节和回退路径统计，为线上性能分析与故障归因提供直接数据。' },
            { type: 'improve', text: '优化 saveGame 序列化与回退链路：统一“一次 stringify 多处复用”，减少重复 JSON 构建与 Blob 开销，并将配额不足时的 compact/minimal/cleanup 重试路径统一纳入可观测流程，提升极端存储压力下的成功率和一致性。' },
            { type: 'new', text: '新增 saveWorkerClient 与 save.worker 模块，并调整 Vite worker 输出命名为 assets/[name].js：在保留 simulation.worker 固定路径兼容的同时支持多 worker 并存，且预留可选 gzip 压缩开关用于后续灰度。' },
            { type: 'improve', text: '清理主循环中的重复自动存档检测：useGameLoop 不再每 tick 做 autoSave 判定，避免高速档下无效检查和潜在重入，自动存档职责统一收敛到 useAutoSave 专用调度器。' },
        ],
    },
    {
        version: '2.3.52',
        date: '2026-04-16',
        isLatest: false,
        highlights: [
            '税收批量重置默认值修正，重置后不再误回到 100% 人头税',
            '外资入境分批周期完成态修复，10 天节奏恢复稳定',
            '建筑回写改为“按改动返回”，减少无效状态覆盖与额外渲染',
        ],
        changes: [
            { type: 'fix', text: '修复政治页税收批量重置的人头税默认值错误：重置逻辑从硬编码倍率 1 调整为 headPercentToMultiplier(5)，避免玩家点击“重置”后人头税被错误恢复到 100% 而不是默认 5%。' },
            { type: 'fix', text: '修复外资入境投资分批循环在一个 10 天周期内重复触发的问题：inboundInvestmentBatchRef 新增 completed 标记，周期处理完后显式置为完成，直到下个周期开启前不再重复进入，避免同周期多次扫描。' },
            { type: 'fix', text: '修复入境投资缓存签名未纳入国家投资冷却字段导致的失效判断偏差：computeInboundSignature 新增 lastForeignInvestmentDay 聚合参与签名，防止缓存命中后绕过冷却校验。' },
            { type: 'improve', text: '优化 simulation 建筑状态回写策略：仅在自由市场扩建、官员投资、部长扩建等路径真实修改建筑数量时返回 buildings，否则返回 null，减少无意义 setState 与潜在覆盖。' },
        ],
    },
    {
        version: '2.3.51',
        date: '2026-04-16',
        isLatest: false,
        highlights: [
            '商业建筑产出重新平衡：贸易站、市场、贸易港的粮食与银币比例更合理',
            '升级链数值同步校准，与基础建筑倍率保持一致',
        ],
        changes: [
            { type: 'balance', text: '贸易站基础产出从 food:4 / silver:1.6 调整为 food:1.5 / silver:2.8：降低早期贸易站的粮食溢出，提高银币收益占比，使商人阶层的经济定位更偏向货币流通而非粮食生产。' },
            { type: 'balance', text: '市场基础产出从 food:4 调整为 food:2 / silver:1.5：市场不再是纯粮食来源，新增银币产出体现商业税收功能，并同步校准升级链"大市场"和"交易所"的产出倍率（1.3x / 2.25x）。' },
            { type: 'balance', text: '贸易港基础产出从 food:12 / silver:2 调整为 food:5 / silver:5：大幅削减贸易港的粮食产出优势，提升银币比重，避免后期贸易港堆叠导致粮食经济过度膨胀。升级链"繁荣港口"和"贸易枢纽"产出同步重算。' },
        ],
    },
    {
        version: '2.3.50',
        date: '2026-04-16',
        isLatest: false,
        highlights: [
            '修复导致白屏闪退的 React #185 无限循环：战线部署、教程系统、移动端视口高度三条路径已堵住',
            'Worker 模拟线程不再因第三方 SDK 访问 window 而崩溃，性能回退问题消除',
            '错误上报系统大幅降噪：健康事件不再被标为崩溃，重复写入已修正',
        ],
        changes: [
            { type: 'fix', text: '修复战线部署 effect 链导致 React #185 无限循环闪退：handleAssignCorpsToFront、focusMilitaryWarfront 等 6 个 useCallback 的依赖从不稳定的 [gameState] 整对象改为通过 useRef 读取，使下游 useEffect 引用稳定，消除战争状态下每帧重跑 → setState → 再渲染的死循环。' },
            { type: 'fix', text: '修复教程系统 useTutorialSystem 中 onComplete 内联函数导致 nextStep 每帧重建的问题：改用 onCompleteRef 持有回调，skipTutorial 和 nextStep 的依赖不再包含 onComplete，教程激活时校验 effect 不再高频无效重跑。' },
            { type: 'fix', text: '修复 useViewportHeight 中 [vh] 自依赖导致的移动端循环渲染：effect 改用 vhRef 比较当前值，依赖改为空数组，WebView 输入法弹出/收起不再触发 setState → effect → setState 的无限循环。' },
            { type: 'fix', text: '修复 Worker 模拟线程 "window is not defined" 崩溃：在 Vite Worker 构建中通过 plugin 将 gaTracker、gameanalytics 等分析模块替换为空 stub，彻底避免第三方 SDK 的模块级代码在 Worker 中因访问 window 而报错。' },
            { type: 'fix', text: '修复分期赔款 installmentPayment.paidAmount 的 null ref 崩溃风险：所有读取 paidAmount、amount、totalAmount 的路径增加 || 0 防御性兜底，兼容旧存档中字段缺失的情况。' },
            { type: 'improve', text: '错误上报系统降噪：Worker 健康事件（worker_ready）不再覆盖崩溃日志槽位，启动时按 type 区分真实崩溃与诊断事件的上报级别，去除 bufferErrorEvent 重复调用，每条错误不再产生两条记录。' },
        ],
    },
    {
        version: '2.3.49',
        date: '2026-04-15',
        isLatest: false,
        highlights: [
            '法令冷却写回兼容性修复，旧存档与新状态字段命名保持一致',
            'Worker 环境补齐更多 DOM 垫片，第三方模块在模拟线程初始化更稳定',
            '开发期热更新后配置与数据恢复链路更稳，降低隐性状态错位风险',
        ],
        changes: [
            { type: 'fix', text: '修复法令冷却字段命名不一致导致的状态回写风险：统一使用 setDecreeCooldowns 作为标准写入入口，并保留 setDecreCooldowns 兼容别名，避免旧调用路径在重构后出现冷却数据丢失或写错字段。' },
            { type: 'fix', text: '修复 Worker 场景下部分依赖访问 document/window API 时的初始化异常：为 document.createElement、querySelector、head/body 挂载等接口补齐空实现与返回兜底，减少第三方模块在 Worker 启动时因 DOM 缺失触发报错。' },
            { type: 'improve', text: '优化存档加载阶段的法令冷却恢复路径：loadGame 改为直接走标准拼写 setter，降低后续维护中因拼写差异导致的行为偏差，使状态恢复逻辑更可预期。' },
        ],
    },
    {
        version: '2.3.48',
        date: '2026-04-15',
        isLatest: false,
        highlights: [
            '热重载稳定性大幅提升：开发期重复定时器、重复监听与 Worker 失效导致的异常明显减少',
            '大规模状态管理重构：合并多组状态钩子，降低 Hook 数量，提升长时间开发与调试稳定性',
            '拆除建筑后会同步回收对应外资持有量，避免出现“建筑已拆但外资残留”',
            'AI 对 AI 多战线分兵逻辑修复，未分配兵团的战线不再错误回退到整国战力',
        ],
        changes: [
            { type: 'fix', text: '修复开发期 HMR 下定时器与全局监听重复注册的问题：分析上报、崩溃上报、主循环与 Worker 生命周期新增幂等保护与销毁清理，避免多次热更新后出现重复心跳、重复上报、Worker 残留或锁死。' },
            { type: 'improve', text: 'useGameState 大规模状态结构改造：将理念、外交、军事、政策、经济等高关联状态分组迁移到 useGroupedState（useReducer）管理，在保持外部调用方式不变的前提下显著减少 Hook 数量，提升 Fast Refresh 稳定性与维护可读性。' },
            { type: 'fix', text: '修复建筑拆除与外资系统的数量一致性问题：当玩家拆除建筑时会同步裁剪对应 foreignInvestments 的 operating 持有量，并按剩余数量等比收缩投资与经营数据，避免“建筑归零但外资仍在运营”的状态错位。' },
            { type: 'fix', text: '修复 AI 对 AI 战争中分兵与战线战力计算异常：军团分配改为覆盖完整国家集合，且在已有军团体系数据时，未分配到战线的国家不再回退到整国宏观战力，减少多战线下战力重复与僵持异常。' },
            { type: 'improve', text: '新增 useAutoSave 独立钩子并改进入口与性能补丁幂等保护：自动存档与主循环解耦，主入口仅初始化一次控制台与性能补丁，降低热更新期间副作用叠加风险。' },
            { type: 'fix', text: '修复旧业主数据转 ownershipList 的计数溢出问题：官员、代管、外资计数统一受剩余建筑数量约束，并兼容外资 count 字段，确保所有业主类型总和不超过建筑总量。' },
        ],
    },
    {
        version: '2.3.47',
        date: '2026-04-13',
        isLatest: false,
        highlights: [
            '兼容旧版 Android WebView：补充 flat/flatMap polyfill，低版本设备不再白屏',
        ],
        changes: [
            { type: 'fix', text: '为旧版浏览器（Chrome < 69 / Android WebView < 69）添加 Array.prototype.flat 与 flatMap 的 polyfill：部分低版本安卓设备因缺少该方法导致应用启动即白屏崩溃，现已在应用入口提前注入兼容补丁。' },
        ],
    },
    {
        version: '2.3.46',
        date: '2026-04-10',
        isLatest: false,
        highlights: [
            '官员系统再修一轮：同帧雇佣与解雇都能稳定落地，不再互相覆盖',
            'simulation 回写会同时处理“新增官员”和“已移除官员”，状态更一致',
            '官员列表竞态分支细化，减少 tick 期间错乱与回退',
        ],
        changes: [
            { type: 'fix', text: '修复官员列表在 simulation 回写时对“已解雇官员”缺少过滤的问题：当玩家在 tick 内解雇官员后，旧快照返回的数据不会再把该官员错误写回。' },
            { type: 'improve', text: '官员合并逻辑升级为双向校验：除保留同帧新雇佣官员外，还会识别并移除 simulation 结果中的失效官员，确保回写后的官员列表与当前状态一致。' },
            { type: 'fix', text: '优化官员回写短路条件与映射流程，降低同帧高频操作下的竞态覆盖概率，提升官员数据连续性与稳定性。' },
        ],
    },
    {
        version: '2.3.45',
        date: '2026-04-10',
        isLatest: false,
        highlights: [
            '官员雇佣与解雇改为双向合并校正，tick 竞态下不再出现“幽灵官员”回写',
            'simulation 写回官员列表会同时保留新雇佣并剔除已解雇对象',
            '官员状态更新链路更稳，避免同帧操作被旧快照覆盖',
        ],
        changes: [
            { type: 'fix', text: '修复官员系统在 tick 写回期间的竞态覆盖问题：当玩家在同帧进行雇佣或解雇时，simulation 仍可能携带旧快照官员，导致已解雇官员“回魂”或新雇佣官员丢失。' },
            { type: 'improve', text: '官员写回改为双向 ID 合并策略：在保留 simulation 财务更新结果的同时，自动补回当前状态中新雇佣官员，并从 simulation 返回中剔除已解雇官员，确保列表与玩家操作一致。' },
            { type: 'fix', text: '优化官员写回短路条件：只有在“无新增且无移除”时才直接采用 simulation 结果，减少同帧状态冲突下的误覆盖，提升官员状态连续性。' },
        ],
    },
    {
        version: '2.3.44',
        date: '2026-04-10',
        isLatest: false,
        highlights: [
            'AI 对 AI 战争推进改为稳定频率结算，长期僵局与“永不结束”明显减少',
            '官员持久状态与代经营建筑归属修复，忠诚与托管增长不再被稀释',
            '军人岗位在岗统计补齐，人口详情就业总览口径更准确',
            '多处建筑业主与理念联动口径校正，显示与机制更一致',
        ],
        changes: [
            { type: 'fix', text: '修复 AI 对 AI 战争在预算保护分支中被长期跳过的问题：战争推进改为按固定 tick 频率独立结算，并补强长期战争强制收敛逻辑，缓解“战线不动、分数常年归零、战争极难结束”的异常。' },
            { type: 'balance', text: 'AI 对 AI 战争新增僵持与疲劳调节：提升占领判定灵敏度、加入最低疲劳增量、长战加速结束与阈值动态下调，并按战争目标细化结束门槛，使朝贡战与附庸战呈现更合理的时长差异。' },
            { type: 'fix', text: '修复附庸控制模式下 AI 战争可能“卡审批不结算”的问题：超过时长阈值后会走自动收尾路径，避免 puppet/guided 场景下长期挂起。' },
            { type: 'fix', text: '修复官员状态在 Worker 传输中被剥离导致的持久字段回退：officials 不再被缓存空值覆盖，忠诚度、财富与日消耗等状态可按 tick 连续演化。' },
            { type: 'improve', text: '代经营制补充新扩建建筑归属分配：阶层业主扩张的建筑会自动并入代经营官员托管汇总，减少“建出来但托管统计不增长”的认知落差。' },
            { type: 'fix', text: '补齐军人岗位就业统计来源：军队系统岗位会写入岗位总览聚合，人口详情中的军人在岗率与军队规模口径一致。' },
            { type: 'balance', text: '校正部分建筑业主与岗位配置（含铜矿、石作坊、硬木营、竖井矿）并同步升级表；相关理念联动建筑从祠堂口径改为教堂口径，显示文本与实际加成对象统一。' },
            { type: 'fix', text: '修复官员雇佣容量在特定场景下被误判为 0 的问题：当 jobsAvailable 缺失时会回退建筑岗位估算，避免 UI 显示可雇佣但实际无法任命。' },
        ],
    },
    {
        version: '2.3.43',
        date: '2026-04-09',
        isLatest: false,
        highlights: [
            '附庸化后会自动结束与我方盟友战事，阵营关系不再“同阵营互殴”',
            'AI 战争新增战场随机波动与长期消耗分，僵持局更容易自然收敛',
            '已灭亡国家会被发现系统与可见性统一过滤，外交列表更干净',
            '税率输入支持直接填负数自动切补贴模式，调税更顺手',
        ],
        changes: [
            { type: 'fix', text: '修复国家在成为玩家附庸后，仍与玩家盟友或其他附庸保持战争状态的问题：在附庸化与和约落地时会同步清理相关 foreignWars 并建立停战期，避免同阵营内出现不合理持续交战。' },
            { type: 'improve', text: 'AI 对 AI 战争推进加入战场噪声与长期消耗分：均势战局会出现可控拉锯，长期僵持也会缓慢累计分数，不再长期卡在中线且难以结算。' },
            { type: 'balance', text: '按战争目标细化 AI 战争结束门槛：朝贡/防御类更容易达成停战，附庸/吞并类需要更高决定性优势，战争节奏与目标强度更匹配。' },
            { type: 'fix', text: '国家发现与可见性系统统一过滤已吞并、已战败和零人口国家，并在模拟写回中补齐 discovered 状态，避免“已灭亡国家仍被纳入发现流程”引发的显示噪音。' },
            { type: 'improve', text: '政治税率输入体验优化：在阶层详情和政治页直接输入负数时会自动切换到补贴语义并正确存储，减少手动切模式的操作成本。' },
        ],
    },
    {
        version: '2.3.42',
        date: '2026-04-09',
        isLatest: false,
        highlights: [
            '外资利润税支持全局档位与逐国覆盖，外交博弈与税收策略更灵活',
            '盟友遇袭改为自动履约参战，并支持联盟连锁参战与多战线同步生成',
            '玩家推进 AI 本土后会触发持续经济衰减，战线压力会真实传导到增长与财政',
            '训练系统新增吞吐上限与岗位优先填补，高兵力时代扩军与就业更平滑',
        ],
        changes: [
            { type: 'new', text: '新增外资利润税政策体系：全局新增“优惠税率/正常税率/加税/重税”四档，并支持按国家单独覆盖；税率结算改为“外交规则下限 + 玩家政策上调”，同时联动 AI 入境投资概率和对我关系月度变化。' },
            { type: 'improve', text: '外交与国际经济界面补充外资税率策略面板：可在总览和单国投资区直接切换税率档位、查看税收与利润流出影响，并一键恢复单国“跟随全局”策略，政策操作路径更短。' },
            { type: 'fix', text: '修复盟友被攻击事件中“参战与拒绝援助”决策链与前线生成不对称的问题：改为军事同盟自动履约参战，攻击方盟友可连锁入战，玩家盟友会同步对敌方阵营开战，前线与 war 状态一致。' },
            { type: 'improve', text: '新增玩家-AI 战线持续消耗模型：AI 被推进至本土后会按战线深度承受财富衰减、人口压力与产出惩罚，并把本土压力写入 AI 经济增长模块，避免“核心区被压制仍高速增长”。' },
            { type: 'balance', text: 'AI 战争经济按本土压力重算：人口增长、基础承载、建筑产出、战争损耗、军队可持续规模与回填速率均随入侵深度收紧；极端战线会触发明显衰退与裁军，战局反馈更符合直觉。' },
            { type: 'fix', text: '修复战斗与摩擦战多处规模失真：统一超大军团伤亡缩放尺度、提高士气崩溃阈值并加入日常士气恢复；新战线增加初始缓冲期，避免开战首日出现不合理巨额伤亡。' },
            { type: 'improve', text: '军事训练新增“吞吐量”机制并写入面板展示：每 tick 可启动训练数量受军事建筑规模约束，结合批次队列后可在高人口阶段保持可控扩军节奏，减少瞬时训练挤占岗位。' },
            { type: 'balance', text: '就业与价格机制微调：Tier0/1 基础岗位获得更高空岗填补优先级与净收入保底，库存过剩时成本底线动态下调，缓解“基层岗位长期空缺”与“高库存仍顽固高价”问题。' },
        ],
    },
    {
        version: '2.3.41',
        date: '2026-04-09',
        isLatest: false,
        highlights: [
            '十万级以上军团战斗加入缩放保护与缓存，超大规模交战更稳定',
            '军事训练队列改为批次模式，招募、补兵与取消训练操作明显提速',
            '人头税补贴会直接影响人口迁移信号，补贴政策引导效果更直观',
            '和谈与赔款日志全面中文化，战后结果反馈更清晰',
        ],
        changes: [
            { type: 'improve', text: '重构战斗克制与战线结算性能路径：兵种克制从逐单位配对改为 5×5 类别矩阵加权，战线状态新增 tick 级缓存，战斗与摩擦战循环统一引入 Map 索引与按比例分配，减少大军团场景下的重复扫描与随机多轮扣减开销。' },
            { type: 'fix', text: '修复超大兵力战斗下中间值过大导致伤亡与补给计算失真的风险：新增大军团缩放因子并在伤亡回写时按比例还原，同时补给成本对 10 万以上兵力改为次线性增长，避免不合理的补给爆炸。' },
            { type: 'improve', text: '军事训练队列升级为“批次”结构：招募、自动补兵、容量裁剪、训练完成、取消训练与一键取消均按批次计数处理；旧存档会自动把平铺队列迁移为批次格式，后期大规模征兵卡顿明显下降。' },
            { type: 'fix', text: '修复外交事件处理中的同帧队列竞态：事件回调新增待处理事件后，当前帧会基于最新队列弹出下一条事件，避免因闭包旧值导致事件漏弹或顺序异常。' },
            { type: 'balance', text: '人口迁移规则微调：降低跨阶层升级吸引力加成、提高升级迁移门槛，并新增补贴收入信号加成；在实施负人头税补贴时，受补贴职业更容易吸引人口流入。' },
            { type: 'improve', text: '统一和谈、吞并、割让、赔款等外交结果日志文案为中文并补充战争结束语义，玩家更容易理解每次谈判的实际结局。' },
        ],
    },
    {
        version: '2.3.40',
        date: '2026-04-08',
        isLatest: false,
        highlights: [
            '旧存档读档时会自动补回缺失国家，外交页不再大片空白',
            '国家发现状态迁移补强，已出现国家不会因旧档异常集体隐藏',
            '战争、贸易、投资等旧外交引用统一校正，兼容性更稳',
        ],
        changes: [
            { type: 'fix', text: '修复部分旧存档在读档后国家 roster 丢失或被精简，导致外交页、附庸、战争与贸易对象大量消失的问题：加载时会按国家模板自动补回缺失国家，并保留已有状态数据。' },
            { type: 'fix', text: '修复旧存档国家发现状态被污染后，明明已经进入当前时代的国家却几乎全部隐藏的问题：新增 discoveryVersion 迁移，并在可见国家异常过少时自动恢复已出现国家的 discovered 状态。' },
            { type: 'improve', text: '读档迁移现在会统一规范旧 nationId 及其别名，并同步清洗组织、战线、战斗、投资、商贸与附庸外交队列中的国家引用，降低历史存档兼容性问题。' },
            { type: 'improve', text: '移除外交页与读档流程中的生产环境调试输出，减少 OTA 版本控制台噪音，便于后续继续定位真正的异常告警。' },
        ],
    },
    {
        version: '2.3.39',
        date: '2026-04-08',
        isLatest: false,
        highlights: [
            '国家发现改为渐进机制：升时代先解锁一部分，其余随探索逐步揭晓',
            'AI 发展加入难度驱动的追赶与上限约束，减少停滞与异常暴涨',
            '人头税口径统一为直接税率，商人贸易收入纳税与税基展示更一致',
            '外交与贸易国家可见性规则统一，升时代后附庸不再异常“消失”',
        ],
        changes: [
            { type: 'new', text: '新增渐进式国家发现系统：时代升级时只解锁同代国家的一部分，后续按 tick 概率继续发现；航海家人口与时代阶段会提高发现概率，探索过程更有层次感。' },
            { type: 'fix', text: '修复国家可见性判定分散导致的显示不一致：外交页、贸易路线与模拟层统一改为 nationVisibility 判断，附庸可见性和已吞并过滤口径一致，避免升时代后列表对象异常。' },
            { type: 'improve', text: '对“已出现但未发现”的国家启用最小化后台增长，避免完全停摆；被发现后能以更自然的经济状态进入玩家视野。' },
            { type: 'improve', text: 'AI 发展系统增加难度驱动的人口/财富追赶与软上限：在人口或人均财富落后时获得追赶加成，接近上限时递减增速，抑制两极化并减少后期停滞。' },
            { type: 'fix', text: '修复 AI 多路径同时改写人口/财富导致的增长冲突：人口、财富与 GDP 更新统一收敛到 AIEconomyService/AIDevelopmentService，并补回战时伤亡压力，增长曲线更稳定。' },
            { type: 'balance', text: '人头税改为“直接税率比率”口径（默认 5%），旧存档自动迁移到 v3 税率格式；税收效率公式调整为“损耗恢复”模型并限制在 100% 以内，税收结果更符合预期。' },
            { type: 'fix', text: '修复商人贸易收入在征税时序中的遗漏：新增上一 tick 贸易收入计税并同步应税收入展示，税基与财务面板口径不再错位。' },
            { type: 'fix', text: '修复非 full tick 时建筑详情加成来源“闪一下就消失”的问题：恢复 modifiers 缓存回填顺序，来源分解在高频模拟下也能稳定显示。' },
        ],
    },
    {
        version: '2.3.38',
        date: '2026-04-05',
        isLatest: false,
        highlights: [
            '附庸批量政策入口下沉到附庸列表，就地调整更顺手',
            '税收批量设置支持人头税负值补贴，批量托底更直接',
            '附庸列表过滤已吞并国家，批量操作对象更准确',
        ],
        changes: [
            { type: 'improve', text: '附庸批量政策面板从外交总布局内联实现改为内聚到附庸概览面板：玩家可在附庸列表区域直接打开并批量下发政策，操作路径更短、维护结构更清晰。' },
            { type: 'fix', text: '修复附庸管理中仍可能纳入已吞并国家的问题：附庸筛选统一增加 isAnnexed 过滤，避免批量政策误作用于无效对象。' },
            { type: 'improve', text: '税收批量设置的人头税支持负值输入作为固定补贴：批量设定时会直接写入补贴值并在反馈文案中区分“税率”与“补贴”，减轻低收入阶层时更高效。' },
            { type: 'improve', text: '批量关税输入提示文案补充负值补贴语义（进出口均支持），降低参数含义误解，减少反复试错。' },
        ],
    },
    {
        version: '2.3.37',
        date: '2026-04-05',
        isLatest: false,
        highlights: [
            '政治与外交新增批量设置，税收与附庸政策可一键全局下发',
            '人头税课税口径修正：补贴免税、失业者税基回退，税负更符合预期',
            '商人分配与贸易应税收入链路修复，财政与行为统计更一致',
            '部长扩建改为缺口驱动，优先补短板产业',
        ],
        changes: [
            { type: 'new', text: '政治页新增「税收批量设置」底部面板，支持一键统一设置人头税、交易税、营业税、进出口关税，并提供全量重置，减少后期逐项调税操作成本。' },
            { type: 'new', text: '外交页新增「附属国批量政策」底部面板，可对全部附庸一次性下发外交控制、贸易/劳工/治理/军事、投资政策与朝贡率倍率，附庸管理效率显著提升。' },
            { type: 'fix', text: '修复人头税课税口径混用导致税负偏差的问题：课税基数改为「应税收入」（工资/军饷/业主与贸易收入），补贴类收入不再计税；失业者在无直接收入时回退到社会平均工资估算税基，避免异常免税或税负失真。' },
            { type: 'fix', text: '修复商人系统中「分配总数可超出实际商人数」与「贸易收入未纳入应税收入」的问题：分配结果会按总量比例收敛，商人买卖收入同步计入应税口径，税收与面板统计保持一致。' },
            { type: 'improve', text: '部长自动扩建策略改为缺口驱动：在岗位充足且预算允许时优先扩建短缺产业，移除 ROI/供需比硬门槛，扩建行为更贴近“补齐供给短板”的治理目标。' },
            { type: 'fix', text: '修复模拟异常后可能卡死的问题：Worker reject 时确保重置 simInFlight 标记，防止后续 tick 被持续跳过。' },
            { type: 'balance', text: '调整部分理念与关联经济参数（含失业相关稳定度转换系数等）并同步修正多个税负感知模块（诉求、组织度、支持度），使税收反馈与实际征收结果更加一致。' },
        ],
    },
    {
        version: '2.3.36',
        date: '2026-04-03',
        isLatest: false,
        highlights: [
            '设置中新增开关',
        ],
        changes: [
            { type: 'improve', text: '开关状态持久化到本地存储，重启后保持用户选择；切换后下次启动即生效，无需重装。' },
        ],
    },
    {
        version: '2.3.35',
        date: '2026-04-03',
        isLatest: false,
        highlights: [
            '修复 OTA 启动后误弹"建议重新安装"警告的问题',
        ],
        changes: [
            { type: 'fix', text: '修复 getOtaErrorStreak 将正常的 ota_startup 诊断记录误计入"连续 OTA 错误"的问题：连续启动 3 次 OTA 版本会触发误报弹窗；现改为仅统计真实错误类型（crash/ota_auto_rollback/ota_notify_fail/unhandled_error），正常启动记录不再计入，彻底消除误报。' },
        ],
    },
    {
        version: '2.3.33',
        date: '2026-04-03',
        isLatest: false,
        highlights: [
            '修复 OTA 热更新后闪退：延迟检查、重置策略与 bundle 清理逻辑全面加固',
            '理念卡牌正确显示各级 triggerEffects 与 converter 继承状态，升级路径更清晰',
            '内存优化：Worker 降频剥离大字段 + full tick 缓存，后期帧率更稳定',
            '移动端菜单隐藏打赏入口，桌面端功能不变',
        ],
        changes: [
            { type: 'fix', text: '修复 OTA 更新后 bundle 清理逻辑中 postDownloadProtected 未包含当前 bundle ID 的问题，避免正在使用的 bundle 被误删导致闪退；cleanupOldBundles 新增对 status=set 的 bundle 的跳过保护。' },
            { type: 'fix', text: '将 capacitor.config.json 的 resetWhenUpdate 改为 true，确保 OTA 更新后 WebView 完整重置，避免旧 JS 上下文残留引发的启动崩溃。' },
            { type: 'fix', text: '修复 vite.config.js 将 console.error/warn 一并 drop 的问题，改为仅 drop console.log/debug/info，保留错误日志以便 OTA 环境下的崩溃诊断。' },
            { type: 'improve', text: 'OTA 检查延迟 10 秒（OTA_CHECK_DELAY_MS）启动，避免与游戏初始化内存峰值叠加；下载前新增内存占用检查，超过 60% 时跳过本次下载并提示。' },
            { type: 'improve', text: '新增 OTA 启动诊断记录（civ_crash_log）：记录 bundle 版本/ID、baseURI、初始内存；Worker 启动成功/失败均写入日志，连续 3 次失败自动切换主线程模式。' },
            { type: 'improve', text: '新增 OTA 主动回滚保护：启动后 30 秒内未捕获异常 ≥ 3 次时自动调用 CapacitorUpdater.reset() 回滚到内置 bundle，防止无限崩溃循环。' },
            { type: 'fix', text: '修复理念卡牌顶部"特殊效果"区域仅读取顶层 triggerEffects（通常为空）的问题：新增 getAggregatedTriggerEffects 函数，聚合当前等级及以下所有 levels 的 triggerEffects 后展示。' },
            { type: 'improve', text: '理念卡牌"效果递进"区域新增 getLevelInheritedItems 辅助函数，正确显示 converters/ruleMods/triggerEffects 的继承状态（"🔁 继承"/"⚡ 继承前级"），避免玩家误以为升级后效果消失。' },
            { type: 'improve', text: '理念卡牌递进区域增量标签新增"▲ 新增"视觉标识，叠加感更直观；修复"无新增数值"误判：存在继承项时不再显示该提示。' },
            { type: 'improve', text: 'Worker stripPayloadForTransfer 扩展：非 full tick 时额外剥离 officials/activeFronts/activeBattles/foreignInvestmentStats/tradeOpportunities 等大型 UI-only 字段；market 仅保留 prices/wages。' },
            { type: 'improve', text: 'useGameLoop 新增 fullTickCacheRef 缓存机制：full tick 时写入 UI 专用字段，非 full tick 时从缓存读取，跳过对应 setState 调用，减少无效渲染。' },
            { type: 'improve', text: '新增 useMemoryMonitor hook：每 30 秒检测内存占用，70% 时自动降低 UI 刷新频率，85% 时暂停游戏并提示保存，连续 3 次危险时强制降速至 1x。' },
            { type: 'improve', text: '移动端（< 1024px）菜单隐藏"打赏作者"入口，桌面端功能保持不变；利用现有 {onDonate && ...} 条件渲染，不传入 prop 即完全不渲染按钮。' },
        ],
    },
    {
        version: '2.3.32',
        date: '2026-04-03',
        isLatest: false,
        highlights: [
            '修复 useGameActions 中未定义回调引发的 React 无限循环（#185）',
            '叛乱战争结束与分期赔款处理新增防御性守卫，避免空引用崩溃',
        ],
        changes: [
            { type: 'fix', text: '修复 useGameActions.js 中 handleRebellionWarEnd 调用路径上存在未定义回调时触发 React #185 无限循环的问题：在调用前添加防御性守卫，确保 callback 存在后再执行，避免渲染阶段异常重入。' },
            { type: 'fix', text: '修复玩家分期赔款处理逻辑中 paidAmount 更新与 addLog 调用在 callback 未定义时抛出空引用错误的问题：补充 undefined 检查，保证分期支付流程在各状态下均可安全执行。' },
        ],
    },
    {
        version: '2.3.31',
        date: '2026-04-02',
        isLatest: false,
        highlights: [
            '修正 AI 求和谈判中战争分数与「玩家优势」符号，意愿与战况一致',
            '首都危急强制求和日志合并赔款说明与处境提示',
        ],
        changes: [
            { type: 'fix', text: '修复 getNationNegotiationContext 将 nation.warScore 直接当作玩家优势分的问题：规则上正值表示攻击方（AI）占优、负值表示防御方（玩家）占优，现对 warScore 取反得到 playerAdvantageScore，使分数驱动求和路径、与战线联动的门槛判断与实际局势一致。' },
            { type: 'improve', text: '战线危急触发的强制求和日志在保留赔款数额的前提下，合并为一句同时说明请求和谈、赔款与「首都岌岌可危」处境，减少重复前缀。' },
        ],
    },
    {
        version: '2.3.30',
        date: '2026-04-02',
        isLatest: false,
        highlights: [
            '附庸现金朝贡改按财富存量计算，资源朝贡用对数曲线更平滑',
            'AI 战线危急求和提前于冷却判定，分片演算时也会强制触发',
            '削弱官员与政治立场带来的建筑成本减免，抬高数量惩罚保底比例',
            '减少自动补兵与贸易/官员类日志刷屏，设置中移除相关开关',
        ],
        changes: [
            { type: 'fix', text: '修复 AI 求和在「上次求和日」冷却期内被提前 return、导致战线已压至 85%+ 仍无法进入强制求和分支的问题：将首都危急强制求和逻辑前移到冷却检查之前。' },
            { type: 'fix', text: '修复 Nations 分片演算时，未在本 tick 完整处理 AI 的国家跳过 checkAIPeaceRequest、危急战线永不求和的问题：在非处理分片仍检测战线均值 ≤15% 并调用求和检查。' },
            { type: 'balance', text: '附庸现金朝贡基数从「GDP×比例」改为「财富存量×比例」，并下调 vassalGDPRate 以匹配存量量级，避免进贡几乎为零或公式不自洽。' },
            { type: 'balance', text: '附庸资源朝贡改为 log(库存+1)×基础系数 等计算，配合提高 resourceTribute.baseAmount，使大宗库存进贡递增但边际递减。' },
            { type: 'balance', text: '官员「建筑成本减免」随机词条数值区间削弱至约原 40%，防止多名官员叠加后建造成本被压得过低。' },
            { type: 'balance', text: '多条政治立场模板中的 buildingCostMod 减半，与官员词条削弱方向一致。' },
            { type: 'balance', text: '建筑成本数量惩罚的最低保留比例从 30% 提高到 50%，避免高额减免下惩罚项被几乎抵消、批量建造单价异常平坦。' },
            { type: 'improve', text: '自动补兵失败/成功及军团补充不再向事件日志逐条写入，减少高频 tick 下的日志噪音（仍保留 debug 通道）。' },
            { type: 'improve', text: '自动贸易路线进出口明细日志默认关闭；模拟中官员投资/扩建等日志与设置面板中商人交易、官员日志开关一并移除或恒关，降低后期日志压力。' },
        ],
    },
    {
        version: '2.3.29',
        date: '2026-04-01',
        isLatest: false,
        highlights: [
            '修复外资入境投资批处理竞态：多决策不再互相覆盖，合并上限检查生效',
            '投资结算改为每tick切片滚动，帧率在高投资数量时更稳定',
            '国际经济面板新增分页，大国投资列表不再卡顿',
        ],
        changes: [
            { type: 'fix', text: '【P0修复】外资入境投资（AI自主投资）批处理改为同步构建全部新记录后一次性批量 merge 写入，修复多次调用 handleDiplomaticAction 均读取旧快照导致合并上限失效、记录互相覆盖的竞态问题。' },
            { type: 'fix', text: '修复 inbound 周期处理完毕后 lastProcessDay 被错误重置为 null，导致下一轮立即重新触发（应等满10天）的节奏错误。' },
            { type: 'fix', text: '修复 useGameActions 中玩家手动建立海外投资时 investorStratum 错误写为 "state" 而非 "capitalist"，导致与 AI 自主投资路径 groupKey 不一致、合并判断失效。' },
            { type: 'fix', text: '清除 useGameActions 海外投资流程中大量遗留调试 console.log，避免高频 tick 下日志刷屏影响性能。' },
            { type: 'improve', text: '海外投资与外资投资结算从"低频批结算"改为"每 tick 切片滚动结算"，将投资列表分为若干切片，每 tick 只处理当前切片的利润计算，帧率在外资数量较多时更为平稳。投资升级逻辑独立保持低频，不受切片化影响。' },
            { type: 'improve', text: '国际经济面板（海外资产 & 外资企业）新增分页控件（每页20条），数据发生变化时自动重置到第一页，大幅改善大国后期投资列表的渲染性能。' },
            { type: 'improve', text: '移除 useGameLoop 年度节庆 useEffect 中多余的 lastFestivalYear 依赖，避免节庆触发后重新注册定时器造成的不必要副作用。' },
        ],
    },
    {
        version: '2.3.28',
        date: '2026-04-01',
        isLatest: false,
        highlights: [
            '修复战线推进到 85%+ 后 AI 依然不求和的问题',
            '战线突破 85% 时 AI 现在会主动被迫求和，首都岌岌可危时强制触发',
        ],
        changes: [
            { type: 'fix', text: '修复 AI 求和意愿对战线位置完全不敏感的问题：此前 checkAIPeaceRequest 仅依赖 warScore 和 warDuration，玩家推进到 95% 战线 AI 也不会求和。现在战线位置作为独立变量直接影响求和概率。' },
            { type: 'balance', text: 'AI 战线被压制到 15% 以下（玩家推进 ≥ 85%）时，强制触发求和并显示"首都已岌岌可危"提示，不再依赖概率骰子。' },
            { type: 'balance', text: 'AI 战线在 15%~35% 之间（玩家推进 65~85%）时，willingness 最高可额外提升 +0.5，大幅提高该区间的主动求和概率。' },
        ],
    },
    {
        version: '2.3.27',
        date: '2026-04-01',
        isLatest: false,
        highlights: [
            '军事战区支持一键发起求和，战时外交操作更顺手',
            '人口详情新增岗位到岗率总览，劳动力缺口一眼可见',
            '官员支持批量统一产业政策，内政调参效率显著提升',
            '建造/招募数量上限大幅提高，超大规模扩张更流畅',
        ],
        changes: [
            { type: 'improve', text: '军事面板与战区详情新增「发起求和」按钮，支持在战线界面直接对目标国家发起和谈，减少多层跳转操作。' },
            { type: 'improve', text: '人口详情弹窗新增「岗位就业总览」：按阶层展示在岗人数、岗位总量、缺口和到岗率，并提供综合到岗率进度条，便于快速识别用工瓶颈。' },
            { type: 'improve', text: '官员面板新增「全局官员设置」折叠区，可一键将全部在任官员的产业政策统一切换到同一策略，批量治理更高效。' },
            { type: 'improve', text: '建筑建造与军事招募的单次数量上限从 9999 提升至 999999，满足后期超大体量国家的批量操作需求。' },
            { type: 'fix', text: '修复外资税收入库后未进入税收分项展示的问题：simulation 现同步写入 taxBreakdown.foreignInvestmentTax，状态栏可正确显示外资税收条目。' },
        ],
    },
    {
        version: '2.3.26',
        date: '2026-04-01',
        isLatest: false,
        highlights: [
            '内存优化第二轮：主线程模式结果剥离、Worker 更激进的数据裁剪、审计日志按需生成',
            '高速模式（≥3x）内存占用预计再降 30-40%',
        ],
        changes: [
            { type: 'fix', text: '【紧急修复】内存优化误删 _auditLog 导致财政收支明细面板数据丢失（关税、军饷维护等条目消失）。现已恢复 _auditLog 传输，仅剥离纯调试字段。' },
            { type: 'improve', text: '【关键修复】高速模式（≥3x）下 simulateTick 结果现在也会剥离 modifiers.sources、buildingDebugData 等调试数据。此前这些数据仅在 Worker 路径被剥离，主线程路径完全保留，是高速模式内存居高不下的主因。' },
            { type: 'improve', text: 'Worker stripPayloadForTransfer 新增：每 tick 剥离 _auditLog/_debug/_auditSilverAtSpread 等审计字段；AI 国家在非完整 tick 时额外剥离 economyTraits/warHistory 等重字段。' },
            { type: 'improve', text: 'simulation.js 返回的 _auditLog 在非调试模式下使用已聚合的 auditLogArr（诊断检查已计算的结果），避免重复调用 silverChangeLog.toArray()。' },
            { type: 'improve', text: 'modifiers.sources.productionInputCost 从 IIFE 闭包改为预计算变量，消除每 tick 创建 Set + 闭包的 GC 开销。' },
            { type: 'improve', text: '高速模式下 simulationParams.nations 直接传引用（不做 map+spread），因为主线程模式不需要序列化安全副本。' },
        ],
    },
    {
        version: '2.3.25',
        date: '2026-04-01',
        isLatest: false,
        highlights: [
            '全面修复内存泄漏：清除无条件 console 调用 + 全局变量守卫，生产包零 console 残留',
            '历史数据数组改为原地更新，每次同步减少约 52 次数组分配',
            '电力等不可储存资源改用供需流量比定价，解决电价虚高问题',
            '建筑产出不足时提示具体短缺资源名称，不再笼统显示"原料不足"',
        ],
        changes: [
            { type: 'fix', text: 'simulation.js / vassalSystem.js / useGameLoop.js 中约 16 处无条件 console.log/group/warn 改为 debugLog + isDebugEnabled 守卫。Chrome DevTools 打开时不再保留海量对象引用，堆内存预计降低 60-80%。' },
            { type: 'fix', text: 'window.__buildingDebugData 改为仅在 isDebugEnabled(\'simulation\') 时赋值，不再每 tick 无条件挂载大型调试对象到全局作用域。' },
            { type: 'fix', text: 'window.__IDEOLOGY_DSL_ISSUES 添加 100 条上限并用 concat 替代 spread 展开，消除无限累积的全局数组泄漏。' },
            { type: 'fix', text: 'pendingDiplomaticEvents 队列添加 50 条硬上限，防止事件堆积时无界增长导致内存膨胀。' },
            { type: 'fix', text: '电力等 volatile 资源定价改用供需流量比（当期供给/需求）替代库存信号。库存被人为压低的不可储存资源不再被误判为"短缺"导致电价虚高；供过于求时成本底线降至 10%，价格可自然回落。' },
            { type: 'improve', text: 'setHistory 历史数据同步从每次创建新数组（[...series, value]）改为原地 push+shift，每次同步减少约 52 次数组分配，显著降低 GC 压力。' },
            { type: 'improve', text: 'Vite 生产构建新增 esbuild.drop: [\'console\', \'debugger\']，生产包主 bundle 仅余 1 个 console.error，Worker bundle 零 console 调用。' },
            { type: 'improve', text: '建筑产出受限时记录具体瓶颈资源（resourceLimitingKey），产出降低提示从笼统的"原料不足"改为"铁矿不足""电力不足"等精确提示。' },
        ],
    },
    {
        version: '2.3.24',
        date: '2026-03-31',
        isLatest: false,
        highlights: [
            '修复银币审计残差虚报：统一审计基线，消除 Worker 异步与 React 竞态导致的误差',
            '税率面板切换标签页不再丢失未提交的设置',
            '移除经济数值硬上限，高阶经济体正常运转不再被截断',
            '供需分析面板正确显示事件全局产出加成',
        ],
        changes: [
            { type: 'fix', text: '修复财政审计基线漂移：Worker 异步计算期间 stateRef 被 React 重渲染更新，导致银币审计起点偏移产生虚假残差。改为在同步区预捕获起始银币作为基线。' },
            { type: 'fix', text: '修复资源快照竞态：adjustedResources 对象在 setResources updater 延迟执行前被战斗补给扣除等后续代码修改，导致资源写回不正确。改为提前创建快照。' },
            { type: 'fix', text: '修复审计残差计算基线不一致：entryTotal 以 auditStartingSilver 为基线，而差值以 prev.silver 为基线，存在 pending delta 时两者偏移产生虚假残差。统一使用 auditStartingSilver 并扣除延迟操作增量。' },
            { type: 'fix', text: '修复军人人头税课税基数为零：军饷在人头税之后才发放导致 actualPerCapitaWage=0、军人阶层免税。回退使用上一 tick 工资信号作为课税基数。' },
            { type: 'fix', text: '修复税率面板切换标签页丢失设置：PoliticsTab 和 StratumDetailSheet 中正在编辑的税率 draft 在组件卸载时自动提交，不再因切换页签而丢失。' },
            { type: 'fix', text: '修复人头税补贴判定遗漏 JavaScript 负零（-0）的情况，补贴模式切换更可靠。' },
            { type: 'fix', text: '修复供需分析面板未显示事件全局产出修正（buildingProductionMod: all），补充对 all 键的读取和「事件全局」标签展示。' },
            { type: 'improve', text: '移除 Ledger 银币 ±1e15 硬上限和财富 1e12 硬上限，改为仅过滤 NaN/Infinity/负数，高阶经济体长期运行不再因数值溢出被截断。' },
            { type: 'improve', text: '补全 stratumConsumption 缓存：非 full-tick 模式下阶层消费数据不再丢失，供需面板数据完整性提升。' },
        ],
    },
    {
        version: '2.3.23',
        date: '2026-03-31',
        isLatest: false,
        highlights: [
            '修复战线推进到敌方领地时己方建筑仍被摧毁的严重 bug',
            '阶层收入面板补贴显示修正，人头税补贴不再重复计入',
            '朝贡上限改为亚线性缩放，大附庸不再暴利失控',
        ],
        changes: [
            { type: 'fix', text: '修复战线区域归属标记（FRONT_ZONES.ownerSide）与实际领土完全反转的严重 bug。根因是 0-50 区间被标记为守方领土、50-100 为攻方领土，但游戏逻辑中 linePosition 增加代表攻方推进、>50 即进入守方领地。导致：(1) 攻方推进后生成的资源节点来自自己的建筑而非敌方；(2) 摩擦战掠劫方向反转，AI 在玩家优势局掠劫玩家节点并摧毁玩家建筑。修复后前线领土归属与所有游戏逻辑一致。' },
            { type: 'fix', text: '修复阶层收入面板中官员阶层补贴（subsidy）显示为 0 的问题，正确读取 classFinancialData 中的补贴记录。' },
            { type: 'fix', text: '修复阶层收入总计中人头税补贴（headTaxSubsidy）与普通补贴（subsidy）重复计算。income.subsidy 已包含人头税补贴，不再单独累加；收入明细拆分为"人头税补贴"和"政府补贴"两行分别展示。' },
            { type: 'balance', text: '朝贡硬上限从固定 10 万改为基于附庸 GDP 的亚线性缩放（平方根）。大经济体附庸的朝贡上限会随 GDP 增长，但增速始终低于线性，避免超大附庸一次朝贡即暴富。' },
        ],
    },
    {
        version: '2.3.22',
        date: '2026-03-31',
        isLatest: false,
        highlights: [
            '修复解散部队必定卡死闪退的严重 bug',
            '财政审计诊断增强：自动定位银币收支差异来源',
        ],
        changes: [
            { type: 'fix', text: '修复批量解散部队（x10/x100/x1000）时游戏卡死闪退。根因是 for 循环逐个调用 disbandUnit，每次触发 setArmy + addLog 状态更新，最多排队 2000-3000 次 React 状态更新导致主线程阻塞。改为 disbandUnit 支持 count 参数，单次调用完成全部解散。' },
            { type: 'fix', text: '修复关税补贴审计条目在已存在普通补贴条目时重复计入，导致财政审计差异报警。' },
            { type: 'fix', text: '修复 simulation 内 startingSilver 基线在贸易路线修改 res.silver 之后才捕获，导致审计起点偏移、差异虚报。改为在 spread copy 后立即记录。' },
            { type: 'improve', text: '财政审计诊断增强：simulation 内新增 10 个阶段检查点（生产、税收、军费、消费、官员、市场等），差异 >0.1 时自动输出阶段级告警，快速定位银币泄漏源。' },
            { type: 'improve', text: 'gameLoop 审计诊断细化：不一致时拆分 sim 内部差异与 gameLoop 层差异，并输出 silverAtSpread/silverAfterTradeRoute 等关键快照，便于排查。' },
        ],
    },
    {
        version: '2.3.21',
        date: '2026-03-31',
        isLatest: false,
        highlights: [
            '内存持续增长全面治理：消除 6 类泄漏源，长时间游戏不再卡顿',
            '新增崩溃上报系统：闪退、OOM 等异常自动记录并上报',
            '修复腐败收入双重扣款导致的国库异常',
        ],
        changes: [
            { type: 'improve', text: '禁用零消费者的 Zustand store 同步（useStoreSync），每次渲染减少 90+ 字段对象创建与完整 gameState 深比较开销。' },
            { type: 'improve', text: '游戏循环中 6 处动态 import() 改为静态 import，消除每 tick 的 Promise 创建、微任务调度与闭包累积。' },
            { type: 'improve', text: 'stateRef 改为 Object.assign 就地更新，避免依赖变化时重建 90+ 字段新对象。' },
            { type: 'improve', text: 'IndexedDB 存档连接单例化，避免每次存档操作重复打开连接导致资源泄漏。' },
            { type: 'improve', text: '移除无 UI 消费者的 resourceChangeLog 与 classWealthChangeLog 审计日志，减少每 tick 数十个临时对象分配。' },
            { type: 'improve', text: 'treasuryChangeLog 改为批量写入，多条日志合并为单次 setState 调用。' },
            { type: 'improve', text: 'nations 清理增强：每 100 tick 同步清除已亡国家的外交关系、海外投资、活跃前线等关联数据，防止数组无限膨胀。' },
            { type: 'improve', text: 'priceHistory 最大长度从 365 降至 90 天，数组更新改为单次分配，减少每 tick 内存创建量。' },
            { type: 'improve', text: 'window 全局调试变量（__PERF_STATS、__APPLY_SECTIONS）仅在 __PERF_LOG 开启时写入，正常游戏零开销。' },
            { type: 'new', text: '新增崩溃上报系统（crashReporter）：自动捕获 JS 错误与未处理 Promise 拒绝，通过 GA + 自研后端上报。' },
            { type: 'new', text: '新增 AppErrorBoundary：React 渲染崩溃时展示友好错误页面并上报，不再白屏。' },
            { type: 'new', text: '应用启动时自动检测上次会话是否异常退出（OOM/强杀），并在 analytics 初始化后上报崩溃日志。' },
            { type: 'fix', text: '修复 Ledger._deduct 未返回实际扣除金额，导致余额不足时记账金额与实际扣款不一致。' },
            { type: 'fix', text: '修复腐败收入处理中 applySilverChange 与 ledger.transfer 双重扣除国库，改为仅通过 ledger.transfer 执行一次扣除+记账。' },
            { type: 'fix', text: '修复动态 import 改静态后投资代码引用未初始化变量 adjustedMarket 导致 ReferenceError。' },
        ],
    },
    {
        version: '2.3.20',
        date: '2026-03-31',
        isLatest: false,
        highlights: [
            '修复玩家中途闪退：消除贸易清理与成就系统引发的 React 无限渲染循环',
            '高速模式 UI 不再卡顿：数据展示与逻辑同步更新，告别延迟感',
            '防御性容错：.map 未定义、解构崩溃等边界场景加固',
        ],
        changes: [
            { type: 'fix', text: '修复贸易路线清理 effect 导致 React #185 (Maximum update depth exceeded) 闪退。根因是 useEffect 依赖了自己写入的 tradeRoutes/merchantState state，国家吞并时触发清理→setState→重跑 effect→无限循环。改为通过 ref 读取最新值，effect 仅依赖 nations 变化。' },
            { type: 'fix', text: '修复成就解锁时嵌套 setState 引发额外渲染风暴。此前 setAchievementNotifications 被放在 setUnlockedAchievements 的 updater 内部调用，React 批处理期间的嵌套 setState 导致不可预测的重渲染。改为 queueMicrotask 延迟通知更新。' },
            { type: 'fix', text: '修复 incrementAchievementProgress 每次调用都创建新 state 对象。当 amount=0 或值无变化时现在直接返回旧引用，避免触发不必要的重渲染。' },
            { type: 'fix', text: '修复成就函数（unlockAchievement / incrementAchievementProgress / dismissAchievementNotification）每次渲染创建新引用，导致依赖它们的 useEffect 无限重触发。已包裹 useCallback 稳定引用。' },
            { type: 'fix', text: '修复经济指标变量 indicators 在高速模式下 ReferenceError：原 const 声明位于 if (_shouldUpdateUI) 块内，高速 tick 跳过该块后后续代码引用未定义变量。已提升 let 声明到块外。' },
            { type: 'fix', text: '新增防御性保护：WikiModal 中 .map 调用前检查数组存在、IdeologyCard/IdeologyTab 中解构前添加空值兜底、useGameActions 中阵列操作容错。' },
            { type: 'improve', text: '高速模式 UI 更新频率从每 5 tick 一次提升至每 tick 同步更新。由于组件每 tick 已因 15+ 个非降频 setState 而重渲染，额外 setState 通过 React 批处理合并，实际渲染开销几乎不变，但数据展示延迟从最多 4 tick 降至 0。' },
        ],
    },
    {
        version: '2.3.19',
        date: '2026-03-31',
        isLatest: false,
        highlights: [
            '5 倍速挂机闪退深度修复：UI 渲染降至 ~1 次/秒，内存分配大幅减少',
            '补贴建筑不再误停产：补贴收入正确计入边际收益判定',
            '人头税负税率（补贴）计算修正',
        ],
        changes: [
            { type: 'improve', text: '高速模式（≥3x）UI 深度降频：每 5 tick 才执行一次完整 UI 更新（popStructure、rates、classInfluence、jobFill 等 20+ 项展示数据），中间 tick 仅更新模拟关键状态（resources、buildings、nations、market 等）。React 渲染频率从 5 次/秒降至 ~1 次/秒。' },
            { type: 'improve', text: '经济指标计算降频：calculateAllIndicators、updatePriceHistory、calculateEquilibriumPrices 在高速模式下仅每 5 tick 执行一次，消除最大的单次 CPU + 内存开销。' },
            { type: 'improve', text: '高速模式 nations 零拷贝：主线程模拟时 simulationParams.nations 直接引用原数组，跳过每 tick 全表 .map() + spread 产生的 GC 压力。' },
            { type: 'fix', text: '修复 eventHistory 和 battleNotifications 运行时无上限增长：长时间游戏中事件历史可无限累积，现加入运行时硬上限（eventHistory 200 条、battleNotifications 20 条）。' },
            { type: 'fix', text: '修复受补贴建筑误停产：此前补贴收入未计入边际收益判定，导致即使政府给予高额补贴，建筑仍因"市场价亏损"而停产。现将补贴视为保底收入纳入有效收益计算。' },
            { type: 'fix', text: '修复人头税负税率场景下税后工资计算错误：此前 Math.max(0, taxCost) 在补贴场景下将负税成本截断为 0，导致补贴未实际增加工人净收入。' },
        ],
    },
    {
        version: '2.3.18',
        date: '2026-03-31',
        isLatest: false,
        highlights: [
            '营业税所见即所得：输入50就是50%税率，输入-500就是每栋补贴500🪙',
            '移除补贴金额上限，玩家可自由设定任意补贴额度',
            '建筑/阶层详情面板：修改税率后右侧即时同步显示',
        ],
        changes: [
            { type: 'improve', text: '营业税系统彻底重构为所见即所得（WYSIWYG）：移除 0.03 基准税率的间接换算层，正值直接存储实际税率（输入50即50%），负值直接存储每栋补贴金额（输入-500即补贴500🪙/栋），从 UI 输入到存储到模拟计算全链路一致。' },
            { type: 'improve', text: '移除营业税补贴方向的上限限制：此前补贴被 MAX_BUSINESS_TAX 间接卡死在375🪙/栋，现在补贴金额不设上限，征税方向仍保留1000%上限。' },
            { type: 'fix', text: '修复建筑详情面板营业税补贴显示不同步：修改左侧补贴金额后右侧立刻显示对应设定值，不再依赖下一模拟 tick 的滞后数据。' },
            { type: 'fix', text: '修复阶层详情面板人头税补贴显示不同步：同上，补贴模式下右侧直接显示当前设定值。' },
            { type: 'fix', text: '修复建筑详情面板营业税无法输入小数：此前输入 2. 时小数点被 Number 解析吞掉，导致无法继续输入到 2.5。改为保留原始输入字符串，仅在提交时做数值转换。' },
        ],
    },
    {
        version: '2.3.17',
        date: '2026-03-31',
        isLatest: false,
        highlights: [
            '修复宣战后军事界面空白的竞态 bug',
            '高倍速（≥3x）自动切换主线程模拟，根治移动端 OOM 闪退',
            'Worker 传输动态降频，进一步降低内存分配压力',
        ],
        changes: [
            { type: 'fix', text: '修复宣战确认后跳转军事界面显示空白的 bug。根因是游戏循环用直接赋值（setActiveFronts(simResult)）覆盖了用户在 tick 运行期间创建的新战线/会战，改为函数式合并更新后新建的战线不再被吞掉。' },
            { type: 'improve', text: '游戏速度 ≥3x 时自动禁用 Web Worker，改为主线程直接执行模拟。彻底消除 postMessage 结构化克隆带来的内存开销（5x 速度下从 300-900MB/分钟降至接近零），以少量 UI 卡顿换取内存安全，根治高倍速挂机闪退。' },
            { type: 'improve', text: 'Worker 输出数据按游戏速度动态降频：大型 UI 面板数据（财务明细、支持度分解、市场 breakdown）改为每 10×gameSpeed tick 传输一次，其余 tick 设为 null 并由主线程使用缓存值，1-2x 速度下也显著降低内存分配。' },
            { type: 'improve', text: '条件化 setState：approvalBreakdown、classFinancialData、buildingFinancialData 仅在 Worker 传回有效数据时更新 React state，避免空值覆盖导致面板闪烁。' },
        ],
    },
    {
        version: '2.3.16',
        date: '2026-03-31',
        isLatest: false,
        highlights: [
            '移除资源库存自然衰减机制，囤积资源不再无故损耗',
        ],
        changes: [
            { type: 'remove', text: '移除资源库存超量衰减机制：此前当库存超过需求×目标天数×3 时，超出部分每 tick 自动衰减 2%（以"变质、失窃"为由）。该机制导致玩家精心囤积的资源莫名减少，现已完全移除。易挥发资源（电力）的溢出清零不受影响。' },
        ],
    },
    {
        version: '2.3.15',
        date: '2026-03-31',
        isLatest: false,
        highlights: [
            '移动端闪退修复：大幅削减每 tick 内存分配，缓解长时间运行后 OOM 崩溃',
            '调试数据按需生成：非开发模式不再创建大量冗余对象',
            '财务面板更新降频：减少 React state 更新频率，降低 GC 压力',
        ],
        changes: [
            { type: 'fix', text: '修复移动端运行约 10 分钟后渐进式卡死直至被系统强杀的问题。根因是每 tick 无条件创建大量调试对象（buildingDebugData、silverChangeLog、classWealthChangeLog、militaryDebug、freeMarketDebug 等），在手机 WebView 有限堆内存下 GC 追不上分配速度导致 OOM。' },
            { type: 'improve', text: 'simulation.js 中所有调试数据（buildingDebugData、classWealthChangeLog、resourceChangeLog、militaryDebug、freeMarketDebug）改为仅在 isDebugEnabled("simulation") 时生成，正常游戏时为 null/no-op，每 tick 节省约 50-200KB 对象分配。' },
            { type: 'improve', text: 'silverChangeLog 从 _debug 块提取为独立的 _auditLog 字段（财政审计仍可用），其余 _debug 数据仅 debug 模式下返回。' },
            { type: 'improve', text: 'buildingFinancialData 和 classFinancialData 的 React state 更新从每 tick 降频到每 10 tick，大幅减少 React 渲染和 GC 压力，UI 感知几乎无影响。' },
            { type: 'improve', text: 'window.__buildingDebugData 不再每 tick 强制覆盖空对象，仅在有数据时挂载，消除全局对象泄漏。' },
            { type: 'improve', text: 'supplyBreakdown 历史保留量从 30 条缩减至 10 条（每条含全资源×全建筑的完整 breakdown），节省约 20-60KB 内存。' },
            { type: 'improve', text: '理念系统指标历史深度从 90 缩减至 30（METRIC_HISTORY_LIMIT），均值窗口从 30 缩至 15，减少长期驻留内存。' },
            { type: 'improve', text: 'EconomyLedger 的 classWealthChangeLog 追踪增加 null 保护，非调试模式下不产生任何对象分配。' },
            { type: 'improve', text: '建筑生产循环中的 ownerDetails 数组改为按需创建（仅 debug 时收集），正常游戏时跳过该分配。' },
        ],
    },
    {
        version: '2.3.14',
        date: '2026-03-31',
        isLatest: false,
        highlights: [
            '粮荒死循环终结：缺粮缺布时价格加速暴涨，劳动力自动转向种地',
            '税制大幅减负：人头税基准 10%→5%，营业税基准 8%→3%',
            '建筑利润不足时显示完整成本分析明细',
            '崩溃日志持久化 + 内存监控，闪退后可回溯原因',
        ],
        changes: [
            { type: 'fix', text: '生存物资（粮食/布料）极度短缺时，价格压制权重从固定 0.4 逐步提升至 1.0（库存低于 30% 目标时线性解除），让粮价如实反映稀缺程度，打破"商人进口压价→无人转职种地→持续饿死人"的恶性循环。' },
            { type: 'fix', text: '接线生存转职逻辑：当食物/布料供需比低于 0.5 时，向生产该资源的角色转职阻力降至原来的 30%（门槛从 ~2x 降至 ~0.6x），迁移速率提升 5 倍，且忽略冷却期限制。' },
            { type: 'fix', text: '修复消费短缺记录缺少 isBasic 标记的 bug：此前粮食/布料短缺被错误归类为"奢侈品短缺"（仅扣 3 点审批），现在正确触发基本需求短缺的严厉惩罚（审批上限封顶 0 或 30）。' },
            { type: 'fix', text: '智能工资预估在生存资源紧缺时也对农民等生产者启用实时计算（此前仅在人口≤20时），确保高粮价下农业空岗在招工排序中靠前。' },
            { type: 'balance', text: '人头税基准比例从 10% 降至 5%，减轻低收入阶层税负压力；所有引用点的 fallback 值同步更新。' },
            { type: 'balance', text: '营业税基准比例从 8% 降至 3%，缓解高税负扼杀产业利润的问题；所有引用点的 fallback 值同步更新。' },
            { type: 'balance', text: '成本价计算中营业税贡献上限为非税成本的 30%，打断"高税→高价→更高税"的正反馈螺旋。' },
            { type: 'balance', text: '边际收益计算移除营业税项（视为利润分配而非生产成本），避免营业税误导建筑停产决策。' },
            { type: 'fix', text: '人头税上限不超过生活成本的 50%，防止极端税率下阶层因税致贫。' },
            { type: 'fix', text: '承诺任务、组织度系统、审批模块的税负计算统一使用收入比例公式，与主模拟保持一致。' },
            { type: 'improve', text: '建筑利润不足时显示详细分析面板：营收、原料成本、工资支出、营业税、每栋预计盈亏一目了然。' },
            { type: 'improve', text: '全局错误收集器升级：崩溃日志持久化到 localStorage（最多 50 条），闪退重启后弹窗展示；新增每 30 秒内存采样监控，辅助定位内存泄漏。' },
            { type: 'fix', text: '建筑财务数据补全 ownerRevenue 和 businessTaxPaid 实时跟踪，修复利润面板数据缺失。' },
        ],
    },
    {
        version: '2.3.13',
        date: '2026-03-31',
        isLatest: false,
        highlights: [
            'APP 启动时自动清理旧版本 OTA 缓存，防止存储空间膨胀',
        ],
        changes: [
            { type: 'improve', text: '新增 OTA 旧 bundle 自动清理：每次启动后识别当前使用的 bundle，删除所有非当前版本的旧包（每个约 29MB），频繁更新不再导致缓存持续增长。' },
            { type: 'improve', text: 'Capacitor 配置补充 autoDeleteFailed 和 autoDeletePrevious，双重保障原生层也主动清理失败和过期的 bundle。' },
        ],
    },
    {
        version: '2.3.12',
        date: '2026-03-31',
        isLatest: false,
        highlights: [
            '移除资源数值硬上限（1000兆），资源积累不再被人为封顶',
        ],
        changes: [
            { type: 'fix', text: '移除 simulation 中 SAFE_VALUE_CAP (1e15) 对资源总量的硬性钳制。此前资源通过 applyResourceChange 路径变动时，单次增量和累计总量均被限制在 ±1e15（1000兆），后期高产能经济体资源会卡在上限无法增长。现在仅保留 NaN/Infinity 防护，不再设置数值天花板。' },
        ],
    },
    {
        version: '2.3.11',
        date: '2026-03-31',
        isLatest: false,
        highlights: [
            '营业税补贴改为每栋固定金额，告别"按比例补贴越亏越补"的怪圈',
            '修复营业税正税金额翻倍 bug 与多个事件效果崩溃',
            '教程系统与日志回调引用稳定化，彻底消除 React 无限渲染',
        ],
        changes: [
            { type: 'fix', text: '营业税正税路径 businessTaxPaid 被 ledger 自动记录后又手动累加一次，导致正税金额翻倍入账。移除重复累加。' },
            { type: 'fix', text: '事件选项非数组时 filterEventOptions 返回原值导致 EventDetail .map() 崩溃，兜底改为返回空数组。' },
            { type: 'fix', text: '事件效果写入 setActiveEventEffects 时，approval/stability/resourceDemand/stratumDemand/buildingProduction 五个字段统一加 Array.isArray 防护，防止旧存档中对象格式数据触发 spread 异常。' },
            { type: 'fix', text: '策略行动的 approvalChanges 写入格式从对象嵌套改为数组追加，与新的 activeEventEffects.approval 结构保持一致。' },
            { type: 'fix', text: 'addLog 回调因依赖 gameState 每帧重建，通过 useRef 持有 setLogs 让引用完全稳定，消除下游 useEffect 不必要重跑。' },
            { type: 'fix', text: '教程系统 useTutorialSystem 将 gameState 整体从依赖数组移除，改用 gameStateRef + 具体原始值字段，修复 React #185 无限渲染循环。' },
            { type: 'improve', text: '营业税 UI 根据正负值自适应显示"税率(%)"或"补贴(🪙/栋)"，标签、占位符、说明文案全部联动，玩家一眼看清当前模式。' },
            { type: 'balance', text: '营业税补贴模式从按营收比例改为每栋固定金额：负数值直接表示每栋每次产出补贴的金币数，计算更直观、补贴总额可预测。' },
            { type: 'balance', text: '营业税正税征收改用实际产出（actualMultiplier）替代人员配比估算（staffingRatio），使税额与真实产值精确挂钩。' },
        ],
    },
    {
        version: '2.3.10',
        date: '2026-03-30',
        isLatest: false,
        highlights: [
            '修复人头税按岗位工资而非人均收入征收的严重计算错误——设 20% 税率实际可能收超过 100% 收入',
        ],
        changes: [
            { type: 'fix', text: '人头税征收从"按岗位工资信号"改为"按当期每人实际工资收入"计算。旧逻辑使用 market.wages（每个岗位的日薪），在就业率低于 100% 时远高于人均收入，导致设定 20% 的税率实际税额可超过人均收入的 100%。' },
            { type: 'fix', text: '官员人头税同步修正：使用官员本 tick 实际到手薪俸作为税基，而非全局工资信号。' },
            { type: 'fix', text: '不满度分析（demands）和组织度系统（organizationSystem）的头税估算同步修正，使用实际人均收入而非岗位工资信号，确保税负评估与实际征收一致。' },
            { type: 'fix', text: '建筑详情营业税"实际税额"始终显示 0：buildingFinancialData.businessTaxPaid 从未被写入，现在在征税和补贴时正确记录实际金额。' },
        ],
    },
    {
        version: '2.3.9',
        date: '2026-03-30',
        isLatest: false,
        highlights: [
            '紧急修复 Worker 崩溃（window is not defined），恢复 95%+ 玩家的游戏线程',
            '修复无限渲染循环（React #185）和多个运行时空指针错误',
        ],
        changes: [
            { type: 'fix', text: 'Web Worker 崩溃修复：gameanalytics SDK 在模块初始化时访问 window 导致 Worker 环境 100% 崩溃，通过注入兼容垫片（workerGlobals）在 SDK 加载前创建最小化 window 代理。影响约 400+ 玩家的 1449 次报错。' },
            { type: 'fix', text: '修复 React Error #185 无限渲染循环：useGameActions 每次渲染返回新对象引用导致依赖它的 useEffect 反复触发，改为 useRef 保持稳定对象引用。影响 152 玩家。' },
            { type: 'fix', text: '修复事件选项 undefined.map 崩溃：filterEventOptions 在 options 非数组时返回原值而非空数组，导致 EventDetail 组件 .map() 时崩溃。' },
            { type: 'fix', text: '修复 result.logs / nextOfficials 等多处空指针：添加 Array.isArray 防护，防止 Worker 返回数据缺失时触发 "is not iterable" 和 "map is not a function" 错误。' },
        ],
    },
    {
        version: '2.3.8',
        date: '2026-03-30',
        isLatest: false,
        highlights: [
            '人头税征税上限 1000%、营业税范围 ±1000%，杜绝极端税率导致的经济崩盘',
            '旧存档迁移改为按实际收入反算税率，迁移后税额与旧版一致',
        ],
        changes: [
            { type: 'fix', text: '旧存档迁移不再暴力钳制——改为用存档中的阶层工资反算旧税额占收入的比例，再换算为新税率，迁移后玩家实际税收与旧版基本一致。' },
            { type: 'balance', text: '人头税征税模式上限从无限制收紧至 1000%（UI 输入超出自动钳制），避免玩家设置天文数字税率导致经济系统崩溃。' },
            { type: 'balance', text: '营业税范围从 ±80 万% 收紧至 ±1000%，建筑详情面板的范围提示同步更新。' },
        ],
    },
    {
        version: '2.3.7',
        date: '2026-03-30',
        isLatest: false,
        highlights: [
            '人头税改为收入百分比制，补贴改为银币绝对值制，税收/补贴完全分离',
            '修复人头税在工资发放前就收取导致只能从剩余存款扣税的重大时序缺陷',
            '旧存档安全迁移：高额旧乘数自动降至 10% 安全税率，避免经济崩盘',
        ],
        changes: [
            { type: 'fix', text: '人头税收取时序从 preProduction 移到 productionLoop 之后——现在先发工资再收税，税收可以从"收入 + 存款"中扣除，而非只能从上一轮剩余存款中收取。' },
            { type: 'fix', text: '旧存档加载时，正值乘数超过 1.0（对应 >10% 收入税）的自动钳制到 10%，负值乘数转为绝对银币补贴，防止旧存档经济崩盘。使用 _headTaxVersion 标记避免重复迁移。' },
            { type: 'improve', text: '人头税 UI 重构：税收模式用百分比输入（如 20%），补贴模式用银币绝对值输入（如 0.50 银币/人/日），两种模式用"税/补"按钮一键切换。' },
            { type: 'improve', text: '阶层详情和政治面板的税率卡片同步更新——补贴模式显示"补贴 X.XX ₴/人/日"而非令人困惑的负百分比。' },
            { type: 'improve', text: '财务明细新增"人头税补贴"收入行，总收入计算也纳入该项，不再遗漏补贴对净收入的贡献。' },
            { type: 'balance', text: '收入为零的阶层不再被征收人头税（旧逻辑会按微小的 headTaxBase 兜底征收），生活成本计算同步修正。' },
            { type: 'balance', text: '组织度系统补上缺失的 effectiveTaxModifier 传参，税负评估与实际征收完全一致，不再出现"税率看着低但民众很不满"的偏差。' },
        ],
    },
    {
        version: '2.3.6',
        date: '2026-03-30',
        isLatest: false,
        highlights: [
            '修复人头税补贴金额在阶层详情中显示为 0 的问题',
            '修复升级时代界面成本不含人口规模系数的问题',
        ],
        changes: [
            { type: 'fix', text: '阶层详情面板的补贴金额不再显示 0.000——新增 headTaxSubsidy 数据追踪，UI 在补贴模式下正确读取实际发放金额。' },
            { type: 'fix', text: '时代升级成本 UI 现已同步人口规模缩放系数，显示的成本与实际检查完全一致，不再出现"条件全绿却无法升级"的困惑。' },
        ],
    },
    {
        version: '2.3.5',
        date: '2026-03-30',
        isLatest: false,
        changes: [],
    },
    {
        version: '2.3.4',
        date: '2026-03-30',
        isLatest: false,
        highlights: [
            '税制改革：营业税按营收比例、人头税按收入比例，UI 所见即所得',
            '理念联动可视化：选理念时直接看到搭配对象与机制效果',
            '时代升级成本随国家规模缩放，中后期不再一键秒升',
            '附庸战争分数对数增长并封顶 2500，不再天文数字',
        ],
        changes: [
            { type: 'fix', text: '修复全局错误处理器在 error 对象为 null 时无法记录诊断信息的问题，现在会记录 message、filename、lineno。' },
            { type: 'improve', text: '理念卡片在候选模式下显示联动搭配方名称，联动/冲突条展示描述文案与机制效果标签（自动建造、资源回声等），选理念时不再盲选。' },
            { type: 'improve', text: '营业税与人头税 UI 改为所见即所得：左侧直接输入百分比税率，右侧显示实际征收银币数额，告别抽象的"倍率系数"。' },
            { type: 'improve', text: '游戏百科与新手教程同步更新税制说明，新玩家不会看到过时的固定税额描述。' },
            { type: 'balance', text: '营业税改为按建筑营收比例征收（基准 8%），人头税改为按阶层日均收入比例征收（基准 10%），取代旧的固定数额制，税负更公平。' },
            { type: 'balance', text: '时代升级成本引入人口规模系数（对数缩放），国家越大升级越贵，中后期尤其官员出场后不再轻松秒升。' },
            { type: 'balance', text: '古典时代升级移除文化 250 需求——青铜时代缺乏自然文化来源，不再卡玩家进度。' },
            { type: 'balance', text: '附庸化所需战争分数改为对数递增并封顶 2500，3 个附庸后不再线性 +400 导致分数暴涨至万分。' },
            { type: 'balance', text: '官员私产上限设为 3 + 当前时代数，且现有建筑岗位填充率低于 85% 时不再投资新建筑，遏制官员囤积空置产业。' },
            { type: 'new', text: '新增青铜时代文化建筑"长者祭坛"与科技"口述传统"（每人每日 +0.001 文化），为进入古典后积累文化打下基础。' },
        ],
    },
    {
        version: '2.3.3',
        date: '2026-03-30',
        isLatest: false,
        highlights: [
            '战斗系统全面重写：兰彻斯特杀伤模型，碾压局秒杀、精锐兵种质量优势真实体现',
            '饥荒自然抑制人口增长，饿死上限防止一波清零',
            '总览页新增"迈向下一时代"进度条，升级条件一目了然',
            '回归玩家欢迎横幅、新事件、底层阶层叛乱频率下调',
        ],
        changes: [
            { type: 'fix', text: '战斗系统从百分比伤亡模型重写为兰彻斯特线性杀伤模型：伤亡 = 敌方总火力 × 强度 / 我方单位防御值，碾压局（如1000人打3人）可在1天内结束，不再出现无限僵持。' },
            { type: 'fix', text: '前线摩擦战也改用兰彻斯特模型计算伤亡，移除旧的 Math.max(1) 保底逻辑，小股敌军不再每天必杀1人。' },
            { type: 'fix', text: '分析后端难度字段不再在初始化时发送默认值，改为延迟 2 秒等存档加载完毕后上报，避免统计数据失真。' },
            { type: 'fix', text: '更新日志弹窗不再对未完成教程的新玩家自动弹出，减少首次体验干扰。' },
            { type: 'fix', text: '虚拟税收上限改为基于当期税收而非国库余额，堵住国库越多→虚拟税越高→国库更多的指数增长漏洞。' },
            { type: 'fix', text: '商品售价新增成本 50% 底线，防止供过于求时价格无限趋零导致系统性通缩。' },
            { type: 'improve', text: '总览页签新增"迈向下一时代"进度条，实时展示人口、科研、科技三项升级条件的达成情况。' },
            { type: 'improve', text: '新增回归玩家欢迎横幅：离开超过 30 分钟后再回来，自动显示帝国状态摘要。' },
            { type: 'improve', text: 'AI 国家数据传输时裁剪 tradeHistory/priceHistory/resourceHistory 等大数组，降低序列化负载。' },
            { type: 'balance', text: '战斗追击最大损失率从 45% 上调至 60%，歼灭判定阈值从 5% 上调至 8%，胜负更干脆。' },
            { type: 'balance', text: '饥荒生育惩罚：全局粮食满足率低于 70% 时按比例降低出生率（最低降至 10%），人口不再在饥荒中逆势增长。' },
            { type: 'balance', text: '饿死人数每 tick 上限为总人口的 3%，防止单次饥荒直接灭国。' },
            { type: 'balance', text: '过量库存（超过目标 3 倍）每 tick 按 2% 衰减，模拟腐烂/失窃等自然损耗。' },
            { type: 'balance', text: '矿工/自耕农/樵夫的组织度乘数下调（1.2/1.1/1.1→1.0/0.9/0.9），底层阶层叛乱频率回归合理。' },
            { type: 'balance', text: '石器时代科技升级门槛从 80% 降至 55%，新手首次时代跃迁更顺畅。' },
            { type: 'new', text: '新增多个时代事件：大航海时代"航海家的请求/海盗围城/殖民地暴动"、启蒙时代"咖啡馆辩论热"等。' },
        ],
    },
    {
        version: '2.3.2',
        date: '2026-03-30',
        isLatest: false,
        highlights: [
            '修复军团补兵、战斗消失等 15 项重大 bug',
            '建筑升级数据全面校准，43 栋建筑产出回归设计意图',
            '事件效果与选择结果可视化，不再是黑箱',
            '分析上报大幅降频，高速游戏时更流畅',
        ],
        changes: [
            { type: 'fix', text: '修复军团开启自动补兵后不补充的问题：被歼灭军团的缺额现在会正确保留在补兵队列中。' },
            { type: 'fix', text: '修复有官员岗位建筑时官员岗位量显示为 0 的问题：App 层补全了容量的后备计算。' },
            { type: 'fix', text: '修复事件限时效果不再显示的问题：总览页签新增活跃效果区域，展示审批、稳定、资源需求等效果及剩余天数。' },
            { type: 'fix', text: '修复与某国处于战争状态但军事页无交战线的问题：前线重建逻辑移出主战斗块，确保每 tick 一致检查。' },
            { type: 'fix', text: '修复战斗中军队动辄自动消失的问题：歼灭阈值从 8% 下调至 5%，追击最大损失率从 60% 降至 45%。' },
            { type: 'fix', text: '修复官员概览与详情页消耗数值显示正负不一致的问题。' },
            { type: 'fix', text: '修复 useGameLoop 中 formatNumberShortCN 未定义的运行时报错。' },
            { type: 'fix', text: '修复 useGameLoop 大量中文注释和日志因 GBK 双重编码显示为乱码的问题，约 380 处恢复为正确中文。' },
            { type: 'improve', text: '事件选项选择后新增详细反馈：显示具体资源加减数量与概率事件的判定结果。' },
            { type: 'improve', text: '工业生产加成现在在资源供需分析面板中正确体现。' },
            { type: 'improve', text: '建筑升级面板新增批量数量输入框，可一次指定升/降级数量，大规模操作更高效。' },
            { type: 'improve', text: '暂停/开始按钮尺寸增大，移动端横屏缩放比例上调，操作更易点击。' },
            { type: 'improve', text: '高频调试日志（财政/性能/附庸等）改为按标志位输出，正常游戏时控制台不再被刷屏。' },
            { type: 'improve', text: '分析后端上报频率大幅降低：周期采样间隔 30 天→90 天，AI 采样压缩 70%，flush 阈值与心跳间隔分别放宽 4 倍和 2 倍。' },
            { type: 'balance', text: '全面校准 43 栋建筑的升级产出与消耗：因基础值调整后升级表未同步，116 处产出和 144 处消耗被按比例修正，升级收益回归设计意图。' },
            { type: 'balance', text: '修复石器作坊升级后工具产出反而降低的数据倒退（0.975→1.95）。' },
            { type: 'balance', text: 'AI 市场强卖强买新增库存/经济规模上限，防止无限交易。' },
            { type: 'balance', text: '附庸海外公司利润引入人口规模因子，几十人小国不再产生百万级外汇回流。' },
            { type: 'balance', text: '附庸化战争分数门槛从 600 上调至 800，后续附庸递增分也提高，抑制碾压式扩张。' },
            { type: 'balance', text: '银币财政收支新增国有建筑银产出项，财务面板数据更完整。' },
            { type: 'balance', text: '交易税补贴上限封顶 50%，堵住 100% 补贴配合人头税无风险套利的漏洞。' },
        ],
    },
    {
        version: '2.3.1',
        date: '2026-03-28',
        isLatest: false,
        highlights: [
            '修复国库与 GDP 数值溢出导致的经济崩溃',
            '叛乱不再每回合重复触发，起义节奏更合理',
            '新时代过渡期物价平稳过渡，减少通胀冲击',
            '蒸汽时代名称修正，不再显示为工业时代',
        ],
        changes: [
            { type: 'fix', text: '修复银币与 GDP 计算中的数值溢出问题：对资源变化量与国库余额加入安全钳制（±1e15），防止附庸朝贡或虚拟税注入导致天文数字。' },
            { type: 'fix', text: '修复策略行动中 setClassOrganization 未定义的报错：组织度变化现统一通过 setRebellionStates 回写，并同步阶段与相位。' },
            { type: 'fix', text: '修复 useGameLoop 中 setMaxPopBonus 未定义的报错，补全解构。' },
            { type: 'fix', text: '修复叛乱起义事件每 tick 重复触发的问题：改为跨越 100% 阈值时仅触发一次，与酝酿/密谋阶段保持一致。' },
            { type: 'fix', text: '修复非银币资源可能出现负数库存的问题，生产资源库存不再低于 0。' },
            { type: 'balance', text: '缓解封建/探索时代二次通胀：新时代过渡期物价乘数上限从 10 渐进开放，铁矿/钢铁目标库存天数下调，减少新资源解锁时的价格飙升。' },
            { type: 'balance', text: '提高附庸化战争分数门槛至 600 并随附庸数量递增，抑制后期碾压式附庸扩张。' },
            { type: 'balance', text: '优化极端缺货时的价格乘数曲线（峰值 5.0），新增库存极端过剩（>3x）时的折价分支，物价波动更平滑。' },
            { type: 'improve', text: 'Worker 超时改为自适应策略（3s-15s），减少低端设备误判超时；模拟 payload 裁剪已阵亡/零人口国家，降低通信开销。' },
            { type: 'fix', text: '蒸汽时代名称修正：第七时代不再错误显示为"工业时代"。' },
        ],
    },
    {
        version: '2.3.0',
        date: '2026-03-27',
        isLatest: false,
        highlights: [
            '支持热更新，后续版本更新无需重新安装 APK',
            '更新进度实时可见，下载状态一目了然',
            '版本追踪统一，分析数据口径更准确',
        ],
        changes: [
            { type: 'new', text: '新增 OTA 热更新系统：后续游戏内容与修复可直接推送到已安装的 APP，无需重新下载安装包。' },
            { type: 'new', text: '热更新时屏幕底部显示实时状态提示（检查中、下载进度、下载完成），更新过程不再是黑箱。' },
            { type: 'improve', text: '版本号追踪统一使用构建注入，GameAnalytics 与自建后端的版本口径完全一致，消除硬编码回退值。' },
        ],
    },
    {
        version: '2.1.15',
        date: '2026-03-27',
        isLatest: false,
        highlights: [
            '埋点改为核心优先，低价值事件默认降噪',
            '会话上报补齐难度与国家维度，分析口径更稳定',
            '求和被拒新增明确反馈，外交结果更可解释',
            'AI 旧存档低兵力自动回填，战局强度更合理',
        ],
        changes: [
            { type: 'improve', text: '埋点治理升级为“事件组软开关”：默认保留经济/物价/人口等核心平衡数据，UI 与低价值微操事件默认关闭并支持本地快速开关，减少分析噪音、提升可用信号密度。' },
            { type: 'improve', text: '分析链路补齐会话维度：客户端初始化与心跳会持续同步难度/剧本，设计事件新增玩家国家 ID/名称上下文，服务端支持动态列探测与文本体解析，旧库未迁移时也可兼容入库。' },
            { type: 'fix', text: '修复页面关闭阶段会话结束上报易丢失的问题：结束流程新增幂等保护与 beforeunload 触发，优先 keepalive 请求并保留 sendBeacon 兜底，减少 session 时长与结束时间缺失。' },
            { type: 'fix', text: '玩家主动求和被拒时新增专门外交事件反馈：会展示提案类型、接受概率与关系惩罚，避免“只扣关系不解释”的黑箱体验。' },
            { type: 'fix', text: '修复组织度变化写回错位问题：事件效果中的 organizationChange 现在统一回写 rebellionStates，并同步阶段与相位，避免组织度面板与事件结果脱节。' },
            { type: 'balance', text: '下调富裕人口转科研/税收的相关理念系数与上限，并增强 AI 军队在旧存档下的低兵力回填，抑制后期滚雪球同时减少 AI 长期个位数兵力导致的战力失真。' },
        ],
    },
    {
        version: '2.1.14',
        date: '2026-03-26',
        isLatest: false,
        highlights: [
            '新增分析查询手册，常用 SQL 可直接复用',
            '新增命令行查询脚本，临时取数更高效',
            '分析工作流文档化，平衡排查路径更清晰',
        ],
        changes: [
            { type: 'new', text: '新增 `analytics-server/ANALYTICS_GUIDE.md` 数据分析手册：集中整理 sessions、design_events、resource_events、error_events 的字段说明、event_id 全索引与按场景分类的查询模板，便于快速定位玩法平衡与留存问题。' },
            { type: 'new', text: '新增 `analytics-server/scripts/query.cjs` 命令行查询脚本：支持通过 `node scripts/query.cjs \"SQL\"` 直接执行 SQL 并输出 JSON 结果，减少临时写脚本和手工连接数据库的重复操作。' },
            { type: 'improve', text: '新增 `skills/civ-analytics/SKILL.md` 分析技能文档，统一数据分析步骤、查询约束和结果解读流程，提升后续版本排查与调参的一致性。' },
        ],
    },
    {
        version: '2.1.13',
        date: '2026-03-26',
        isLatest: false,
        highlights: [
            '理念富裕人口转化系数回调，后期税收与科研增幅更可控',
            '岗位迁移速度与保底迁移同步优化，劳动力错配恢复更快',
            '建筑页虚拟滚动兼容父容器滚动，长列表浏览更稳定',
            '分析后端版本注入与安卓网络配置补齐，上报链路更稳',
        ],
        changes: [
            { type: 'balance', text: '下调多组理念中 wealthyPop 转化器系数（含税收与科研方向），将原先偏激进的人口转化增益回调一个数量级，缓解中后期富裕人口对财政与科技滚雪球过快的问题。' },
            { type: 'balance', text: '岗位迁移基础比例从 0.25% 提升到 1.2%，并在“来源有人口且目标有空岗”时新增至少迁移 1 人的硬保底，减少岗位长期卡死与劳动力无法流动的情况。' },
            { type: 'fix', text: '修复理念转化器读取人口来源时只识别总人口的问题：当 source 指向具体阶层时，转化逻辑现在优先读取该阶层人口；理念卡面文案同步区分“总人口”与“某阶层人口”。' },
            { type: 'fix', text: '修复建筑面板虚拟滚动在父级容器滚动场景下偶发失效的问题：滚动监听改为 capture 模式捕获文档滚动事件，长列表定位与渲染窗口更稳定。' },
            { type: 'improve', text: '分析后端上报链路改进：客户端会打印后端初始化与网络失败日志，appVersion 改为由构建阶段注入的 __APP_VERSION__，避免硬编码版本造成数据追踪口径漂移。' },
            { type: 'fix', text: '安卓端补齐网络兼容配置：新增 network_security_config 并挂载到 Manifest，WebView 允许混合内容加载，修复自建分析后端在特定网络协议组合下无法上报的问题。' },
        ],
    },
    {
        version: '2.1.12',
        date: '2026-03-26',
        isLatest: false,
        highlights: [
            '新增自建分析后端，事件缓冲批量上报与 sendBeacon 兜底',
            '埋点覆盖率从核心操作扩展到全量玩家行为与经济周期采样',
            '条约有效性判定统一加固，cancelled 状态不再遗漏',
            '建筑面板虚拟滚动 spacer 计算修复无限震荡',
        ],
        changes: [
            { type: 'new', text: '新增自建分析后端（analytics-server）：基于 Express + PostgreSQL 的独立事件收集服务，含会话管理、批量事件入库与常用查询模板；客户端通过 customBackend 适配层缓冲事件，10 秒或 50 条自动 flush，页面关闭时 sendBeacon 兜底，配置 VITE_ANALYTICS_API_URL 即可启用。' },
            { type: 'new', text: '事件埋点新增 60+ 事件类型：覆盖存档导入导出、难度/场景选择、建筑批量升降级、附庸审批/指令、和约接受/拒绝/提议、军事解散全部/取消训练/自动补兵/军饷倍率、税收调整、价格管制、贸易偏好/商人分配/路线模式、事件抉择、手动采集、理念装卸、UI 标签/子标签/速度/暂停/建筑置顶与筛选等，同时新增经济流水、市场价格、人口里程碑、饥荒死亡、稳定度等级变化、经济危机、诉求生命周期、组织度阶段、AI 行为和条约状态的周期采样。' },
            { type: 'improve', text: '所有分析事件同时双写至 GameAnalytics SDK 和自建后端，确保数据冗余；自建后端静默降级——服务不可用时不影响游戏运行。' },
            { type: 'improve', text: '事件追踪模块按类别重组（生命周期/建筑/科技/外交/附庸/和约/军事/政治/税收/贸易/事件/理念/成就/周期指标/经济流水/价格/里程碑/诉求/组织度/AI/条约/UI），结构更清晰、扩展更方便。' },
            { type: 'fix', text: '条约有效性判定统一并加固：提取 isTreatyRecordActive 公共函数，到期日优先于 status 字段判断，新增对 cancelled 状态的过滤；getActiveTreaties 同步修正，避免已取消条约仍生效。' },
            { type: 'fix', text: '建筑面板虚拟滚动的 topSpacer 高度计算不再回补自身高度：修复 spacer 高度变化 → gridTop 变化 → range 变化 → spacer 变化的无限震荡循环。' },
        ],
    },
    {
        version: '2.1.11',
        date: '2026-03-26',
        isLatest: false,
        highlights: [
            '接入 GameAnalytics 全链路埋点与 GDPR 合规开关',
            'AI 求和机制重做：持久战/僵局路径 + 战争分门槛修正',
            '附庸升时代后不再从外交与贸易面板消失',
            '理念涌现新增时代均衡与去重，候选多样性显著提升',
        ],
        changes: [
            { type: 'new', text: '接入 GameAnalytics SDK，覆盖建筑/科技/外交/军事/成就/存档等全部玩家操作与周期经济采样（每 30 游戏日），并在设置面板提供"匿名数据"GDPR 开关，关闭后不再上报任何事件。' },
            { type: 'new', text: '国有企业（代经营制）利润的国库份额现在通过 ledger 正式入账并归入财政明细（state_enterprise_profit），状态栏收入分项可直接看到国企贡献。' },
            { type: 'improve', text: '附庸国在外交、贸易路线和军事面板的可见性不再受时代窗口限制：升时代后玩家的附庸仍可正常管理、建立贸易路线和查看状态。' },
            { type: 'improve', text: '建筑购买数量和军事招募数量持久化到 localStorage：切换建筑或重载页面后数量自动恢复，上限统一为 9999，同时移除了建筑面板中每次渲染重算"最大可买数量"的高开销逻辑。' },
            { type: 'improve', text: '阶层详情的"实际税额"改为乘入完整税收修正系数（含合法性、政策和额外加成），当修正偏离 1.0 时额外显示"基准税额 × 税收修正"的分解说明。' },
            { type: 'improve', text: '理念涌现候选池新增时代均衡权重和同时代去重衰减：数量少的时代获得适度补偿，同一轮已选中某时代的理念后，该时代后续权重自动降低，减少中期时代长期霸占候选位。' },
            { type: 'fix', text: '移除战斗结算时对 nation.warScore 的冗余累加与 ±100 硬限幅：战斗阶段增量已通过 warScoreBreakdown 正确汇总，旧代码会导致战争分被双重计数且无法超过 100。' },
            { type: 'fix', text: 'AI 求和/投降逻辑重做：新增"持久战/僵局"求和路径（战争超 100 天且双方僵持时 AI 也会考虑求和），投降门槛从旧的 25/50/100 调整为 200/400/800 以匹配实际战争分量级，aiDominantOnFront 改为软惩罚而非硬阻断。' },
            { type: 'fix', text: '修复叛乱政权求和时走普通和谈流程导致叛乱态无法正确结束的问题：叛乱国家的求和现在统一走专用收尾逻辑。' },
            { type: 'fix', text: '炼钢厂前置科技修正为"机械工程"（epoch 7），要塞造价移除钢铁依赖改为纯铁+砖，贝塞麦炼钢法描述清理多余的"解锁炼钢厂"字样。' },
            { type: 'balance', text: '附庸朝贡 GDP 比例从 25% 下调至 18%，缓解附庸在发展早期被持续抽血、经济长期无法起飞的问题。' },
            { type: 'balance', text: 'AI 国家基础人口增长率从 0.32% 微调至 0.42%、增长上限从 2.5% 提高至 3.0%，减少中后期 AI"只维持不扩张"的停滞感。' },
            { type: 'balance', text: 'AI 虚拟经济利润外流系数从 18% 下调至 12%，给本地经济留更多再投资空间，间接改善 AI 财富积累与军事投入能力。' },
        ],
    },
    {
        version: '2.1.10',
        date: '2026-03-21',
        isLatest: false,
        highlights: ['年度报告改为按全年口径统计并发放理念奖励', '理念涌现跳过保底增强，高稀有理念更容易出现', '外交战争分计算与资源价格曲线显示进一步修正'],
        changes: [
            { type: 'improve', text: '年度政府工作报告改为按全年累计与全年均值统计关键经济指标：GDP 以年累计展示，CPI/PPI、税收与财政净收入改为年均口径，同时补充历史报告中的对应字段与趋势图标签，报告内容与玩家一整年的经营表现更一致。' },
            { type: 'new', text: '年度报告评分现在会发放理念分奖励：结算时按 S/A/B/C 评级分别奖励理念分，并在新年度开始后自动重置年度累计器，让年度考核与理念成长形成直接联动。' },
            { type: 'improve', text: '理念涌现的跳过机制重做：跳过后会显著提高 uncommon/rare/legendary 权重，并加入最低稀有度保底，连续跳过时下一次更容易刷出高品质理念。' },
            { type: 'improve', text: '理念库界面精简为按品质筛选，移除分类筛选的噪音；同时更新跳过提示文案，更明确说明“更易出现高稀有理念”的收益。' },
            { type: 'fix', text: '修复多处战争分读取旧 front.warScore 字段导致和谈、附庸化与战况判断口径不一致的问题：统一按 warScoreBreakdown 汇总有效战争分，并把附庸化门槛明确提升到 300、吞并门槛统一为 500。' },
            { type: 'fix', text: '修复资源详情价格曲线在小幅波动时被过早四舍五入成台阶线的问题：市场内部价格改为保留完整精度，详情图表与数值显示改用更细粒度格式化，轻微价格变化也能被正确观察。' },
        ],
    },
    {
        version: '2.1.9',
        date: '2026-03-20',
        isLatest: false,
        highlights: ['部长自动扩建改为预算驱动并支持单次连建', '建造与招募支持自定义数量输入', '修复多处显示口径与实时状态不同步问题'],
        changes: [
            { type: 'improve', text: '部长自动扩建策略参数全面配置化：新增预算比例与单次预算上限，单次触发可在预算内连续扩建多座建筑，并按部长与全局冷却协同控制节奏，提升自动扩建的可控性与执行效率。' },
            { type: 'improve', text: '建筑详情与军事面板的数量选择器支持自定义数字输入，替代仅靠固定档位切换，玩家可更精细地控制单次建造与招募规模。' },
            { type: 'fix', text: '修复 simulation 里 classLivingStandard 读取旧缓存导致的状态滞后：主循环现在显式透传并优先使用当前帧生活水平数据，降低事件与评估阶段出现口径不一致的概率。' },
            { type: 'fix', text: '修复国家详情承载率展示与当前人口口径偶发不一致的问题：承载率优先按“当前人口 / 承载上限”实时计算，避免缓存指标短暂延迟造成显示矛盾。' },
            { type: 'fix', text: '修复官员详情中立场满意状态偶发滞后的显示问题：详情面板优先使用 UI 层实时重算结果，无实时值时再回退模拟端缓存值。' },
        ],
    },
    {
        version: '2.1.8',
        date: '2026-03-20',
        isLatest: false,
        highlights: ['修复建筑升级写回竞态覆盖玩家操作', '理念稀有度分布调整为更高常见性'],
        changes: [
            { type: 'fix', text: '修复 tick 期间建筑升级写回的竞态问题：当玩家在同一 tick 内进行升级操作时，simulation 结果不再覆盖当帧玩家变更，避免升级数量被回滚或丢失。' },
            { type: 'improve', text: '新增建筑升级延迟变更合并逻辑：按 tick 基线对比 current 状态，计算并合并升级增量，确保自动升级与玩家手动操作可同时正确落地。' },
            { type: 'balance', text: '调整多项理念卡牌稀有度，将部分 uncommon 下调为 common，提升这些理念在流程中的出现概率与可获得性。' },
        ],
    },
    {
        version: '2.1.7',
        date: '2026-03-20',
        isLatest: false,
        highlights: ['建筑营业税输入加限幅与容错', '工资系统新增双底线并回写全局工资镜像', '事件外交目标过滤修复附庸/同盟误触发开战'],
        changes: [
            { type: 'fix', text: '修复建筑营业税系数输入在无效值、极端值与正负切换时的异常表现：税率输入改为支持中间输入态，并统一按 TAX_LIMITS.MAX_BUSINESS_TAX 限幅。' },
            { type: 'improve', text: '工资支付逻辑改为“雇员生计底线 + 业主保留底线”双底线机制，且按 preparedWagePlans 统一汇总各业主工资责任，降低异常工资波动与业主财富瞬时透支。' },
            { type: 'fix', text: '新增建筑级实际发薪到全局 wages 的镜像回写，修复价格、招工与投资等模块读取工资与真实支付脱节的问题。' },
            { type: 'fix', text: '修复事件外交目标选择会命中玩家附庸/军事同盟成员并触发不合理宣战的问题：事件选择器与 triggerWar/triggerPeace 现在统一排除受玩家保护的国家。' },
            { type: 'fix', text: '修复事件详情中偶发显示英文控制字段（如 exclude）的异常：外交效果徽章仅渲染有效数值目标。' },
            { type: 'improve', text: '建筑详情页补充营业税限幅提示，并优化收入说明文案，明确实际工资受生计底线、业主保留与支付比例共同约束。' },
        ],
    },
    {
        version: '2.1.6',
        date: '2026-03-20',
        isLatest: false,
        highlights: ['部长自动扩建改为分部长冷却', '修复自动补兵在战斗中失效', '修复连续操作导致的建筑/研究扣费异常', '组织度新增低人口限制'],
        changes: [
            { type: 'improve', text: '部长自动扩建系统重构：全局检查冷却缩短为 5 天，同时为农业、工业、商业、市政四位部长分别记录 10 天个人冷却，避免单个部长频繁触发把其他部长的扩建机会一并锁死。旧存档中的单个数字冷却值会自动迁移为新的对象结构。' },
            { type: 'fix', text: '修复自动补兵会跳过战斗中军团的问题：补兵需求统计和目标分配不再因为 corps 处于 in_combat 状态而被直接过滤，前线军团现在也能持续收到补员。' },
            { type: 'fix', text: '修复连续快速执行建造、升级、时代升级、科研和招募时可能读取陈旧 resources/buildings 闭包，导致花费计算异常或重复扣费的问题。关键操作现统一读取并回写最新 ref 状态。' },
            { type: 'fix', text: '修复改革法令面板 taxIncome 标签重复定义导致显示不一致的问题，统一为“税收加成”。' },
            { type: 'balance', text: '组织度系统新增最低叛乱人口门槛：人口低于 10 的阶层无法组织有效叛乱，组织度上限压到 50%；若已触发 uprising，则改为少量人口携带财富外流，而不是生成不合理的小规模叛乱。' },
            { type: 'improve', text: '外交与理念界面体验调整：战争中的国家详情页“求和”按钮改为正确触发 peace 动作；理念卡牌始终显示稀有度标签，装备中的理念也可直接打开详情底部面板。' },
            { type: 'balance', text: '若干显示与数值微调：时代演进面板改为直接读取 EPOCHS 名称，工业时代主题名称调整为“蒸汽时代”；工匠阶层低中富裕度下的工具消费需求小幅下调。' },
        ],
    },
    {
        version: '2.1.5',
        date: '2026-03-18',
        isLatest: false,
        highlights: ['橡胶/塑料/铝重新加入全阶层消费'],
        changes: [
            { type: 'balance', text: '重新加入橡胶（rubber）、塑料（plastics）、铝（aluminum）三种资源的居民直接消费：作为广泛日用品（胶鞋、塑料盆、铝餐具等），全阶层从低富裕度（1.0~2.0）即开始使用，随富裕度增长逐级增加消费量，上层阶层用量显著高于底层' },
        ],
    },
    {
        version: '2.1.4',
        date: '2026-03-18',
        isLatest: false,
        highlights: ['建筑升级岗位大幅扩充', '建筑集约化体系：后期建筑业主占比递减', '建筑升级资源解锁前置检查', '业主自动升级速度大幅提升'],
        changes: [
            { type: 'balance', text: '建筑升级岗位大幅扩充：所有建筑升级后岗位增加 50~80%/级，Lv1 产出 1.75x、Lv2 产出 3.3x，输入同步增长，确保效率比逐级明显增加' },
            { type: 'balance', text: '建筑集约化体系：调整 55 个基础建筑 + 103 个升级配置的岗位比例，业主平均占比从 E0(90%) 到 E9(5%) 严格递减，体现时代发展带来的集约化特性' },
            { type: 'balance', text: '消除零业主岗位：修复 9 个后期建筑（高级铜矿、广播站、铀矿等）缺少业主岗位的问题，每个建筑及其升级均补充 capitalist: 1 业主岗' },
            { type: 'balance', text: '岗位扩充同步缩放输入输出：所有岗位调整的建筑均按比例同步缩放资源输入和产出，缩放因子上限 2.5x，确保单位效率不变' },
            { type: 'improve', text: '建筑升级资源解锁前置检查：如果下一等级需要的输入资源尚未解锁（如高级庄园需要化肥），则禁止升级，玩家手动升级、批量升级、业主自动升级、官员投资升级均受此约束' },
            { type: 'improve', text: '升级面板 UI 增强：未解锁资源的升级按钮自动禁用，显示锁定图标和具体未解锁资源名称' },
            { type: 'improve', text: '业主自动升级速度大幅提升：单次升级概率从 2% 提高到 15%（7.5 倍），每类建筑每 tick 允许升级最多 3 座（原 1 座）' },
        ],
    },
    {
        version: '2.1.3',
        date: '2026-03-18',
        isLatest: false,
        highlights: ['新增香料种植园建筑', '修复吞并失败与联盟惩罚逻辑', '阶层角色分离：业主/雇员互斥', '修正资源消费链', '化肥成为农业建筑必需输入'],
        changes: [
            { type: 'new', text: '新增香料种植园（spice_plantation）建筑及 2 级升级配置，补充 Epoch 5 香料生产来源，完善香料资源链' },
            { type: 'fix', text: '修复吞并判定使用错误的 warScore 数据源导致吞并始终失败的问题：改用 frontWarScore 确保数据一致性' },
            { type: 'fix', text: '修正联盟 approvalCap 惩罚逻辑：惩罚强度现在与国家贫困程度正相关（越穷惩罚越重）；联盟期望面板区分显示不同类型的提示信息' },
            { type: 'improve', text: '阶层角色分离：实施业主/雇员互斥规则，同一阶层不能同时担任建筑的业主和雇员，提升经济模型的逻辑严谨性' },
            { type: 'balance', text: '修正资源消费链：从所有阶层的奢侈需求中移除 synthetic_fiber（化纤）、rubber（橡胶）、plastics（塑料）、aluminum（铝）四种工业中间品的直接消费，这些资源只应通过建筑加工为终端产品后再被民间消费' },
            { type: 'balance', text: '复合材料（composites）消费大幅加强：覆盖面从 12 个阶层扩展到全部 17 个阶层，消费门槛全面降低（上层从 2.5 降至 1.8，中层从 5.0~9.0 降至 4.5~5.0，底层新增 7.0~7.5 档），每个阶层均有 2~4 个梯度消费档位' },
            { type: 'balance', text: '化肥（fertilizer）纳入农业生产链：7 个农业/种植建筑的升级配置添加化肥输入需求（早期建筑 Lv2、工业时代建筑 Lv1 起需要化肥），添加化肥后产出额外提升 15~25%' },
            { type: 'balance', text: '橡胶园（rubber_plantation）作为 E7 建筑，基础等级即需要化肥输入，与化肥厂同时代形成资源依赖链' },
        ],
    },
    {
        version: '2.1.2',
        date: '2026-03-17',
        isLatest: false,
        highlights: ['修复未发现国家的虚空贸易', '修复官员阶层财富显示异常', '理念系统新一轮平衡调整'],
        changes: [
            { type: 'fix', text: '修复与未发现国家产生虚空贸易的问题：贸易机会扫描、商人派驻轮换与缓存执行阶段现在都会过滤 relation 为 null/undefined 的国家，避免对未发现目标创建新贸易路线。' },
            { type: 'fix', text: '修复已发起但尚在运输中的历史贸易在国家未发现后被异常清理的问题：进行中的订单会继续完成，避免已经承诺的货物与资金凭空消失。' },
            { type: 'fix', text: '修复贸易路线弹窗“进行中贸易”数量统计错误：页签计数与列表头部现在改为使用合并后的运输订单数，显示与实际列表保持一致。' },
            { type: 'fix', text: '修复跳过官员模拟时 official 阶层财富被错误清零的问题：系统会从官员个体财富重新汇总，确保阶层财富与 UI 展示正确。' },
            { type: 'fix', text: '修复阶层详情面板在需求明细存在空值时的显示异常：essentialNeeds 与 luxuryNeeds 的成本、数量、价格字段现在统一兜底为 0。' },
            { type: 'balance', text: '理念系统新一轮平衡调整：大幅重做多组理念的基础数值、转换器、条件触发与事件 Buff，整体强化理念之间的成长性、联动性与流派差异。' },
        ],
    },
    {
        version: '2.1.1',
        date: '2026-03-17',
        isLatest: false,
        highlights: ['贸易优化'],
        changes: [
            { type: 'improve', text: '贸易优化' },
        ],
    },
    {
        version: '2.1.0',
        date: '2026-03-17',
        isLatest: false,
        highlights: ['修复军团士兵不计入阶层人口的问题', '修复市场恶性清空资源 bug', '军团卡片新增可展开详情面板', '组织度面板重做', '各难度满意度阈值调整', '税收通过弹性机制自然抑制各阶层需求意愿量'],
        changes: [
            { type: 'fix', text: '修复编入军团的士兵不计入 soldier 阶层岗位需求的问题：军团内单位现在会与散兵一同参与 soldier 岗位计算，确保军人阶层人口数量、满意度、军饷转账等下游数值正确反映实际兵力' },
            { type: 'fix', text: '修复市场商人自动贸易逻辑导致的恶性清空资源 bug：移除了建筑循环内商人以自有资金强制进行以物易物的逻辑，避免市场库存被异常抽空' },
            { type: 'fix', text: '修复外交面板商人状态变更回调参数格式错误，避免商人分配数据被意外覆盖' },
            { type: 'new', text: '战线面板军团卡片新增可展开详情面板：点击军团卡片可展开查看兵种配置（按类别分组）、将领特质与加成、战斗力分项（攻击/防御/士气/将领修正）、日均军需银币折算' },
            { type: 'improve', text: '组织度面板 UI 重做：新增趋势指示（上升/下降/稳定）、组织度变化因素分析（好感度阈值对比、物资短缺驱动）、50% 上限锁定提示，视觉风格统一为古典主题' },
            { type: 'balance', text: '各难度满意度阈值下调：和平 30→25、简单 40→35、普通 50→45、困难 70→60、灾厄 85→75、地狱 90→85，降低阈值使组织度更容易衰减，减少"好感度已高但组织度不降"的体验' },
            { type: 'balance', text: '组织度衰减死区从 +5 缩小到 +3：满意度超过阈值 3 点即开始衰减（原为 5 点），减少安全区宽度，提升组织度响应灵敏度' },
            { type: 'improve', text: '税收需求弹性抑制：交易税现在会通过弹性机制自然压低各阶层对资源的需求意愿量，而非仅靠"买不起"硬截断。抑制强度综合考虑三个维度：资源需求弹性（必需品如粮食几乎不受影响，奢侈品如香料、珍馐受影响显著）、阶层人均存款充裕度（存款越充裕对税收越不敏感，富人不在乎税）、是否为奢侈性需求（luxuryNeeds 中的需求额外放大 1.5 倍敏感度）。综合抑制率上限 50%，与原有 affordable 硬截断协同工作' },
        ],
    },
    {
        version: '2.0.10',
        date: '2026-03-17',
        isLatest: false,
        highlights: ['新增年度报告历史弹窗', '信息时代视觉主题', '政体效果大幅扩展', 'Tick 预算管理与性能优化', '游戏循环重构'],
        changes: [
            { type: 'new', text: '新增年度报告历史弹窗（AnnualReportHistoryModal），支持查看历史年度报告，涵盖经济、人口、军事等多维度数据对比' },
            { type: 'new', text: '新增信息时代（epoch 8）完整视觉主题：配色方案、粒子效果与时代背景图片渲染' },
            { type: 'new', text: '政体效果大幅扩展：新增商业帝国、神权封建王国、科技联盟等多种政体配置，覆盖更多时代与政治路线' },
            { type: 'improve', text: 'Tick 预算管理：新增单帧时间预算机制（150ms 上限），防止模拟计算超时导致界面卡顿' },
            { type: 'improve', text: '节流状态分层优化：背景/装饰元素降低刷新频率，减少不必要的 React 重渲染' },
            { type: 'improve', text: 'Worker 通信优化：主线程与模拟 Worker 间消息传递重构，降低序列化开销' },
            { type: 'improve', text: '游戏循环重构：精简 useGameLoop 主循环逻辑，减少冗余状态同步' },
            { type: 'improve', text: '内阁协同效果优化：调整协同加成逻辑，提升内阁组合的策略深度' },
            { type: 'fix', text: '修复理念涌现系统中涌现条件判断的边界问题，确保理念在正确时机触发' },
            { type: 'fix', text: '修复建筑面板在特定筛选条件下的显示异常' },
            { type: 'balance', text: '进一步微调各难度下的库存目标与经济波动参数，强化难度梯度差异' },
        ],
    },
    {
        version: '2.0.9',
        date: '2026-03-16',
        isLatest: false,
        highlights: ['修复敌方停战提议接受流程', '放缓 AI 时代推进速度', '重做难度库存缓冲与价格波动', '修正营业税补贴导致的负成本价'],
        changes: [
            { type: 'fix', text: '修复接受敌方停战提议时流程未统一走战争结束逻辑的问题，避免停战状态与外交后续处理不一致' },
            { type: 'fix', text: '修复营业税为负值（补贴）时可能出现负成本价的问题，成本价现在保底为 0，避免价格模型被异常拉偏' },
            { type: 'fix', text: '清理雇员工资冷启动推导代码中的注释串行问题，避免影响后续维护与阅读' },
            { type: 'balance', text: '大幅放缓 AI 时代推进：提高各时代科技/文化需求系数，时代升级冷却由 200 提升至 600，科技文化累积速率下调至 0.4' },
            { type: 'balance', text: '重做各难度库存目标倍率：和平/简单模式增加库存缓冲提升稳定性，困难/灾厄/地狱模式降低缓冲以增强价格波动与经营压力' },
            { type: 'improve', text: '建筑利润计算改为统一通过税务模块读取营业税倍率，确保税率被正确限制在合法范围内' },
            { type: 'improve', text: '敌方停战事件按钮文案优化为“婉拒停战”，提升交互语义清晰度' },
        ],
    },
    {
        version: '2.0.8',
        date: '2026-03-16',
        isLatest: false,
        highlights: ['新增建筑/国家收藏置顶功能', '修复外交赠礼费用显示错误', '修复成衣作坊时代配置', '新增港口建筑', '平衡调整'],
        changes: [
            { type: 'new', text: '新增建筑收藏功能：建筑卡片左上角悬停出现 ⭐ 按钮，可收藏常用建筑；建筑面板新增"⭐ 收藏"过滤器，收藏数据持久保存' },
            { type: 'new', text: '新增国家收藏功能：外交国家卡片右上角悬停出现 ⭐ 按钮，可收藏常用国家；国家列表新增"⭐ 收藏"过滤器，收藏的国家自动置顶' },
            { type: 'new', text: '新增港口（harbor）建筑：epoch 1，需要航海术科技，消耗木板产出银币，填补航海术的实际解锁目标' },
            { type: 'fix', text: '修复外交赠礼费用显示与实际花费不一致的问题（UI 显示固定 100 但实际花费更高）' },
            { type: 'fix', text: '修复成衣作坊时代配置错误：从 epoch 1 调整为 epoch 2，前置科技改为高级纺织，与华服解锁时代对齐' },
            { type: 'fix', text: '修正航海术科技描述：解锁港口（而非船坞）；修正海图绘制描述：明确解锁船坞' },
            { type: 'balance', text: '小幅提升教堂基础产出：文化 3.2 → 4.0（+25%），银币 0.67 → 0.8（+20%），强化文化+财政双产出定位' },
            { type: 'balance', text: '大幅降低各理念 taxIncome 数值（约 -50%）：修复后期 income_ideology_virtual_tax 异常偏高的问题' },
            { type: 'balance', text: '同步降低各时代 taxIncome 加成：封建 0.20→0.10，探索 0.50→0.25，电气 0.30→0.15，原子 0.35→0.18，信息 0.40→0.20' },
        ],
    },
    {
        version: '2.0.6',
        date: '2026-03-15',
        isLatest: false,
        highlights: ['更新日志功能上线', '修复密谋事件反复弹出的问题', '修复同一官员反复出现的问题'],
        changes: [
            { type: 'fix', text: '修复密谋/起义事件在玩家未处理时反复弹出的问题（现在有未处理事件时不会触发新的组织度事件）' },
            { type: 'fix', text: '修复同一官员候选人反复出现的问题' },
            { type: 'fix', text: '事件弹出时游戏现在会自动暂停' },
            { type: 'new', text: '新增更新日志功能，方便玩家了解游戏更新内容' },
            { type: 'remove', text: '移除存档的"导出到剪贴板"和"从剪贴板导入"功能（已由文件导入导出替代）' },
        ],
    },
    {
        version: '2.0.5',
        date: '2026-03-15',
        highlights: ['外交系统优化', '理念系统平衡调整'],
        changes: [
            { type: 'new', text: '外交谈判新增更多条约类型' },
            { type: 'balance', text: '调整多项理念数值，修复升级收益倒挂问题' },
            { type: 'fix', text: '修复贸易路线税收计算错误' },
            { type: 'fix', text: '修复官员忠诚度在某些情况下不正确衰减的问题' },
        ],
    },
    {
        version: '2.0.4',
        date: '2026-03-14',
        highlights: ['军团系统上线', '战线管理优化'],
        changes: [
            { type: 'new', text: '新增军团编组系统，支持多军团同时作战' },
            { type: 'new', text: '新增战线管理界面，可为不同战线分配军团' },
            { type: 'new', text: '新增将领系统，将领可为军团提供战斗加成' },
            { type: 'balance', text: '调整军队维护成本计算，加入规模惩罚机制' },
            { type: 'fix', text: '修复战斗结算时部分单位数量计算错误' },
        ],
    },
];
