/**
 * 更新日志条目配置
 * 每次更新后在此数组头部添加新版本记录
 */
export const CHANGELOG = [
    {
        version: '2.3.31',
        date: '2026-04-02',
        isLatest: true,
        highlights: [
            '修正 AI 求和谈判中战争分数与「玩家优势」符号，意愿与战况一致',
            '首都危急强制求和日志合并赔款说明与处境提示',
        ],
        changes: [
            { type: 'fix', text: '修复 getNationNegotiationContext 将 nation.warScore 直接当作玩家优势分的问题：规则上正值表示攻击方（AI）占优、负值表示防御方（玩家）占优，现对 warScore 取反得到 playerAdvantageScore，使分数驱动求和路径、与战线联动的门槛判断与实际局势一致。' },
            { type: 'improve', text: '战线危急触发的强制求和日志在保留赔款数额的前提下，合并为一句同时说明请求和谈、赔款与「首都岌岌可危」处境，减少重复前缀。' },
        ],
    },
    {
        version: '2.3.30',
        date: '2026-04-02',
        isLatest: false,
        highlights: [
            '附庸现金朝贡改按财富存量计算，资源朝贡用对数曲线更平滑',
            'AI 战线危急求和提前于冷却判定，分片演算时也会强制触发',
            '削弱官员与政治立场带来的建筑成本减免，抬高数量惩罚保底比例',
            '减少自动补兵与贸易/官员类日志刷屏，设置中移除相关开关',
        ],
        changes: [
            { type: 'fix', text: '修复 AI 求和在「上次求和日」冷却期内被提前 return、导致战线已压至 85%+ 仍无法进入强制求和分支的问题：将首都危急强制求和逻辑前移到冷却检查之前。' },
            { type: 'fix', text: '修复 Nations 分片演算时，未在本 tick 完整处理 AI 的国家跳过 checkAIPeaceRequest、危急战线永不求和的问题：在非处理分片仍检测战线均值 ≤15% 并调用求和检查。' },
            { type: 'balance', text: '附庸现金朝贡基数从「GDP×比例」改为「财富存量×比例」，并下调 vassalGDPRate 以匹配存量量级，避免进贡几乎为零或公式不自洽。' },
            { type: 'balance', text: '附庸资源朝贡改为 log(库存+1)×基础系数 等计算，配合提高 resourceTribute.baseAmount，使大宗库存进贡递增但边际递减。' },
            { type: 'balance', text: '官员「建筑成本减免」随机词条数值区间削弱至约原 40%，防止多名官员叠加后建造成本被压得过低。' },
            { type: 'balance', text: '多条政治立场模板中的 buildingCostMod 减半，与官员词条削弱方向一致。' },
            { type: 'balance', text: '建筑成本数量惩罚的最低保留比例从 30% 提高到 50%，避免高额减免下惩罚项被几乎抵消、批量建造单价异常平坦。' },
            { type: 'improve', text: '自动补兵失败/成功及军团补充不再向事件日志逐条写入，减少高频 tick 下的日志噪音（仍保留 debug 通道）。' },
            { type: 'improve', text: '自动贸易路线进出口明细日志默认关闭；模拟中官员投资/扩建等日志与设置面板中商人交易、官员日志开关一并移除或恒关，降低后期日志压力。' },
        ],
    },
    {
        version: '2.3.29',
        date: '2026-04-01',
        isLatest: false,
        highlights: [
            '修复外资入境投资批处理竞态：多决策不再互相覆盖，合并上限检查生效',
            '投资结算改为每tick切片滚动，帧率在高投资数量时更稳定',
            '国际经济面板新增分页，大国投资列表不再卡顿',
        ],
        changes: [
            { type: 'fix', text: '【P0修复】外资入境投资（AI自主投资）批处理改为同步构建全部新记录后一次性批量 merge 写入，修复多次调用 handleDiplomaticAction 均读取旧快照导致合并上限失效、记录互相覆盖的竞态问题。' },
            { type: 'fix', text: '修复 inbound 周期处理完毕后 lastProcessDay 被错误重置为 null，导致下一轮立即重新触发（应等满10天）的节奏错误。' },
            { type: 'fix', text: '修复 useGameActions 中玩家手动建立海外投资时 investorStratum 错误写为 "state" 而非 "capitalist"，导致与 AI 自主投资路径 groupKey 不一致、合并判断失效。' },
            { type: 'fix', text: '清除 useGameActions 海外投资流程中大量遗留调试 console.log，避免高频 tick 下日志刷屏影响性能。' },
            { type: 'improve', text: '海外投资与外资投资结算从"低频批结算"改为"每 tick 切片滚动结算"，将投资列表分为若干切片，每 tick 只处理当前切片的利润计算，帧率在外资数量较多时更为平稳。投资升级逻辑独立保持低频，不受切片化影响。' },
            { type: 'improve', text: '国际经济面板（海外资产 & 外资企业）新增分页控件（每页20条），数据发生变化时自动重置到第一页，大幅改善大国后期投资列表的渲染性能。' },
            { type: 'improve', text: '移除 useGameLoop 年度节庆 useEffect 中多余的 lastFestivalYear 依赖，避免节庆触发后重新注册定时器造成的不必要副作用。' },
        ],
    },
    {
        version: '2.3.28',
        date: '2026-04-01',
        isLatest: false,
        highlights: [
            '修复战线推进到 85%+ 后 AI 依然不求和的问题',
            '战线突破 85% 时 AI 现在会主动被迫求和，首都岌岌可危时强制触发',
        ],
        changes: [
            { type: 'fix', text: '修复 AI 求和意愿对战线位置完全不敏感的问题：此前 checkAIPeaceRequest 仅依赖 warScore 和 warDuration，玩家推进到 95% 战线 AI 也不会求和。现在战线位置作为独立变量直接影响求和概率。' },
            { type: 'balance', text: 'AI 战线被压制到 15% 以下（玩家推进 ≥ 85%）时，强制触发求和并显示"首都已岌岌可危"提示，不再依赖概率骰子。' },
            { type: 'balance', text: 'AI 战线在 15%~35% 之间（玩家推进 65~85%）时，willingness 最高可额外提升 +0.5，大幅提高该区间的主动求和概率。' },
        ],
    },
    {
        version: '2.3.27',
        date: '2026-04-01',
        isLatest: false,
        highlights: [
            '军事战区支持一键发起求和，战时外交操作更顺手',
            '人口详情新增岗位到岗率总览，劳动力缺口一眼可见',
            '官员支持批量统一产业政策，内政调参效率显著提升',
            '建造/招募数量上限大幅提高，超大规模扩张更流畅',
        ],
        changes: [
            { type: 'improve', text: '军事面板与战区详情新增「发起求和」按钮，支持在战线界面直接对目标国家发起和谈，减少多层跳转操作。' },
            { type: 'improve', text: '人口详情弹窗新增「岗位就业总览」：按阶层展示在岗人数、岗位总量、缺口和到岗率，并提供综合到岗率进度条，便于快速识别用工瓶颈。' },
            { type: 'improve', text: '官员面板新增「全局官员设置」折叠区，可一键将全部在任官员的产业政策统一切换到同一策略，批量治理更高效。' },
            { type: 'improve', text: '建筑建造与军事招募的单次数量上限从 9999 提升至 999999，满足后期超大体量国家的批量操作需求。' },
            { type: 'fix', text: '修复外资税收入库后未进入税收分项展示的问题：simulation 现同步写入 taxBreakdown.foreignInvestmentTax，状态栏可正确显示外资税收条目。' },
        ],
    },
    {
        version: '2.3.26',
        date: '2026-04-01',
        isLatest: false,
        highlights: [
            '内存优化第二轮：主线程模式结果剥离、Worker 更激进的数据裁剪、审计日志按需生成',
            '高速模式（≥3x）内存占用预计再降 30-40%',
        ],
        changes: [
            { type: 'fix', text: '【紧急修复】内存优化误删 _auditLog 导致财政收支明细面板数据丢失（关税、军饷维护等条目消失）。现已恢复 _auditLog 传输，仅剥离纯调试字段。' },
            { type: 'improve', text: '【关键修复】高速模式（≥3x）下 simulateTick 结果现在也会剥离 modifiers.sources、buildingDebugData 等调试数据。此前这些数据仅在 Worker 路径被剥离，主线程路径完全保留，是高速模式内存居高不下的主因。' },
            { type: 'improve', text: 'Worker stripPayloadForTransfer 新增：每 tick 剥离 _auditLog/_debug/_auditSilverAtSpread 等审计字段；AI 国家在非完整 tick 时额外剥离 economyTraits/warHistory 等重字段。' },
            { type: 'improve', text: 'simulation.js 返回的 _auditLog 在非调试模式下使用已聚合的 auditLogArr（诊断检查已计算的结果），避免重复调用 silverChangeLog.toArray()。' },
            { type: 'improve', text: 'modifiers.sources.productionInputCost 从 IIFE 闭包改为预计算变量，消除每 tick 创建 Set + 闭包的 GC 开销。' },
            { type: 'improve', text: '高速模式下 simulationParams.nations 直接传引用（不做 map+spread），因为主线程模式不需要序列化安全副本。' },
        ],
    },
    {
        version: '2.3.25',
        date: '2026-04-01',
        isLatest: false,
        highlights: [
            '全面修复内存泄漏：清除无条件 console 调用 + 全局变量守卫，生产包零 console 残留',
            '历史数据数组改为原地更新，每次同步减少约 52 次数组分配',
            '电力等不可储存资源改用供需流量比定价，解决电价虚高问题',
            '建筑产出不足时提示具体短缺资源名称，不再笼统显示"原料不足"',
        ],
        changes: [
            { type: 'fix', text: 'simulation.js / vassalSystem.js / useGameLoop.js 中约 16 处无条件 console.log/group/warn 改为 debugLog + isDebugEnabled 守卫。Chrome DevTools 打开时不再保留海量对象引用，堆内存预计降低 60-80%。' },
            { type: 'fix', text: 'window.__buildingDebugData 改为仅在 isDebugEnabled(\'simulation\') 时赋值，不再每 tick 无条件挂载大型调试对象到全局作用域。' },
            { type: 'fix', text: 'window.__IDEOLOGY_DSL_ISSUES 添加 100 条上限并用 concat 替代 spread 展开，消除无限累积的全局数组泄漏。' },
            { type: 'fix', text: 'pendingDiplomaticEvents 队列添加 50 条硬上限，防止事件堆积时无界增长导致内存膨胀。' },
            { type: 'fix', text: '电力等 volatile 资源定价改用供需流量比（当期供给/需求）替代库存信号。库存被人为压低的不可储存资源不再被误判为"短缺"导致电价虚高；供过于求时成本底线降至 10%，价格可自然回落。' },
            { type: 'improve', text: 'setHistory 历史数据同步从每次创建新数组（[...series, value]）改为原地 push+shift，每次同步减少约 52 次数组分配，显著降低 GC 压力。' },
            { type: 'improve', text: 'Vite 生产构建新增 esbuild.drop: [\'console\', \'debugger\']，生产包主 bundle 仅余 1 个 console.error，Worker bundle 零 console 调用。' },
            { type: 'improve', text: '建筑产出受限时记录具体瓶颈资源（resourceLimitingKey），产出降低提示从笼统的"原料不足"改为"铁矿不足""电力不足"等精确提示。' },
        ],
    },
    {
        version: '2.3.24',
        date: '2026-03-31',
        isLatest: false,
        highlights: [
            '修复银币审计残差虚报：统一审计基线，消除 Worker 异步与 React 竞态导致的误差',
            '税率面板切换标签页不再丢失未提交的设置',
            '移除经济数值硬上限，高阶经济体正常运转不再被截断',
            '供需分析面板正确显示事件全局产出加成',
        ],
        changes: [
            { type: 'fix', text: '修复财政审计基线漂移：Worker 异步计算期间 stateRef 被 React 重渲染更新，导致银币审计起点偏移产生虚假残差。改为在同步区预捕获起始银币作为基线。' },
            { type: 'fix', text: '修复资源快照竞态：adjustedResources 对象在 setResources updater 延迟执行前被战斗补给扣除等后续代码修改，导致资源写回不正确。改为提前创建快照。' },
            { type: 'fix', text: '修复审计残差计算基线不一致：entryTotal 以 auditStartingSilver 为基线，而差值以 prev.silver 为基线，存在 pending delta 时两者偏移产生虚假残差。统一使用 auditStartingSilver 并扣除延迟操作增量。' },
            { type: 'fix', text: '修复军人人头税课税基数为零：军饷在人头税之后才发放导致 actualPerCapitaWage=0、军人阶层免税。回退使用上一 tick 工资信号作为课税基数。' },
            { type: 'fix', text: '修复税率面板切换标签页丢失设置：PoliticsTab 和 StratumDetailSheet 中正在编辑的税率 draft 在组件卸载时自动提交，不再因切换页签而丢失。' },
            { type: 'fix', text: '修复人头税补贴判定遗漏 JavaScript 负零（-0）的情况，补贴模式切换更可靠。' },
            { type: 'fix', text: '修复供需分析面板未显示事件全局产出修正（buildingProductionMod: all），补充对 all 键的读取和「事件全局」标签展示。' },
            { type: 'improve', text: '移除 Ledger 银币 ±1e15 硬上限和财富 1e12 硬上限，改为仅过滤 NaN/Infinity/负数，高阶经济体长期运行不再因数值溢出被截断。' },
            { type: 'improve', text: '补全 stratumConsumption 缓存：非 full-tick 模式下阶层消费数据不再丢失，供需面板数据完整性提升。' },
        ],
    },
    {
        version: '2.3.23',
        date: '2026-03-31',
        isLatest: false,
        highlights: [
            '修复战线推进到敌方领地时己方建筑仍被摧毁的严重 bug',
            '阶层收入面板补贴显示修正，人头税补贴不再重复计入',
            '朝贡上限改为亚线性缩放，大附庸不再暴利失控',
        ],
        changes: [
            { type: 'fix', text: '修复战线区域归属标记（FRONT_ZONES.ownerSide）与实际领土完全反转的严重 bug。根因是 0-50 区间被标记为守方领土、50-100 为攻方领土，但游戏逻辑中 linePosition 增加代表攻方推进、>50 即进入守方领地。导致：(1) 攻方推进后生成的资源节点来自自己的建筑而非敌方；(2) 摩擦战掠劫方向反转，AI 在玩家优势局掠劫玩家节点并摧毁玩家建筑。修复后前线领土归属与所有游戏逻辑一致。' },
            { type: 'fix', text: '修复阶层收入面板中官员阶层补贴（subsidy）显示为 0 的问题，正确读取 classFinancialData 中的补贴记录。' },
            { type: 'fix', text: '修复阶层收入总计中人头税补贴（headTaxSubsidy）与普通补贴（subsidy）重复计算。income.subsidy 已包含人头税补贴，不再单独累加；收入明细拆分为"人头税补贴"和"政府补贴"两行分别展示。' },
            { type: 'balance', text: '朝贡硬上限从固定 10 万改为基于附庸 GDP 的亚线性缩放（平方根）。大经济体附庸的朝贡上限会随 GDP 增长，但增速始终低于线性，避免超大附庸一次朝贡即暴富。' },
        ],
    },
    {
        version: '2.3.22',
        date: '2026-03-31',
        isLatest: false,
        highlights: [
            '修复解散部队必定卡死闪退的严重 bug',
            '财政审计诊断增强：自动定位银币收支差异来源',
        ],
        changes: [
            { type: 'fix', text: '修复批量解散部队（x10/x100/x1000）时游戏卡死闪退。根因是 for 循环逐个调用 disbandUnit，每次触发 setArmy + addLog 状态更新，最多排队 2000-3000 次 React 状态更新导致主线程阻塞。改为 disbandUnit 支持 count 参数，单次调用完成全部解散。' },
            { type: 'fix', text: '修复关税补贴审计条目在已存在普通补贴条目时重复计入，导致财政审计差异报警。' },
            { type: 'fix', text: '修复 simulation 内 startingSilver 基线在贸易路线修改 res.silver 之后才捕获，导致审计起点偏移、差异虚报。改为在 spread copy 后立即记录。' },
            { type: 'improve', text: '财政审计诊断增强：simulation 内新增 10 个阶段检查点（生产、税收、军费、消费、官员、市场等），差异 >0.1 时自动输出阶段级告警，快速定位银币泄漏源。' },
            { type: 'improve', text: 'gameLoop 审计诊断细化：不一致时拆分 sim 内部差异与 gameLoop 层差异，并输出 silverAtSpread/silverAfterTradeRoute 等关键快照，便于排查。' },
        ],
    },
    {
        version: '2.3.21',
        date: '2026-03-31',
        isLatest: false,
        highlights: [
            '内存持续增长全面治理：消除 6 类泄漏源，长时间游戏不再卡顿',
            '新增崩溃上报系统：闪退、OOM 等异常自动记录并上报',
            '修复腐败收入双重扣款导致的国库异常',
        ],
        changes: [
            { type: 'improve', text: '禁用零消费者的 Zustand store 同步（useStoreSync），每次渲染减少 90+ 字段对象创建与完整 gameState 深比较开销。' },
            { type: 'improve', text: '游戏循环中 6 处动态 import() 改为静态 import，消除每 tick 的 Promise 创建、微任务调度与闭包累积。' },
            { type: 'improve', text: 'stateRef 改为 Object.assign 就地更新，避免依赖变化时重建 90+ 字段新对象。' },
            { type: 'improve', text: 'IndexedDB 存档连接单例化，避免每次存档操作重复打开连接导致资源泄漏。' },
            { type: 'improve', text: '移除无 UI 消费者的 resourceChangeLog 与 classWealthChangeLog 审计日志，减少每 tick 数十个临时对象分配。' },
            { type: 'improve', text: 'treasuryChangeLog 改为批量写入，多条日志合并为单次 setState 调用。' },
            { type: 'improve', text: 'nations 清理增强：每 100 tick 同步清除已亡国家的外交关系、海外投资、活跃前线等关联数据，防止数组无限膨胀。' },
            { type: 'improve', text: 'priceHistory 最大长度从 365 降至 90 天，数组更新改为单次分配，减少每 tick 内存创建量。' },
            { type: 'improve', text: 'window 全局调试变量（__PERF_STATS、__APPLY_SECTIONS）仅在 __PERF_LOG 开启时写入，正常游戏零开销。' },
            { type: 'new', text: '新增崩溃上报系统（crashReporter）：自动捕获 JS 错误与未处理 Promise 拒绝，通过 GA + 自研后端上报。' },
            { type: 'new', text: '新增 AppErrorBoundary：React 渲染崩溃时展示友好错误页面并上报，不再白屏。' },
            { type: 'new', text: '应用启动时自动检测上次会话是否异常退出（OOM/强杀），并在 analytics 初始化后上报崩溃日志。' },
            { type: 'fix', text: '修复 Ledger._deduct 未返回实际扣除金额，导致余额不足时记账金额与实际扣款不一致。' },
            { type: 'fix', text: '修复腐败收入处理中 applySilverChange 与 ledger.transfer 双重扣除国库，改为仅通过 ledger.transfer 执行一次扣除+记账。' },
            { type: 'fix', text: '修复动态 import 改静态后投资代码引用未初始化变量 adjustedMarket 导致 ReferenceError。' },
        ],
    },
    {
        version: '2.3.20',
        date: '2026-03-31',
        isLatest: false,
        highlights: [
            '修复玩家中途闪退：消除贸易清理与成就系统引发的 React 无限渲染循环',
            '高速模式 UI 不再卡顿：数据展示与逻辑同步更新，告别延迟感',
            '防御性容错：.map 未定义、解构崩溃等边界场景加固',
        ],
        changes: [
            { type: 'fix', text: '修复贸易路线清理 effect 导致 React #185 (Maximum update depth exceeded) 闪退。根因是 useEffect 依赖了自己写入的 tradeRoutes/merchantState state，国家吞并时触发清理→setState→重跑 effect→无限循环。改为通过 ref 读取最新值，effect 仅依赖 nations 变化。' },
            { type: 'fix', text: '修复成就解锁时嵌套 setState 引发额外渲染风暴。此前 setAchievementNotifications 被放在 setUnlockedAchievements 的 updater 内部调用，React 批处理期间的嵌套 setState 导致不可预测的重渲染。改为 queueMicrotask 延迟通知更新。' },
            { type: 'fix', text: '修复 incrementAchievementProgress 每次调用都创建新 state 对象。当 amount=0 或值无变化时现在直接返回旧引用，避免触发不必要的重渲染。' },
            { type: 'fix', text: '修复成就函数（unlockAchievement / incrementAchievementProgress / dismissAchievementNotification）每次渲染创建新引用，导致依赖它们的 useEffect 无限重触发。已包裹 useCallback 稳定引用。' },
            { type: 'fix', text: '修复经济指标变量 indicators 在高速模式下 ReferenceError：原 const 声明位于 if (_shouldUpdateUI) 块内，高速 tick 跳过该块后后续代码引用未定义变量。已提升 let 声明到块外。' },
            { type: 'fix', text: '新增防御性保护：WikiModal 中 .map 调用前检查数组存在、IdeologyCard/IdeologyTab 中解构前添加空值兜底、useGameActions 中阵列操作容错。' },
            { type: 'improve', text: '高速模式 UI 更新频率从每 5 tick 一次提升至每 tick 同步更新。由于组件每 tick 已因 15+ 个非降频 setState 而重渲染，额外 setState 通过 React 批处理合并，实际渲染开销几乎不变，但数据展示延迟从最多 4 tick 降至 0。' },
        ],
    },
    {
        version: '2.3.19',
        date: '2026-03-31',
        isLatest: false,
        highlights: [
            '5 倍速挂机闪退深度修复：UI 渲染降至 ~1 次/秒，内存分配大幅减少',
            '补贴建筑不再误停产：补贴收入正确计入边际收益判定',
            '人头税负税率（补贴）计算修正',
        ],
        changes: [
            { type: 'improve', text: '高速模式（≥3x）UI 深度降频：每 5 tick 才执行一次完整 UI 更新（popStructure、rates、classInfluence、jobFill 等 20+ 项展示数据），中间 tick 仅更新模拟关键状态（resources、buildings、nations、market 等）。React 渲染频率从 5 次/秒降至 ~1 次/秒。' },
            { type: 'improve', text: '经济指标计算降频：calculateAllIndicators、updatePriceHistory、calculateEquilibriumPrices 在高速模式下仅每 5 tick 执行一次，消除最大的单次 CPU + 内存开销。' },
            { type: 'improve', text: '高速模式 nations 零拷贝：主线程模拟时 simulationParams.nations 直接引用原数组，跳过每 tick 全表 .map() + spread 产生的 GC 压力。' },
            { type: 'fix', text: '修复 eventHistory 和 battleNotifications 运行时无上限增长：长时间游戏中事件历史可无限累积，现加入运行时硬上限（eventHistory 200 条、battleNotifications 20 条）。' },
            { type: 'fix', text: '修复受补贴建筑误停产：此前补贴收入未计入边际收益判定，导致即使政府给予高额补贴，建筑仍因"市场价亏损"而停产。现将补贴视为保底收入纳入有效收益计算。' },
            { type: 'fix', text: '修复人头税负税率场景下税后工资计算错误：此前 Math.max(0, taxCost) 在补贴场景下将负税成本截断为 0，导致补贴未实际增加工人净收入。' },
        ],
    },
    {
        version: '2.3.18',
        date: '2026-03-31',
        isLatest: false,
        highlights: [
            '营业税所见即所得：输入50就是50%税率，输入-500就是每栋补贴500🪙',
            '移除补贴金额上限，玩家可自由设定任意补贴额度',
            '建筑/阶层详情面板：修改税率后右侧即时同步显示',
        ],
        changes: [
            { type: 'improve', text: '营业税系统彻底重构为所见即所得（WYSIWYG）：移除 0.03 基准税率的间接换算层，正值直接存储实际税率（输入50即50%），负值直接存储每栋补贴金额（输入-500即补贴500🪙/栋），从 UI 输入到存储到模拟计算全链路一致。' },
            { type: 'improve', text: '移除营业税补贴方向的上限限制：此前补贴被 MAX_BUSINESS_TAX 间接卡死在375🪙/栋，现在补贴金额不设上限，征税方向仍保留1000%上限。' },
            { type: 'fix', text: '修复建筑详情面板营业税补贴显示不同步：修改左侧补贴金额后右侧立刻显示对应设定值，不再依赖下一模拟 tick 的滞后数据。' },
            { type: 'fix', text: '修复阶层详情面板人头税补贴显示不同步：同上，补贴模式下右侧直接显示当前设定值。' },
            { type: 'fix', text: '修复建筑详情面板营业税无法输入小数：此前输入 2. 时小数点被 Number 解析吞掉，导致无法继续输入到 2.5。改为保留原始输入字符串，仅在提交时做数值转换。' },
        ],
    },
    {
        version: '2.3.17',
        date: '2026-03-31',
        isLatest: false,
        highlights: [
            '修复宣战后军事界面空白的竞态 bug',
            '高倍速（≥3x）自动切换主线程模拟，根治移动端 OOM 闪退',
            'Worker 传输动态降频，进一步降低内存分配压力',
        ],
        changes: [
            { type: 'fix', text: '修复宣战确认后跳转军事界面显示空白的 bug。根因是游戏循环用直接赋值（setActiveFronts(simResult)）覆盖了用户在 tick 运行期间创建的新战线/会战，改为函数式合并更新后新建的战线不再被吞掉。' },
            { type: 'improve', text: '游戏速度 ≥3x 时自动禁用 Web Worker，改为主线程直接执行模拟。彻底消除 postMessage 结构化克隆带来的内存开销（5x 速度下从 300-900MB/分钟降至接近零），以少量 UI 卡顿换取内存安全，根治高倍速挂机闪退。' },
            { type: 'improve', text: 'Worker 输出数据按游戏速度动态降频：大型 UI 面板数据（财务明细、支持度分解、市场 breakdown）改为每 10×gameSpeed tick 传输一次，其余 tick 设为 null 并由主线程使用缓存值，1-2x 速度下也显著降低内存分配。' },
            { type: 'improve', text: '条件化 setState：approvalBreakdown、classFinancialData、buildingFinancialData 仅在 Worker 传回有效数据时更新 React state，避免空值覆盖导致面板闪烁。' },
        ],
    },
    {
        version: '2.3.16',
        date: '2026-03-31',
        isLatest: false,
        highlights: [
            '移除资源库存自然衰减机制，囤积资源不再无故损耗',
        ],
        changes: [
            { type: 'remove', text: '移除资源库存超量衰减机制：此前当库存超过需求×目标天数×3 时，超出部分每 tick 自动衰减 2%（以"变质、失窃"为由）。该机制导致玩家精心囤积的资源莫名减少，现已完全移除。易挥发资源（电力）的溢出清零不受影响。' },
        ],
    },
    {
        version: '2.3.15',
        date: '2026-03-31',
        isLatest: false,
        highlights: [
            '移动端闪退修复：大幅削减每 tick 内存分配，缓解长时间运行后 OOM 崩溃',
            '调试数据按需生成：非开发模式不再创建大量冗余对象',
            '财务面板更新降频：减少 React state 更新频率，降低 GC 压力',
        ],
        changes: [
            { type: 'fix', text: '修复移动端运行约 10 分钟后渐进式卡死直至被系统强杀的问题。根因是每 tick 无条件创建大量调试对象（buildingDebugData、silverChangeLog、classWealthChangeLog、militaryDebug、freeMarketDebug 等），在手机 WebView 有限堆内存下 GC 追不上分配速度导致 OOM。' },
            { type: 'improve', text: 'simulation.js 中所有调试数据（buildingDebugData、classWealthChangeLog、resourceChangeLog、militaryDebug、freeMarketDebug）改为仅在 isDebugEnabled("simulation") 时生成，正常游戏时为 null/no-op，每 tick 节省约 50-200KB 对象分配。' },
            { type: 'improve', text: 'silverChangeLog 从 _debug 块提取为独立的 _auditLog 字段（财政审计仍可用），其余 _debug 数据仅 debug 模式下返回。' },
            { type: 'improve', text: 'buildingFinancialData 和 classFinancialData 的 React state 更新从每 tick 降频到每 10 tick，大幅减少 React 渲染和 GC 压力，UI 感知几乎无影响。' },
            { type: 'improve', text: 'window.__buildingDebugData 不再每 tick 强制覆盖空对象，仅在有数据时挂载，消除全局对象泄漏。' },
            { type: 'improve', text: 'supplyBreakdown 历史保留量从 30 条缩减至 10 条（每条含全资源×全建筑的完整 breakdown），节省约 20-60KB 内存。' },
            { type: 'improve', text: '理念系统指标历史深度从 90 缩减至 30（METRIC_HISTORY_LIMIT），均值窗口从 30 缩至 15，减少长期驻留内存。' },
            { type: 'improve', text: 'EconomyLedger 的 classWealthChangeLog 追踪增加 null 保护，非调试模式下不产生任何对象分配。' },
            { type: 'improve', text: '建筑生产循环中的 ownerDetails 数组改为按需创建（仅 debug 时收集），正常游戏时跳过该分配。' },
        ],
    },
    {
        version: '2.3.14',
        date: '2026-03-31',
        isLatest: false,
        highlights: [
            '粮荒死循环终结：缺粮缺布时价格加速暴涨，劳动力自动转向种地',
            '税制大幅减负：人头税基准 10%→5%，营业税基准 8%→3%',
            '建筑利润不足时显示完整成本分析明细',
            '崩溃日志持久化 + 内存监控，闪退后可回溯原因',
        ],
        changes: [
            { type: 'fix', text: '生存物资（粮食/布料）极度短缺时，价格压制权重从固定 0.4 逐步提升至 1.0（库存低于 30% 目标时线性解除），让粮价如实反映稀缺程度，打破"商人进口压价→无人转职种地→持续饿死人"的恶性循环。' },
            { type: 'fix', text: '接线生存转职逻辑：当食物/布料供需比低于 0.5 时，向生产该资源的角色转职阻力降至原来的 30%（门槛从 ~2x 降至 ~0.6x），迁移速率提升 5 倍，且忽略冷却期限制。' },
            { type: 'fix', text: '修复消费短缺记录缺少 isBasic 标记的 bug：此前粮食/布料短缺被错误归类为"奢侈品短缺"（仅扣 3 点审批），现在正确触发基本需求短缺的严厉惩罚（审批上限封顶 0 或 30）。' },
            { type: 'fix', text: '智能工资预估在生存资源紧缺时也对农民等生产者启用实时计算（此前仅在人口≤20时），确保高粮价下农业空岗在招工排序中靠前。' },
            { type: 'balance', text: '人头税基准比例从 10% 降至 5%，减轻低收入阶层税负压力；所有引用点的 fallback 值同步更新。' },
            { type: 'balance', text: '营业税基准比例从 8% 降至 3%，缓解高税负扼杀产业利润的问题；所有引用点的 fallback 值同步更新。' },
            { type: 'balance', text: '成本价计算中营业税贡献上限为非税成本的 30%，打断"高税→高价→更高税"的正反馈螺旋。' },
            { type: 'balance', text: '边际收益计算移除营业税项（视为利润分配而非生产成本），避免营业税误导建筑停产决策。' },
            { type: 'fix', text: '人头税上限不超过生活成本的 50%，防止极端税率下阶层因税致贫。' },
            { type: 'fix', text: '承诺任务、组织度系统、审批模块的税负计算统一使用收入比例公式，与主模拟保持一致。' },
            { type: 'improve', text: '建筑利润不足时显示详细分析面板：营收、原料成本、工资支出、营业税、每栋预计盈亏一目了然。' },
            { type: 'improve', text: '全局错误收集器升级：崩溃日志持久化到 localStorage（最多 50 条），闪退重启后弹窗展示；新增每 30 秒内存采样监控，辅助定位内存泄漏。' },
            { type: 'fix', text: '建筑财务数据补全 ownerRevenue 和 businessTaxPaid 实时跟踪，修复利润面板数据缺失。' },
        ],
    },
    {
        version: '2.3.13',
        date: '2026-03-31',
        isLatest: false,
        highlights: [
            'APP 启动时自动清理旧版本 OTA 缓存，防止存储空间膨胀',
        ],
        changes: [
            { type: 'improve', text: '新增 OTA 旧 bundle 自动清理：每次启动后识别当前使用的 bundle，删除所有非当前版本的旧包（每个约 29MB），频繁更新不再导致缓存持续增长。' },
            { type: 'improve', text: 'Capacitor 配置补充 autoDeleteFailed 和 autoDeletePrevious，双重保障原生层也主动清理失败和过期的 bundle。' },
        ],
    },
    {
        version: '2.3.12',
        date: '2026-03-31',
        isLatest: false,
        highlights: [
            '移除资源数值硬上限（1000兆），资源积累不再被人为封顶',
        ],
        changes: [
            { type: 'fix', text: '移除 simulation 中 SAFE_VALUE_CAP (1e15) 对资源总量的硬性钳制。此前资源通过 applyResourceChange 路径变动时，单次增量和累计总量均被限制在 ±1e15（1000兆），后期高产能经济体资源会卡在上限无法增长。现在仅保留 NaN/Infinity 防护，不再设置数值天花板。' },
        ],
    },
    {
        version: '2.3.11',
        date: '2026-03-31',
        isLatest: false,
        highlights: [
            '营业税补贴改为每栋固定金额，告别"按比例补贴越亏越补"的怪圈',
            '修复营业税正税金额翻倍 bug 与多个事件效果崩溃',
            '教程系统与日志回调引用稳定化，彻底消除 React 无限渲染',
        ],
        changes: [
            { type: 'fix', text: '营业税正税路径 businessTaxPaid 被 ledger 自动记录后又手动累加一次，导致正税金额翻倍入账。移除重复累加。' },
            { type: 'fix', text: '事件选项非数组时 filterEventOptions 返回原值导致 EventDetail .map() 崩溃，兜底改为返回空数组。' },
            { type: 'fix', text: '事件效果写入 setActiveEventEffects 时，approval/stability/resourceDemand/stratumDemand/buildingProduction 五个字段统一加 Array.isArray 防护，防止旧存档中对象格式数据触发 spread 异常。' },
            { type: 'fix', text: '策略行动的 approvalChanges 写入格式从对象嵌套改为数组追加，与新的 activeEventEffects.approval 结构保持一致。' },
            { type: 'fix', text: 'addLog 回调因依赖 gameState 每帧重建，通过 useRef 持有 setLogs 让引用完全稳定，消除下游 useEffect 不必要重跑。' },
            { type: 'fix', text: '教程系统 useTutorialSystem 将 gameState 整体从依赖数组移除，改用 gameStateRef + 具体原始值字段，修复 React #185 无限渲染循环。' },
            { type: 'improve', text: '营业税 UI 根据正负值自适应显示"税率(%)"或"补贴(🪙/栋)"，标签、占位符、说明文案全部联动，玩家一眼看清当前模式。' },
            { type: 'balance', text: '营业税补贴模式从按营收比例改为每栋固定金额：负数值直接表示每栋每次产出补贴的金币数，计算更直观、补贴总额可预测。' },
            { type: 'balance', text: '营业税正税征收改用实际产出（actualMultiplier）替代人员配比估算（staffingRatio），使税额与真实产值精确挂钩。' },
        ],
    },
    {
        version: '2.3.10',
        date: '2026-03-30',
        isLatest: false,
        highlights: [
            '修复人头税按岗位工资而非人均收入征收的严重计算错误——设 20% 税率实际可能收超过 100% 收入',
        ],
        changes: [
            { type: 'fix', text: '人头税征收从"按岗位工资信号"改为"按当期每人实际工资收入"计算。旧逻辑使用 market.wages（每个岗位的日薪），在就业率低于 100% 时远高于人均收入，导致设定 20% 的税率实际税额可超过人均收入的 100%。' },
            { type: 'fix', text: '官员人头税同步修正：使用官员本 tick 实际到手薪俸作为税基，而非全局工资信号。' },
            { type: 'fix', text: '不满度分析（demands）和组织度系统（organizationSystem）的头税估算同步修正，使用实际人均收入而非岗位工资信号，确保税负评估与实际征收一致。' },
            { type: 'fix', text: '建筑详情营业税"实际税额"始终显示 0：buildingFinancialData.businessTaxPaid 从未被写入，现在在征税和补贴时正确记录实际金额。' },
        ],
    },
    {
        version: '2.3.9',
        date: '2026-03-30',
        isLatest: false,
        highlights: [
            '紧急修复 Worker 崩溃（window is not defined），恢复 95%+ 玩家的游戏线程',
            '修复无限渲染循环（React #185）和多个运行时空指针错误',
        ],
        changes: [
            { type: 'fix', text: 'Web Worker 崩溃修复：gameanalytics SDK 在模块初始化时访问 window 导致 Worker 环境 100% 崩溃，通过注入兼容垫片（workerGlobals）在 SDK 加载前创建最小化 window 代理。影响约 400+ 玩家的 1449 次报错。' },
            { type: 'fix', text: '修复 React Error #185 无限渲染循环：useGameActions 每次渲染返回新对象引用导致依赖它的 useEffect 反复触发，改为 useRef 保持稳定对象引用。影响 152 玩家。' },
            { type: 'fix', text: '修复事件选项 undefined.map 崩溃：filterEventOptions 在 options 非数组时返回原值而非空数组，导致 EventDetail 组件 .map() 时崩溃。' },
            { type: 'fix', text: '修复 result.logs / nextOfficials 等多处空指针：添加 Array.isArray 防护，防止 Worker 返回数据缺失时触发 "is not iterable" 和 "map is not a function" 错误。' },
        ],
    },
    {
        version: '2.3.8',
        date: '2026-03-30',
        isLatest: false,
        highlights: [
            '人头税征税上限 1000%、营业税范围 ±1000%，杜绝极端税率导致的经济崩盘',
            '旧存档迁移改为按实际收入反算税率，迁移后税额与旧版一致',
        ],
        changes: [
            { type: 'fix', text: '旧存档迁移不再暴力钳制——改为用存档中的阶层工资反算旧税额占收入的比例，再换算为新税率，迁移后玩家实际税收与旧版基本一致。' },
            { type: 'balance', text: '人头税征税模式上限从无限制收紧至 1000%（UI 输入超出自动钳制），避免玩家设置天文数字税率导致经济系统崩溃。' },
            { type: 'balance', text: '营业税范围从 ±80 万% 收紧至 ±1000%，建筑详情面板的范围提示同步更新。' },
        ],
    },
    {
        version: '2.3.7',
        date: '2026-03-30',
        isLatest: false,
        highlights: [
            '人头税改为收入百分比制，补贴改为银币绝对值制，税收/补贴完全分离',
            '修复人头税在工资发放前就收取导致只能从剩余存款扣税的重大时序缺陷',
            '旧存档安全迁移：高额旧乘数自动降至 10% 安全税率，避免经济崩盘',
        ],
        changes: [
            { type: 'fix', text: '人头税收取时序从 preProduction 移到 productionLoop 之后——现在先发工资再收税，税收可以从"收入 + 存款"中扣除，而非只能从上一轮剩余存款中收取。' },
            { type: 'fix', text: '旧存档加载时，正值乘数超过 1.0（对应 >10% 收入税）的自动钳制到 10%，负值乘数转为绝对银币补贴，防止旧存档经济崩盘。使用 _headTaxVersion 标记避免重复迁移。' },
            { type: 'improve', text: '人头税 UI 重构：税收模式用百分比输入（如 20%），补贴模式用银币绝对值输入（如 0.50 银币/人/日），两种模式用"税/补"按钮一键切换。' },
            { type: 'improve', text: '阶层详情和政治面板的税率卡片同步更新——补贴模式显示"补贴 X.XX ₴/人/日"而非令人困惑的负百分比。' },
            { type: 'improve', text: '财务明细新增"人头税补贴"收入行，总收入计算也纳入该项，不再遗漏补贴对净收入的贡献。' },
            { type: 'balance', text: '收入为零的阶层不再被征收人头税（旧逻辑会按微小的 headTaxBase 兜底征收），生活成本计算同步修正。' },
            { type: 'balance', text: '组织度系统补上缺失的 effectiveTaxModifier 传参，税负评估与实际征收完全一致，不再出现"税率看着低但民众很不满"的偏差。' },
        ],
    },
    {
        version: '2.3.6',
        date: '2026-03-30',
        isLatest: false,
        highlights: [
            '修复人头税补贴金额在阶层详情中显示为 0 的问题',
            '修复升级时代界面成本不含人口规模系数的问题',
        ],
        changes: [
            { type: 'fix', text: '阶层详情面板的补贴金额不再显示 0.000——新增 headTaxSubsidy 数据追踪，UI 在补贴模式下正确读取实际发放金额。' },
            { type: 'fix', text: '时代升级成本 UI 现已同步人口规模缩放系数，显示的成本与实际检查完全一致，不再出现"条件全绿却无法升级"的困惑。' },
        ],
    },
    {
        version: '2.3.5',
        date: '2026-03-30',
        isLatest: false,
        changes: [],
    },
    {
        version: '2.3.4',
        date: '2026-03-30',
        isLatest: false,
        highlights: [
            '税制改革：营业税按营收比例、人头税按收入比例，UI 所见即所得',
            '理念联动可视化：选理念时直接看到搭配对象与机制效果',
            '时代升级成本随国家规模缩放，中后期不再一键秒升',
            '附庸战争分数对数增长并封顶 2500，不再天文数字',
        ],
        changes: [
            { type: 'fix', text: '修复全局错误处理器在 error 对象为 null 时无法记录诊断信息的问题，现在会记录 message、filename、lineno。' },
            { type: 'improve', text: '理念卡片在候选模式下显示联动搭配方名称，联动/冲突条展示描述文案与机制效果标签（自动建造、资源回声等），选理念时不再盲选。' },
            { type: 'improve', text: '营业税与人头税 UI 改为所见即所得：左侧直接输入百分比税率，右侧显示实际征收银币数额，告别抽象的"倍率系数"。' },
            { type: 'improve', text: '游戏百科与新手教程同步更新税制说明，新玩家不会看到过时的固定税额描述。' },
            { type: 'balance', text: '营业税改为按建筑营收比例征收（基准 8%），人头税改为按阶层日均收入比例征收（基准 10%），取代旧的固定数额制，税负更公平。' },
            { type: 'balance', text: '时代升级成本引入人口规模系数（对数缩放），国家越大升级越贵，中后期尤其官员出场后不再轻松秒升。' },
            { type: 'balance', text: '古典时代升级移除文化 250 需求——青铜时代缺乏自然文化来源，不再卡玩家进度。' },
            { type: 'balance', text: '附庸化所需战争分数改为对数递增并封顶 2500，3 个附庸后不再线性 +400 导致分数暴涨至万分。' },
            { type: 'balance', text: '官员私产上限设为 3 + 当前时代数，且现有建筑岗位填充率低于 85% 时不再投资新建筑，遏制官员囤积空置产业。' },
            { type: 'new', text: '新增青铜时代文化建筑"长者祭坛"与科技"口述传统"（每人每日 +0.001 文化），为进入古典后积累文化打下基础。' },
        ],
    },
    {
        version: '2.3.3',
        date: '2026-03-30',
        isLatest: false,
        highlights: [
            '战斗系统全面重写：兰彻斯特杀伤模型，碾压局秒杀、精锐兵种质量优势真实体现',
            '饥荒自然抑制人口增长，饿死上限防止一波清零',
            '总览页新增"迈向下一时代"进度条，升级条件一目了然',
            '回归玩家欢迎横幅、新事件、底层阶层叛乱频率下调',
        ],
        changes: [
            { type: 'fix', text: '战斗系统从百分比伤亡模型重写为兰彻斯特线性杀伤模型：伤亡 = 敌方总火力 × 强度 / 我方单位防御值，碾压局（如1000人打3人）可在1天内结束，不再出现无限僵持。' },
            { type: 'fix', text: '前线摩擦战也改用兰彻斯特模型计算伤亡，移除旧的 Math.max(1) 保底逻辑，小股敌军不再每天必杀1人。' },
            { type: 'fix', text: '分析后端难度字段不再在初始化时发送默认值，改为延迟 2 秒等存档加载完毕后上报，避免统计数据失真。' },
            { type: 'fix', text: '更新日志弹窗不再对未完成教程的新玩家自动弹出，减少首次体验干扰。' },
            { type: 'fix', text: '虚拟税收上限改为基于当期税收而非国库余额，堵住国库越多→虚拟税越高→国库更多的指数增长漏洞。' },
            { type: 'fix', text: '商品售价新增成本 50% 底线，防止供过于求时价格无限趋零导致系统性通缩。' },
            { type: 'improve', text: '总览页签新增"迈向下一时代"进度条，实时展示人口、科研、科技三项升级条件的达成情况。' },
            { type: 'improve', text: '新增回归玩家欢迎横幅：离开超过 30 分钟后再回来，自动显示帝国状态摘要。' },
            { type: 'improve', text: 'AI 国家数据传输时裁剪 tradeHistory/priceHistory/resourceHistory 等大数组，降低序列化负载。' },
            { type: 'balance', text: '战斗追击最大损失率从 45% 上调至 60%，歼灭判定阈值从 5% 上调至 8%，胜负更干脆。' },
            { type: 'balance', text: '饥荒生育惩罚：全局粮食满足率低于 70% 时按比例降低出生率（最低降至 10%），人口不再在饥荒中逆势增长。' },
            { type: 'balance', text: '饿死人数每 tick 上限为总人口的 3%，防止单次饥荒直接灭国。' },
            { type: 'balance', text: '过量库存（超过目标 3 倍）每 tick 按 2% 衰减，模拟腐烂/失窃等自然损耗。' },
            { type: 'balance', text: '矿工/自耕农/樵夫的组织度乘数下调（1.2/1.1/1.1→1.0/0.9/0.9），底层阶层叛乱频率回归合理。' },
            { type: 'balance', text: '石器时代科技升级门槛从 80% 降至 55%，新手首次时代跃迁更顺畅。' },
            { type: 'new', text: '新增多个时代事件：大航海时代"航海家的请求/海盗围城/殖民地暴动"、启蒙时代"咖啡馆辩论热"等。' },
        ],
    },
    {
        version: '2.3.2',
        date: '2026-03-30',
        isLatest: false,
        highlights: [
            '修复军团补兵、战斗消失等 15 项重大 bug',
            '建筑升级数据全面校准，43 栋建筑产出回归设计意图',
            '事件效果与选择结果可视化，不再是黑箱',
            '分析上报大幅降频，高速游戏时更流畅',
        ],
        changes: [
            { type: 'fix', text: '修复军团开启自动补兵后不补充的问题：被歼灭军团的缺额现在会正确保留在补兵队列中。' },
            { type: 'fix', text: '修复有官员岗位建筑时官员岗位量显示为 0 的问题：App 层补全了容量的后备计算。' },
            { type: 'fix', text: '修复事件限时效果不再显示的问题：总览页签新增活跃效果区域，展示审批、稳定、资源需求等效果及剩余天数。' },
            { type: 'fix', text: '修复与某国处于战争状态但军事页无交战线的问题：前线重建逻辑移出主战斗块，确保每 tick 一致检查。' },
            { type: 'fix', text: '修复战斗中军队动辄自动消失的问题：歼灭阈值从 8% 下调至 5%，追击最大损失率从 60% 降至 45%。' },
            { type: 'fix', text: '修复官员概览与详情页消耗数值显示正负不一致的问题。' },
            { type: 'fix', text: '修复 useGameLoop 中 formatNumberShortCN 未定义的运行时报错。' },
            { type: 'fix', text: '修复 useGameLoop 大量中文注释和日志因 GBK 双重编码显示为乱码的问题，约 380 处恢复为正确中文。' },
            { type: 'improve', text: '事件选项选择后新增详细反馈：显示具体资源加减数量与概率事件的判定结果。' },
            { type: 'improve', text: '工业生产加成现在在资源供需分析面板中正确体现。' },
            { type: 'improve', text: '建筑升级面板新增批量数量输入框，可一次指定升/降级数量，大规模操作更高效。' },
            { type: 'improve', text: '暂停/开始按钮尺寸增大，移动端横屏缩放比例上调，操作更易点击。' },
            { type: 'improve', text: '高频调试日志（财政/性能/附庸等）改为按标志位输出，正常游戏时控制台不再被刷屏。' },
            { type: 'improve', text: '分析后端上报频率大幅降低：周期采样间隔 30 天→90 天，AI 采样压缩 70%，flush 阈值与心跳间隔分别放宽 4 倍和 2 倍。' },
            { type: 'balance', text: '全面校准 43 栋建筑的升级产出与消耗：因基础值调整后升级表未同步，116 处产出和 144 处消耗被按比例修正，升级收益回归设计意图。' },
            { type: 'balance', text: '修复石器作坊升级后工具产出反而降低的数据倒退（0.975→1.95）。' },
            { type: 'balance', text: 'AI 市场强卖强买新增库存/经济规模上限，防止无限交易。' },
            { type: 'balance', text: '附庸海外公司利润引入人口规模因子，几十人小国不再产生百万级外汇回流。' },
            { type: 'balance', text: '附庸化战争分数门槛从 600 上调至 800，后续附庸递增分也提高，抑制碾压式扩张。' },
            { type: 'balance', text: '银币财政收支新增国有建筑银产出项，财务面板数据更完整。' },
            { type: 'balance', text: '交易税补贴上限封顶 50%，堵住 100% 补贴配合人头税无风险套利的漏洞。' },
        ],
    },
    {
        version: '2.3.1',
        date: '2026-03-28',
        isLatest: false,
        highlights: [
            '修复国库与 GDP 数值溢出导致的经济崩溃',
            '叛乱不再每回合重复触发，起义节奏更合理',
            '新时代过渡期物价平稳过渡，减少通胀冲击',
            '蒸汽时代名称修正，不再显示为工业时代',
        ],
        changes: [
            { type: 'fix', text: '修复银币与 GDP 计算中的数值溢出问题：对资源变化量与国库余额加入安全钳制（±1e15），防止附庸朝贡或虚拟税注入导致天文数字。' },
            { type: 'fix', text: '修复策略行动中 setClassOrganization 未定义的报错：组织度变化现统一通过 setRebellionStates 回写，并同步阶段与相位。' },
            { type: 'fix', text: '修复 useGameLoop 中 setMaxPopBonus 未定义的报错，补全解构。' },
            { type: 'fix', text: '修复叛乱起义事件每 tick 重复触发的问题：改为跨越 100% 阈值时仅触发一次，与酝酿/密谋阶段保持一致。' },
            { type: 'fix', text: '修复非银币资源可能出现负数库存的问题，生产资源库存不再低于 0。' },
            { type: 'balance', text: '缓解封建/探索时代二次通胀：新时代过渡期物价乘数上限从 10 渐进开放，铁矿/钢铁目标库存天数下调，减少新资源解锁时的价格飙升。' },
            { type: 'balance', text: '提高附庸化战争分数门槛至 600 并随附庸数量递增，抑制后期碾压式附庸扩张。' },
            { type: 'balance', text: '优化极端缺货时的价格乘数曲线（峰值 5.0），新增库存极端过剩（>3x）时的折价分支，物价波动更平滑。' },
            { type: 'improve', text: 'Worker 超时改为自适应策略（3s-15s），减少低端设备误判超时；模拟 payload 裁剪已阵亡/零人口国家，降低通信开销。' },
            { type: 'fix', text: '蒸汽时代名称修正：第七时代不再错误显示为"工业时代"。' },
        ],
    },
    {
        version: '2.3.0',
        date: '2026-03-27',
        isLatest: false,
        highlights: [
            '支持热更新，后续版本更新无需重新安装 APK',
            '更新进度实时可见，下载状态一目了然',
            '版本追踪统一，分析数据口径更准确',
        ],
        changes: [
            { type: 'new', text: '新增 OTA 热更新系统：后续游戏内容与修复可直接推送到已安装的 APP，无需重新下载安装包。' },
            { type: 'new', text: '热更新时屏幕底部显示实时状态提示（检查中、下载进度、下载完成），更新过程不再是黑箱。' },
            { type: 'improve', text: '版本号追踪统一使用构建注入，GameAnalytics 与自建后端的版本口径完全一致，消除硬编码回退值。' },
        ],
    },
    {
        version: '2.1.15',
        date: '2026-03-27',
        isLatest: false,
        highlights: [
            '埋点改为核心优先，低价值事件默认降噪',
            '会话上报补齐难度与国家维度，分析口径更稳定',
            '求和被拒新增明确反馈，外交结果更可解释',
            'AI 旧存档低兵力自动回填，战局强度更合理',
        ],
        changes: [
            { type: 'improve', text: '埋点治理升级为“事件组软开关”：默认保留经济/物价/人口等核心平衡数据，UI 与低价值微操事件默认关闭并支持本地快速开关，减少分析噪音、提升可用信号密度。' },
            { type: 'improve', text: '分析链路补齐会话维度：客户端初始化与心跳会持续同步难度/剧本，设计事件新增玩家国家 ID/名称上下文，服务端支持动态列探测与文本体解析，旧库未迁移时也可兼容入库。' },
            { type: 'fix', text: '修复页面关闭阶段会话结束上报易丢失的问题：结束流程新增幂等保护与 beforeunload 触发，优先 keepalive 请求并保留 sendBeacon 兜底，减少 session 时长与结束时间缺失。' },
            { type: 'fix', text: '玩家主动求和被拒时新增专门外交事件反馈：会展示提案类型、接受概率与关系惩罚，避免“只扣关系不解释”的黑箱体验。' },
            { type: 'fix', text: '修复组织度变化写回错位问题：事件效果中的 organizationChange 现在统一回写 rebellionStates，并同步阶段与相位，避免组织度面板与事件结果脱节。' },
            { type: 'balance', text: '下调富裕人口转科研/税收的相关理念系数与上限，并增强 AI 军队在旧存档下的低兵力回填，抑制后期滚雪球同时减少 AI 长期个位数兵力导致的战力失真。' },
        ],
    },
    {
        version: '2.1.14',
        date: '2026-03-26',
        isLatest: false,
        highlights: [
            '新增分析查询手册，常用 SQL 可直接复用',
            '新增命令行查询脚本，临时取数更高效',
            '分析工作流文档化，平衡排查路径更清晰',
        ],
        changes: [
            { type: 'new', text: '新增 `analytics-server/ANALYTICS_GUIDE.md` 数据分析手册：集中整理 sessions、design_events、resource_events、error_events 的字段说明、event_id 全索引与按场景分类的查询模板，便于快速定位玩法平衡与留存问题。' },
            { type: 'new', text: '新增 `analytics-server/scripts/query.cjs` 命令行查询脚本：支持通过 `node scripts/query.cjs \"SQL\"` 直接执行 SQL 并输出 JSON 结果，减少临时写脚本和手工连接数据库的重复操作。' },
            { type: 'improve', text: '新增 `skills/civ-analytics/SKILL.md` 分析技能文档，统一数据分析步骤、查询约束和结果解读流程，提升后续版本排查与调参的一致性。' },
        ],
    },
    {
        version: '2.1.13',
        date: '2026-03-26',
        isLatest: false,
        highlights: [
            '理念富裕人口转化系数回调，后期税收与科研增幅更可控',
            '岗位迁移速度与保底迁移同步优化，劳动力错配恢复更快',
            '建筑页虚拟滚动兼容父容器滚动，长列表浏览更稳定',
            '分析后端版本注入与安卓网络配置补齐，上报链路更稳',
        ],
        changes: [
            { type: 'balance', text: '下调多组理念中 wealthyPop 转化器系数（含税收与科研方向），将原先偏激进的人口转化增益回调一个数量级，缓解中后期富裕人口对财政与科技滚雪球过快的问题。' },
            { type: 'balance', text: '岗位迁移基础比例从 0.25% 提升到 1.2%，并在“来源有人口且目标有空岗”时新增至少迁移 1 人的硬保底，减少岗位长期卡死与劳动力无法流动的情况。' },
            { type: 'fix', text: '修复理念转化器读取人口来源时只识别总人口的问题：当 source 指向具体阶层时，转化逻辑现在优先读取该阶层人口；理念卡面文案同步区分“总人口”与“某阶层人口”。' },
            { type: 'fix', text: '修复建筑面板虚拟滚动在父级容器滚动场景下偶发失效的问题：滚动监听改为 capture 模式捕获文档滚动事件，长列表定位与渲染窗口更稳定。' },
            { type: 'improve', text: '分析后端上报链路改进：客户端会打印后端初始化与网络失败日志，appVersion 改为由构建阶段注入的 __APP_VERSION__，避免硬编码版本造成数据追踪口径漂移。' },
            { type: 'fix', text: '安卓端补齐网络兼容配置：新增 network_security_config 并挂载到 Manifest，WebView 允许混合内容加载，修复自建分析后端在特定网络协议组合下无法上报的问题。' },
        ],
    },
    {
        version: '2.1.12',
        date: '2026-03-26',
        isLatest: false,
        highlights: [
            '新增自建分析后端，事件缓冲批量上报与 sendBeacon 兜底',
            '埋点覆盖率从核心操作扩展到全量玩家行为与经济周期采样',
            '条约有效性判定统一加固，cancelled 状态不再遗漏',
            '建筑面板虚拟滚动 spacer 计算修复无限震荡',
        ],
        changes: [
            { type: 'new', text: '新增自建分析后端（analytics-server）：基于 Express + PostgreSQL 的独立事件收集服务，含会话管理、批量事件入库与常用查询模板；客户端通过 customBackend 适配层缓冲事件，10 秒或 50 条自动 flush，页面关闭时 sendBeacon 兜底，配置 VITE_ANALYTICS_API_URL 即可启用。' },
            { type: 'new', text: '事件埋点新增 60+ 事件类型：覆盖存档导入导出、难度/场景选择、建筑批量升降级、附庸审批/指令、和约接受/拒绝/提议、军事解散全部/取消训练/自动补兵/军饷倍率、税收调整、价格管制、贸易偏好/商人分配/路线模式、事件抉择、手动采集、理念装卸、UI 标签/子标签/速度/暂停/建筑置顶与筛选等，同时新增经济流水、市场价格、人口里程碑、饥荒死亡、稳定度等级变化、经济危机、诉求生命周期、组织度阶段、AI 行为和条约状态的周期采样。' },
            { type: 'improve', text: '所有分析事件同时双写至 GameAnalytics SDK 和自建后端，确保数据冗余；自建后端静默降级——服务不可用时不影响游戏运行。' },
            { type: 'improve', text: '事件追踪模块按类别重组（生命周期/建筑/科技/外交/附庸/和约/军事/政治/税收/贸易/事件/理念/成就/周期指标/经济流水/价格/里程碑/诉求/组织度/AI/条约/UI），结构更清晰、扩展更方便。' },
            { type: 'fix', text: '条约有效性判定统一并加固：提取 isTreatyRecordActive 公共函数，到期日优先于 status 字段判断，新增对 cancelled 状态的过滤；getActiveTreaties 同步修正，避免已取消条约仍生效。' },
            { type: 'fix', text: '建筑面板虚拟滚动的 topSpacer 高度计算不再回补自身高度：修复 spacer 高度变化 → gridTop 变化 → range 变化 → spacer 变化的无限震荡循环。' },
        ],
    },
    {
        version: '2.1.11',
        date: '2026-03-26',
        isLatest: false,
        highlights: [
            '接入 GameAnalytics 全链路埋点与 GDPR 合规开关',
            'AI 求和机制重做：持久战/僵局路径 + 战争分门槛修正',
            '附庸升时代后不再从外交与贸易面板消失',
            '理念涌现新增时代均衡与去重，候选多样性显著提升',
        ],
        changes: [
            { type: 'new', text: '接入 GameAnalytics SDK，覆盖建筑/科技/外交/军事/成就/存档等全部玩家操作与周期经济采样（每 30 游戏日），并在设置面板提供"匿名数据"GDPR 开关，关闭后不再上报任何事件。' },
            { type: 'new', text: '国有企业（代经营制）利润的国库份额现在通过 ledger 正式入账并归入财政明细（state_enterprise_profit），状态栏收入分项可直接看到国企贡献。' },
            { type: 'improve', text: '附庸国在外交、贸易路线和军事面板的可见性不再受时代窗口限制：升时代后玩家的附庸仍可正常管理、建立贸易路线和查看状态。' },
            { type: 'improve', text: '建筑购买数量和军事招募数量持久化到 localStorage：切换建筑或重载页面后数量自动恢复，上限统一为 9999，同时移除了建筑面板中每次渲染重算"最大可买数量"的高开销逻辑。' },
            { type: 'improve', text: '阶层详情的"实际税额"改为乘入完整税收修正系数（含合法性、政策和额外加成），当修正偏离 1.0 时额外显示"基准税额 × 税收修正"的分解说明。' },
            { type: 'improve', text: '理念涌现候选池新增时代均衡权重和同时代去重衰减：数量少的时代获得适度补偿，同一轮已选中某时代的理念后，该时代后续权重自动降低，减少中期时代长期霸占候选位。' },
            { type: 'fix', text: '移除战斗结算时对 nation.warScore 的冗余累加与 ±100 硬限幅：战斗阶段增量已通过 warScoreBreakdown 正确汇总，旧代码会导致战争分被双重计数且无法超过 100。' },
            { type: 'fix', text: 'AI 求和/投降逻辑重做：新增"持久战/僵局"求和路径（战争超 100 天且双方僵持时 AI 也会考虑求和），投降门槛从旧的 25/50/100 调整为 200/400/800 以匹配实际战争分量级，aiDominantOnFront 改为软惩罚而非硬阻断。' },
            { type: 'fix', text: '修复叛乱政权求和时走普通和谈流程导致叛乱态无法正确结束的问题：叛乱国家的求和现在统一走专用收尾逻辑。' },
            { type: 'fix', text: '炼钢厂前置科技修正为"机械工程"（epoch 7），要塞造价移除钢铁依赖改为纯铁+砖，贝塞麦炼钢法描述清理多余的"解锁炼钢厂"字样。' },
            { type: 'balance', text: '附庸朝贡 GDP 比例从 25% 下调至 18%，缓解附庸在发展早期被持续抽血、经济长期无法起飞的问题。' },
            { type: 'balance', text: 'AI 国家基础人口增长率从 0.32% 微调至 0.42%、增长上限从 2.5% 提高至 3.0%，减少中后期 AI"只维持不扩张"的停滞感。' },
            { type: 'balance', text: 'AI 虚拟经济利润外流系数从 18% 下调至 12%，给本地经济留更多再投资空间，间接改善 AI 财富积累与军事投入能力。' },
        ],
    },
    {
        version: '2.1.10',
        date: '2026-03-21',
        isLatest: false,
        highlights: ['年度报告改为按全年口径统计并发放理念奖励', '理念涌现跳过保底增强，高稀有理念更容易出现', '外交战争分计算与资源价格曲线显示进一步修正'],
        changes: [
            { type: 'improve', text: '年度政府工作报告改为按全年累计与全年均值统计关键经济指标：GDP 以年累计展示，CPI/PPI、税收与财政净收入改为年均口径，同时补充历史报告中的对应字段与趋势图标签，报告内容与玩家一整年的经营表现更一致。' },
            { type: 'new', text: '年度报告评分现在会发放理念分奖励：结算时按 S/A/B/C 评级分别奖励理念分，并在新年度开始后自动重置年度累计器，让年度考核与理念成长形成直接联动。' },
            { type: 'improve', text: '理念涌现的跳过机制重做：跳过后会显著提高 uncommon/rare/legendary 权重，并加入最低稀有度保底，连续跳过时下一次更容易刷出高品质理念。' },
            { type: 'improve', text: '理念库界面精简为按品质筛选，移除分类筛选的噪音；同时更新跳过提示文案，更明确说明“更易出现高稀有理念”的收益。' },
            { type: 'fix', text: '修复多处战争分读取旧 front.warScore 字段导致和谈、附庸化与战况判断口径不一致的问题：统一按 warScoreBreakdown 汇总有效战争分，并把附庸化门槛明确提升到 300、吞并门槛统一为 500。' },
            { type: 'fix', text: '修复资源详情价格曲线在小幅波动时被过早四舍五入成台阶线的问题：市场内部价格改为保留完整精度，详情图表与数值显示改用更细粒度格式化，轻微价格变化也能被正确观察。' },
        ],
    },
    {
        version: '2.1.9',
        date: '2026-03-20',
        isLatest: false,
        highlights: ['部长自动扩建改为预算驱动并支持单次连建', '建造与招募支持自定义数量输入', '修复多处显示口径与实时状态不同步问题'],
        changes: [
            { type: 'improve', text: '部长自动扩建策略参数全面配置化：新增预算比例与单次预算上限，单次触发可在预算内连续扩建多座建筑，并按部长与全局冷却协同控制节奏，提升自动扩建的可控性与执行效率。' },
            { type: 'improve', text: '建筑详情与军事面板的数量选择器支持自定义数字输入，替代仅靠固定档位切换，玩家可更精细地控制单次建造与招募规模。' },
            { type: 'fix', text: '修复 simulation 里 classLivingStandard 读取旧缓存导致的状态滞后：主循环现在显式透传并优先使用当前帧生活水平数据，降低事件与评估阶段出现口径不一致的概率。' },
            { type: 'fix', text: '修复国家详情承载率展示与当前人口口径偶发不一致的问题：承载率优先按“当前人口 / 承载上限”实时计算，避免缓存指标短暂延迟造成显示矛盾。' },
            { type: 'fix', text: '修复官员详情中立场满意状态偶发滞后的显示问题：详情面板优先使用 UI 层实时重算结果，无实时值时再回退模拟端缓存值。' },
        ],
    },
    {
        version: '2.1.8',
        date: '2026-03-20',
        isLatest: false,
        highlights: ['修复建筑升级写回竞态覆盖玩家操作', '理念稀有度分布调整为更高常见性'],
        changes: [
            { type: 'fix', text: '修复 tick 期间建筑升级写回的竞态问题：当玩家在同一 tick 内进行升级操作时，simulation 结果不再覆盖当帧玩家变更，避免升级数量被回滚或丢失。' },
            { type: 'improve', text: '新增建筑升级延迟变更合并逻辑：按 tick 基线对比 current 状态，计算并合并升级增量，确保自动升级与玩家手动操作可同时正确落地。' },
            { type: 'balance', text: '调整多项理念卡牌稀有度，将部分 uncommon 下调为 common，提升这些理念在流程中的出现概率与可获得性。' },
        ],
    },
    {
        version: '2.1.7',
        date: '2026-03-20',
        isLatest: false,
        highlights: ['建筑营业税输入加限幅与容错', '工资系统新增双底线并回写全局工资镜像', '事件外交目标过滤修复附庸/同盟误触发开战'],
        changes: [
            { type: 'fix', text: '修复建筑营业税系数输入在无效值、极端值与正负切换时的异常表现：税率输入改为支持中间输入态，并统一按 TAX_LIMITS.MAX_BUSINESS_TAX 限幅。' },
            { type: 'improve', text: '工资支付逻辑改为“雇员生计底线 + 业主保留底线”双底线机制，且按 preparedWagePlans 统一汇总各业主工资责任，降低异常工资波动与业主财富瞬时透支。' },
            { type: 'fix', text: '新增建筑级实际发薪到全局 wages 的镜像回写，修复价格、招工与投资等模块读取工资与真实支付脱节的问题。' },
            { type: 'fix', text: '修复事件外交目标选择会命中玩家附庸/军事同盟成员并触发不合理宣战的问题：事件选择器与 triggerWar/triggerPeace 现在统一排除受玩家保护的国家。' },
            { type: 'fix', text: '修复事件详情中偶发显示英文控制字段（如 exclude）的异常：外交效果徽章仅渲染有效数值目标。' },
            { type: 'improve', text: '建筑详情页补充营业税限幅提示，并优化收入说明文案，明确实际工资受生计底线、业主保留与支付比例共同约束。' },
        ],
    },
    {
        version: '2.1.6',
        date: '2026-03-20',
        isLatest: false,
        highlights: ['部长自动扩建改为分部长冷却', '修复自动补兵在战斗中失效', '修复连续操作导致的建筑/研究扣费异常', '组织度新增低人口限制'],
        changes: [
            { type: 'improve', text: '部长自动扩建系统重构：全局检查冷却缩短为 5 天，同时为农业、工业、商业、市政四位部长分别记录 10 天个人冷却，避免单个部长频繁触发把其他部长的扩建机会一并锁死。旧存档中的单个数字冷却值会自动迁移为新的对象结构。' },
            { type: 'fix', text: '修复自动补兵会跳过战斗中军团的问题：补兵需求统计和目标分配不再因为 corps 处于 in_combat 状态而被直接过滤，前线军团现在也能持续收到补员。' },
            { type: 'fix', text: '修复连续快速执行建造、升级、时代升级、科研和招募时可能读取陈旧 resources/buildings 闭包，导致花费计算异常或重复扣费的问题。关键操作现统一读取并回写最新 ref 状态。' },
            { type: 'fix', text: '修复改革法令面板 taxIncome 标签重复定义导致显示不一致的问题，统一为“税收加成”。' },
            { type: 'balance', text: '组织度系统新增最低叛乱人口门槛：人口低于 10 的阶层无法组织有效叛乱，组织度上限压到 50%；若已触发 uprising，则改为少量人口携带财富外流，而不是生成不合理的小规模叛乱。' },
            { type: 'improve', text: '外交与理念界面体验调整：战争中的国家详情页“求和”按钮改为正确触发 peace 动作；理念卡牌始终显示稀有度标签，装备中的理念也可直接打开详情底部面板。' },
            { type: 'balance', text: '若干显示与数值微调：时代演进面板改为直接读取 EPOCHS 名称，工业时代主题名称调整为“蒸汽时代”；工匠阶层低中富裕度下的工具消费需求小幅下调。' },
        ],
    },
    {
        version: '2.1.5',
        date: '2026-03-18',
        isLatest: false,
        highlights: ['橡胶/塑料/铝重新加入全阶层消费'],
        changes: [
            { type: 'balance', text: '重新加入橡胶（rubber）、塑料（plastics）、铝（aluminum）三种资源的居民直接消费：作为广泛日用品（胶鞋、塑料盆、铝餐具等），全阶层从低富裕度（1.0~2.0）即开始使用，随富裕度增长逐级增加消费量，上层阶层用量显著高于底层' },
        ],
    },
    {
        version: '2.1.4',
        date: '2026-03-18',
        isLatest: false,
        highlights: ['建筑升级岗位大幅扩充', '建筑集约化体系：后期建筑业主占比递减', '建筑升级资源解锁前置检查', '业主自动升级速度大幅提升'],
        changes: [
            { type: 'balance', text: '建筑升级岗位大幅扩充：所有建筑升级后岗位增加 50~80%/级，Lv1 产出 1.75x、Lv2 产出 3.3x，输入同步增长，确保效率比逐级明显增加' },
            { type: 'balance', text: '建筑集约化体系：调整 55 个基础建筑 + 103 个升级配置的岗位比例，业主平均占比从 E0(90%) 到 E9(5%) 严格递减，体现时代发展带来的集约化特性' },
            { type: 'balance', text: '消除零业主岗位：修复 9 个后期建筑（高级铜矿、广播站、铀矿等）缺少业主岗位的问题，每个建筑及其升级均补充 capitalist: 1 业主岗' },
            { type: 'balance', text: '岗位扩充同步缩放输入输出：所有岗位调整的建筑均按比例同步缩放资源输入和产出，缩放因子上限 2.5x，确保单位效率不变' },
            { type: 'improve', text: '建筑升级资源解锁前置检查：如果下一等级需要的输入资源尚未解锁（如高级庄园需要化肥），则禁止升级，玩家手动升级、批量升级、业主自动升级、官员投资升级均受此约束' },
            { type: 'improve', text: '升级面板 UI 增强：未解锁资源的升级按钮自动禁用，显示锁定图标和具体未解锁资源名称' },
            { type: 'improve', text: '业主自动升级速度大幅提升：单次升级概率从 2% 提高到 15%（7.5 倍），每类建筑每 tick 允许升级最多 3 座（原 1 座）' },
        ],
    },
    {
        version: '2.1.3',
        date: '2026-03-18',
        isLatest: false,
        highlights: ['新增香料种植园建筑', '修复吞并失败与联盟惩罚逻辑', '阶层角色分离：业主/雇员互斥', '修正资源消费链', '化肥成为农业建筑必需输入'],
        changes: [
            { type: 'new', text: '新增香料种植园（spice_plantation）建筑及 2 级升级配置，补充 Epoch 5 香料生产来源，完善香料资源链' },
            { type: 'fix', text: '修复吞并判定使用错误的 warScore 数据源导致吞并始终失败的问题：改用 frontWarScore 确保数据一致性' },
            { type: 'fix', text: '修正联盟 approvalCap 惩罚逻辑：惩罚强度现在与国家贫困程度正相关（越穷惩罚越重）；联盟期望面板区分显示不同类型的提示信息' },
            { type: 'improve', text: '阶层角色分离：实施业主/雇员互斥规则，同一阶层不能同时担任建筑的业主和雇员，提升经济模型的逻辑严谨性' },
            { type: 'balance', text: '修正资源消费链：从所有阶层的奢侈需求中移除 synthetic_fiber（化纤）、rubber（橡胶）、plastics（塑料）、aluminum（铝）四种工业中间品的直接消费，这些资源只应通过建筑加工为终端产品后再被民间消费' },
            { type: 'balance', text: '复合材料（composites）消费大幅加强：覆盖面从 12 个阶层扩展到全部 17 个阶层，消费门槛全面降低（上层从 2.5 降至 1.8，中层从 5.0~9.0 降至 4.5~5.0，底层新增 7.0~7.5 档），每个阶层均有 2~4 个梯度消费档位' },
            { type: 'balance', text: '化肥（fertilizer）纳入农业生产链：7 个农业/种植建筑的升级配置添加化肥输入需求（早期建筑 Lv2、工业时代建筑 Lv1 起需要化肥），添加化肥后产出额外提升 15~25%' },
            { type: 'balance', text: '橡胶园（rubber_plantation）作为 E7 建筑，基础等级即需要化肥输入，与化肥厂同时代形成资源依赖链' },
        ],
    },
    {
        version: '2.1.2',
        date: '2026-03-17',
        isLatest: false,
        highlights: ['修复未发现国家的虚空贸易', '修复官员阶层财富显示异常', '理念系统新一轮平衡调整'],
        changes: [
            { type: 'fix', text: '修复与未发现国家产生虚空贸易的问题：贸易机会扫描、商人派驻轮换与缓存执行阶段现在都会过滤 relation 为 null/undefined 的国家，避免对未发现目标创建新贸易路线。' },
            { type: 'fix', text: '修复已发起但尚在运输中的历史贸易在国家未发现后被异常清理的问题：进行中的订单会继续完成，避免已经承诺的货物与资金凭空消失。' },
            { type: 'fix', text: '修复贸易路线弹窗“进行中贸易”数量统计错误：页签计数与列表头部现在改为使用合并后的运输订单数，显示与实际列表保持一致。' },
            { type: 'fix', text: '修复跳过官员模拟时 official 阶层财富被错误清零的问题：系统会从官员个体财富重新汇总，确保阶层财富与 UI 展示正确。' },
            { type: 'fix', text: '修复阶层详情面板在需求明细存在空值时的显示异常：essentialNeeds 与 luxuryNeeds 的成本、数量、价格字段现在统一兜底为 0。' },
            { type: 'balance', text: '理念系统新一轮平衡调整：大幅重做多组理念的基础数值、转换器、条件触发与事件 Buff，整体强化理念之间的成长性、联动性与流派差异。' },
        ],
    },
    {
        version: '2.1.1',
        date: '2026-03-17',
        isLatest: false,
        highlights: ['贸易优化'],
        changes: [
            { type: 'improve', text: '贸易优化' },
        ],
    },
    {
        version: '2.1.0',
        date: '2026-03-17',
        isLatest: false,
        highlights: ['修复军团士兵不计入阶层人口的问题', '修复市场恶性清空资源 bug', '军团卡片新增可展开详情面板', '组织度面板重做', '各难度满意度阈值调整', '税收通过弹性机制自然抑制各阶层需求意愿量'],
        changes: [
            { type: 'fix', text: '修复编入军团的士兵不计入 soldier 阶层岗位需求的问题：军团内单位现在会与散兵一同参与 soldier 岗位计算，确保军人阶层人口数量、满意度、军饷转账等下游数值正确反映实际兵力' },
            { type: 'fix', text: '修复市场商人自动贸易逻辑导致的恶性清空资源 bug：移除了建筑循环内商人以自有资金强制进行以物易物的逻辑，避免市场库存被异常抽空' },
            { type: 'fix', text: '修复外交面板商人状态变更回调参数格式错误，避免商人分配数据被意外覆盖' },
            { type: 'new', text: '战线面板军团卡片新增可展开详情面板：点击军团卡片可展开查看兵种配置（按类别分组）、将领特质与加成、战斗力分项（攻击/防御/士气/将领修正）、日均军需银币折算' },
            { type: 'improve', text: '组织度面板 UI 重做：新增趋势指示（上升/下降/稳定）、组织度变化因素分析（好感度阈值对比、物资短缺驱动）、50% 上限锁定提示，视觉风格统一为古典主题' },
            { type: 'balance', text: '各难度满意度阈值下调：和平 30→25、简单 40→35、普通 50→45、困难 70→60、灾厄 85→75、地狱 90→85，降低阈值使组织度更容易衰减，减少"好感度已高但组织度不降"的体验' },
            { type: 'balance', text: '组织度衰减死区从 +5 缩小到 +3：满意度超过阈值 3 点即开始衰减（原为 5 点），减少安全区宽度，提升组织度响应灵敏度' },
            { type: 'improve', text: '税收需求弹性抑制：交易税现在会通过弹性机制自然压低各阶层对资源的需求意愿量，而非仅靠"买不起"硬截断。抑制强度综合考虑三个维度：资源需求弹性（必需品如粮食几乎不受影响，奢侈品如香料、珍馐受影响显著）、阶层人均存款充裕度（存款越充裕对税收越不敏感，富人不在乎税）、是否为奢侈性需求（luxuryNeeds 中的需求额外放大 1.5 倍敏感度）。综合抑制率上限 50%，与原有 affordable 硬截断协同工作' },
        ],
    },
    {
        version: '2.0.10',
        date: '2026-03-17',
        isLatest: false,
        highlights: ['新增年度报告历史弹窗', '信息时代视觉主题', '政体效果大幅扩展', 'Tick 预算管理与性能优化', '游戏循环重构'],
        changes: [
            { type: 'new', text: '新增年度报告历史弹窗（AnnualReportHistoryModal），支持查看历史年度报告，涵盖经济、人口、军事等多维度数据对比' },
            { type: 'new', text: '新增信息时代（epoch 8）完整视觉主题：配色方案、粒子效果与时代背景图片渲染' },
            { type: 'new', text: '政体效果大幅扩展：新增商业帝国、神权封建王国、科技联盟等多种政体配置，覆盖更多时代与政治路线' },
            { type: 'improve', text: 'Tick 预算管理：新增单帧时间预算机制（150ms 上限），防止模拟计算超时导致界面卡顿' },
            { type: 'improve', text: '节流状态分层优化：背景/装饰元素降低刷新频率，减少不必要的 React 重渲染' },
            { type: 'improve', text: 'Worker 通信优化：主线程与模拟 Worker 间消息传递重构，降低序列化开销' },
            { type: 'improve', text: '游戏循环重构：精简 useGameLoop 主循环逻辑，减少冗余状态同步' },
            { type: 'improve', text: '内阁协同效果优化：调整协同加成逻辑，提升内阁组合的策略深度' },
            { type: 'fix', text: '修复理念涌现系统中涌现条件判断的边界问题，确保理念在正确时机触发' },
            { type: 'fix', text: '修复建筑面板在特定筛选条件下的显示异常' },
            { type: 'balance', text: '进一步微调各难度下的库存目标与经济波动参数，强化难度梯度差异' },
        ],
    },
    {
        version: '2.0.9',
        date: '2026-03-16',
        isLatest: false,
        highlights: ['修复敌方停战提议接受流程', '放缓 AI 时代推进速度', '重做难度库存缓冲与价格波动', '修正营业税补贴导致的负成本价'],
        changes: [
            { type: 'fix', text: '修复接受敌方停战提议时流程未统一走战争结束逻辑的问题，避免停战状态与外交后续处理不一致' },
            { type: 'fix', text: '修复营业税为负值（补贴）时可能出现负成本价的问题，成本价现在保底为 0，避免价格模型被异常拉偏' },
            { type: 'fix', text: '清理雇员工资冷启动推导代码中的注释串行问题，避免影响后续维护与阅读' },
            { type: 'balance', text: '大幅放缓 AI 时代推进：提高各时代科技/文化需求系数，时代升级冷却由 200 提升至 600，科技文化累积速率下调至 0.4' },
            { type: 'balance', text: '重做各难度库存目标倍率：和平/简单模式增加库存缓冲提升稳定性，困难/灾厄/地狱模式降低缓冲以增强价格波动与经营压力' },
            { type: 'improve', text: '建筑利润计算改为统一通过税务模块读取营业税倍率，确保税率被正确限制在合法范围内' },
            { type: 'improve', text: '敌方停战事件按钮文案优化为“婉拒停战”，提升交互语义清晰度' },
        ],
    },
    {
        version: '2.0.8',
        date: '2026-03-16',
        isLatest: false,
        highlights: ['新增建筑/国家收藏置顶功能', '修复外交赠礼费用显示错误', '修复成衣作坊时代配置', '新增港口建筑', '平衡调整'],
        changes: [
            { type: 'new', text: '新增建筑收藏功能：建筑卡片左上角悬停出现 ⭐ 按钮，可收藏常用建筑；建筑面板新增"⭐ 收藏"过滤器，收藏数据持久保存' },
            { type: 'new', text: '新增国家收藏功能：外交国家卡片右上角悬停出现 ⭐ 按钮，可收藏常用国家；国家列表新增"⭐ 收藏"过滤器，收藏的国家自动置顶' },
            { type: 'new', text: '新增港口（harbor）建筑：epoch 1，需要航海术科技，消耗木板产出银币，填补航海术的实际解锁目标' },
            { type: 'fix', text: '修复外交赠礼费用显示与实际花费不一致的问题（UI 显示固定 100 但实际花费更高）' },
            { type: 'fix', text: '修复成衣作坊时代配置错误：从 epoch 1 调整为 epoch 2，前置科技改为高级纺织，与华服解锁时代对齐' },
            { type: 'fix', text: '修正航海术科技描述：解锁港口（而非船坞）；修正海图绘制描述：明确解锁船坞' },
            { type: 'balance', text: '小幅提升教堂基础产出：文化 3.2 → 4.0（+25%），银币 0.67 → 0.8（+20%），强化文化+财政双产出定位' },
            { type: 'balance', text: '大幅降低各理念 taxIncome 数值（约 -50%）：修复后期 income_ideology_virtual_tax 异常偏高的问题' },
            { type: 'balance', text: '同步降低各时代 taxIncome 加成：封建 0.20→0.10，探索 0.50→0.25，电气 0.30→0.15，原子 0.35→0.18，信息 0.40→0.20' },
        ],
    },
    {
        version: '2.0.6',
        date: '2026-03-15',
        isLatest: false,
        highlights: ['更新日志功能上线', '修复密谋事件反复弹出的问题', '修复同一官员反复出现的问题'],
        changes: [
            { type: 'fix', text: '修复密谋/起义事件在玩家未处理时反复弹出的问题（现在有未处理事件时不会触发新的组织度事件）' },
            { type: 'fix', text: '修复同一官员候选人反复出现的问题' },
            { type: 'fix', text: '事件弹出时游戏现在会自动暂停' },
            { type: 'new', text: '新增更新日志功能，方便玩家了解游戏更新内容' },
            { type: 'remove', text: '移除存档的"导出到剪贴板"和"从剪贴板导入"功能（已由文件导入导出替代）' },
        ],
    },
    {
        version: '2.0.5',
        date: '2026-03-15',
        highlights: ['外交系统优化', '理念系统平衡调整'],
        changes: [
            { type: 'new', text: '外交谈判新增更多条约类型' },
            { type: 'balance', text: '调整多项理念数值，修复升级收益倒挂问题' },
            { type: 'fix', text: '修复贸易路线税收计算错误' },
            { type: 'fix', text: '修复官员忠诚度在某些情况下不正确衰减的问题' },
        ],
    },
    {
        version: '2.0.4',
        date: '2026-03-14',
        highlights: ['军团系统上线', '战线管理优化'],
        changes: [
            { type: 'new', text: '新增军团编组系统，支持多军团同时作战' },
            { type: 'new', text: '新增战线管理界面，可为不同战线分配军团' },
            { type: 'new', text: '新增将领系统，将领可为军团提供战斗加成' },
            { type: 'balance', text: '调整军队维护成本计算，加入规模惩罚机制' },
            { type: 'fix', text: '修复战斗结算时部分单位数量计算错误' },
        ],
    },
];
