/**
 * 政令配置
 * 侧重于提供可感知的数值影响，并覆盖系统协同所需的全部政令 ID
 */
export const DECREES = [
  // ======== 经济类 ========
  {
    id: 'market_regulation',
    name: '市场监管',
    desc: '建立常设物价与囤积检查队，压制投机并保障城市供应。',
    category: 'economy',
    unlockEpoch: 1,
    cost: {},
    effects: ['公共服务产出 +8%', '居民需求 -5%'],
    drawbacks: ['每日 -3 银币监管成本'],
    modifiers: {
      categories: { civic: 0.08 },
      needsReduction: 0.05,
      passive: { silver: -3 },
    },
    active: false,
  },
  {
    id: 'guild_charter',
    name: '行会特许',
    desc: '授予老牌行会自治权，保障手艺人供应链与训练。',
    category: 'economy',
    unlockEpoch: 1,
    cost: {},
    effects: ['手工业建筑产出 +15%', '工业总体 +5%'],
    drawbacks: ['每日 -4 银币行会补贴'],
    modifiers: {
      buildings: {
        loom_house: 0.15,
        furniture_workshop: 0.15,
        dye_works: 0.15,
      },
      categories: { industry: 0.05 },
      passive: { silver: -4 },
    },
    active: false,
  },
  {
    id: 'free_trade',
    name: '自由贸易',
    desc: '开放港口与商路，鼓励远洋商人和自由竞争。',
    category: 'economy',
    unlockEpoch: 2,
    cost: {},
    effects: ['市场/港口产出 +20%', '每日 +6 银币贸易顺差'],
    drawbacks: ['工业产出 -5%（进口冲击）'],
    modifiers: {
      buildings: {
        market: 0.15,
        trade_port: 0.25,
        dockyard: 0.15,
      },
      passive: { silver: 6 },
      categories: { industry: -0.05 },
    },
    active: false,
  },
  {
    id: 'trade_protection',
    name: '贸易保护',
    desc: '以关税与配额护卫本土手工业，维持就业。',
    category: 'economy',
    unlockEpoch: 2,
    cost: {},
    effects: ['成品工业产出 +12%', '采集产出 +5%'],
    drawbacks: ['每日 -6 银币关税代价'],
    modifiers: {
      categories: { industry: 0.12, gather: 0.05 },
      passive: { silver: -6 },
    },
    active: false,
  },
  {
    id: 'patent_law',
    name: '专利法',
    desc: '颁布创新奖励制度，鼓励工坊投资新工艺。',
    category: 'economy',
    unlockEpoch: 3,
    cost: {},
    effects: ['工厂产出 +12%', '工业总体 +8%'],
    drawbacks: ['每日 -4 银币奖励基金'],
    modifiers: {
      buildings: {
        factory: 0.12,
        steel_works: 0.12,
        printing_house: 0.1,
      },
      categories: { industry: 0.08 },
      passive: { silver: -4 },
    },
    active: false,
  },
  {
    id: 'colonial_charter',
    name: '殖民特许',
    desc: '批准远洋公司垄断海外贸易，扩大奢侈品供给。',
    category: 'economy',
    unlockEpoch: 3,
    cost: {},
    effects: ['采集产出 +10%', '每日 +7 银币殖民地货物'],
    drawbacks: ['每日 -4 食物补给'],
    modifiers: {
      categories: { gather: 0.1 },
      passive: { silver: 7, spice: 0.4, coffee: 0.4, food: -4 },
    },
    active: false,
  },
  {
    id: 'infrastructure_plan',
    name: '基建计划',
    desc: '集中财政修路、疏浚与港区，提高物流效率。',
    category: 'economy',
    unlockEpoch: 2,
    cost: {},
    effects: ['采集/公共建筑产出 +10%', '工业产出 +5%'],
    drawbacks: ['每日 -8 银币维护'],
    modifiers: {
      production: 0.1,
      categories: { industry: 0.05 },
      passive: { silver: -8 },
    },
    active: false,
  },
  {
    id: 'citizen_roadworks',
    name: '徭役筑路',
    desc: '轮征市民维护道路与仓廪，保障物资流通。',
    category: 'economy',
    unlockEpoch: 0,
    cost: {},
    effects: ['采集产出 +5%', '人口上限 +10%'],
    drawbacks: ['每日 -5 银币徭役补贴'],
    modifiers: {
      categories: { gather: 0.05 },
      maxPop: 0.1,
      passive: { silver: -5 },
    },
    active: false,
  },
  {
    id: 'state_monopoly',
    name: '国家专营',
    desc: '由王室直接垄断关键工坊，集中利润与标准。',
    category: 'economy',
    unlockEpoch: 3,
    cost: {},
    effects: ['重工业产出 +18%', '每日 +10 银币国营利润'],
    drawbacks: ['公共服务 -8%', '人口上限 -5%'],
    modifiers: {
      buildings: {
        factory: 0.18,
        steel_works: 0.15,
        metallurgy_workshop: 0.12,
      },
      passive: { silver: 10 },
      categories: { civic: -0.08 },
      maxPop: -0.05,
    },
    active: false,
  },

  // ======== 军事类 ========
  {
    id: 'conscription_law',
    name: '征兵法',
    desc: '实行常备征兵档案，临战强制征调青壮。',
    category: 'military',
    unlockEpoch: 1,
    cost: {},
    effects: ['军事建筑产出 +20%', '采集产出 -5%'],
    drawbacks: ['人口上限 -5%', '每日 -3 食物口粮'],
    modifiers: {
      categories: { military: 0.2, gather: -0.05 },
      maxPop: -0.05,
      passive: { food: -3 },
    },
    active: false,
  },
  {
    id: 'military_academy',
    name: '军事学院',
    desc: '建立军官学校，训练士官与专长兵种。',
    category: 'military',
    unlockEpoch: 2,
    cost: {},
    effects: ['兵营/训练场产出 +20%', '军事建筑额外 +5%'],
    drawbacks: ['每日 -4 银币教官费用'],
    modifiers: {
      buildings: {
        barracks: 0.2,
        training_ground: 0.2,
      },
      categories: { military: 0.05 },
      passive: { silver: -4 },
    },
    active: false,
  },
  {
    id: 'war_economy',
    name: '战时经济',
    desc: '将工场和粮秣全面转入军需优先的配给体系。',
    category: 'military',
    unlockEpoch: 3,
    cost: {},
    effects: ['军事产出 +30%', '工业产出 +10%'],
    drawbacks: ['公共服务 -12%', '每日 -6 食物'],
    modifiers: {
      categories: { military: 0.3, industry: 0.1, civic: -0.12 },
      passive: { food: -6 },
    },
    active: false,
  },
  {
    id: 'officer_corps',
    name: '军官团',
    desc: '给予贵族子弟军职与终身津贴，确保军令畅通。',
    category: 'military',
    unlockEpoch: 3,
    cost: {},
    effects: ['堡垒/要塞产出 +20%', '军事产出 +10%'],
    drawbacks: ['每日 -6 银币军饷'],
    modifiers: {
      buildings: { fortress: 0.2 },
      categories: { military: 0.1 },
      passive: { silver: -6 },
    },
    active: false,
  },
  {
    id: 'praetorian_guard',
    name: '禁卫军',
    desc: '组建金卫队守卫王宫，靠高薪招募忠诚战士。',
    category: 'military',
    unlockEpoch: 2,
    cost: {},
    effects: ['军事产出 +15%'],
    drawbacks: ['每日 -10 银币卫队薪饷'],
    modifiers: {
      categories: { military: 0.15 },
      passive: { silver: -10 },
    },
    active: false,
  },

  // ======== 文化/学术类 ========
  {
    id: 'public_education',
    name: '公共教育',
    desc: '推广基层学舍，提高识字率与行政效率。',
    category: 'culture',
    unlockEpoch: 1,
    cost: {},
    effects: ['图书馆/印刷所产出 +20%', '人口上限 +5%'],
    drawbacks: ['每日 -5 银币教育预算'],
    modifiers: {
      buildings: { library: 0.2, printing_house: 0.15 },
      maxPop: 0.05,
      passive: { silver: -5 },
    },
    active: false,
  },
  {
    id: 'university_charter',
    name: '大学特许',
    desc: '授予大学自治与募款特权，吸引远方学者。',
    category: 'culture',
    unlockEpoch: 2,
    cost: {},
    effects: ['大学产出 +30%', '公共服务 +5%'],
    drawbacks: ['每日 -6 银币学术支出'],
    modifiers: {
      buildings: { university: 0.3, navigator_school: 0.1 },
      categories: { civic: 0.05 },
      passive: { silver: -6 },
    },
    active: false,
  },
  {
    id: 'research_grants',
    name: '科研资助',
    desc: '国家直接资助重点学者与工匠实验计划。',
    category: 'culture',
    unlockEpoch: 3,
    cost: {},
    effects: ['科研建筑额外 +20%', '工业产出 +5%'],
    drawbacks: ['每日 -6 银币科研经费'],
    modifiers: {
      buildings: {
        university: 0.2,
        library: 0.15,
        printing_house: 0.1,
      },
      categories: { industry: 0.05 },
      passive: { silver: -6 },
    },
    active: false,
  },
  {
    id: 'cultural_patronage',
    name: '文化赞助',
    desc: '王室出资扶持剧院与画院，彰显都城风雅。',
    category: 'culture',
    unlockEpoch: 1,
    cost: {},
    effects: ['歌剧院/剧场产出 +25%', '公共服务 +5%'],
    drawbacks: ['每日 -4 银币赞助费用'],
    modifiers: {
      buildings: { opera_house: 0.25, amphitheater: 0.2 },
      categories: { civic: 0.05 },
      passive: { silver: -4 },
    },
    active: false,
  },
  {
    id: 'free_press',
    name: '出版自由',
    desc: '允许报刊自由出版，鼓励知识传播与信息流动。',
    category: 'culture',
    unlockEpoch: 2,
    cost: {},
    effects: ['印刷/出版建筑产出 +25%', '公共服务 +5%'],
    drawbacks: ['每日 -4 银币监察开销'],
    modifiers: {
      buildings: { printing_house: 0.25, publishing_house: 0.25 },
      categories: { civic: 0.05 },
      passive: { silver: -4 },
    },
    active: false,
  },
  {
    id: 'state_religion',
    name: '国教制度',
    desc: '确立国教，统一节庆与道德规范维持秩序。',
    category: 'culture',
    unlockEpoch: 0,
    cost: {},
    effects: ['居民需求 -8%', '公共服务 +5%'],
    drawbacks: ['工业产出 -6%'],
    modifiers: {
      needsReduction: 0.08,
      categories: { civic: 0.05, industry: -0.06 },
    },
    active: false,
  },
  {
    id: 'secular_state',
    name: '世俗国家',
    desc: '政教彻底分离，强化世俗法制与工商业。',
    category: 'culture',
    unlockEpoch: 4,
    cost: {},
    effects: ['工业产出 +8%', '大学产出 +10%'],
    drawbacks: ['居民需求 +5%'],
    modifiers: {
      categories: { industry: 0.08 },
      buildings: { university: 0.1 },
      needsReduction: -0.05,
    },
    active: false,
  },
  {
    id: 'tithe',
    name: '什一税',
    desc: '恢复教士代收什一贡品，为神职提供收入。',
    category: 'culture',
    unlockEpoch: 0,
    cost: {},
    effects: ['每日 +6 银币教税'],
    drawbacks: ['居民需求 +5%'],
    modifiers: {
      passive: { silver: 6 },
      needsReduction: -0.05,
    },
    active: false,
  },

  // ======== 社会类 ========
  {
    id: 'grain_rationing',
    name: '粮食配给',
    desc: '将主食集中配给，优先保障军队与贫民口粮。',
    category: 'social',
    unlockEpoch: 0,
    cost: {},
    effects: ['居民需求 -12%', '公共服务 +5%'],
    drawbacks: ['工业产出 -5%'],
    modifiers: {
      needsReduction: 0.12,
      categories: { civic: 0.05, industry: -0.05 },
    },
    active: false,
  },
  {
    id: 'land_reform',
    name: '土地改革',
    desc: '没收荒地、分田到户，激励自耕农生产。',
    category: 'social',
    unlockEpoch: 1,
    cost: {},
    effects: ['农场/庄园产出 +15%', '人口上限 +5%'],
    drawbacks: ['公共服务 -4%'],
    modifiers: {
      buildings: { farm: 0.15, large_estate: 0.1 },
      categories: { gather: 0.1, civic: -0.04 },
      maxPop: 0.05,
    },
    active: false,
  },
  {
    id: 'feudal_privileges',
    name: '封建特权',
    desc: '重申领主世袭权力，用税收换取忠诚。',
    category: 'social',
    unlockEpoch: 2,
    cost: {},
    effects: ['庄园/教堂产出 +20%', '每日 +4 银币地税'],
    drawbacks: ['人口上限 -5%', '居民需求 +3%'],
    modifiers: {
      buildings: { large_estate: 0.2, church: 0.1 },
      passive: { silver: 4 },
      maxPop: -0.05,
      needsReduction: -0.03,
    },
    active: false,
  },
  {
    id: 'equality_decree',
    name: '平等法令',
    desc: '废除世袭特权，法庭对所有人一视同仁。',
    category: 'social',
    unlockEpoch: 3,
    cost: {},
    effects: ['居民需求 -10%', '基础生产 +5%'],
    drawbacks: ['军事产出 -5%'],
    modifiers: {
      needsReduction: 0.1,
      production: 0.05,
      categories: { military: -0.05 },
    },
    active: false,
  },
  {
    id: 'apprentice_system',
    name: '学徒制度',
    desc: '行会必须收徒培养，稳定手艺传承。',
    category: 'social',
    unlockEpoch: 1,
    cost: {},
    effects: ['工坊产出 +12%', '工业产出 +5%'],
    drawbacks: ['每日 -3 银币津贴'],
    modifiers: {
      buildings: {
        tailor_workshop: 0.12,
        furniture_workshop: 0.12,
        stone_tool_workshop: 0.1,
      },
      categories: { industry: 0.05 },
      passive: { silver: -3 },
    },
    active: false,
  },
  {
    id: 'welfare_system',
    name: '福利制度',
    desc: '设立常设济贫所与养老金，稳定社会预期。',
    category: 'social',
    unlockEpoch: 3,
    cost: {},
    effects: ['居民需求 -8%', '人口上限 +5%'],
    drawbacks: ['每日 -8 银币支出'],
    modifiers: {
      needsReduction: 0.08,
      maxPop: 0.05,
      passive: { silver: -8 },
    },
    active: false,
  },
  {
    id: 'forced_labor',
    name: '强制劳役',
    desc: '通过徭役加速大型工程，牺牲民众满意度。',
    category: 'social',
    unlockEpoch: 0,
    cost: {},
    effects: ['采集产出 +25%'],
    drawbacks: ['工业产出 -8%', '居民需求 +8%'],
    modifiers: {
      categories: { gather: 0.25, industry: -0.08 },
      needsReduction: -0.08,
    },
    active: false,
  },
  {
    id: 'clan_tribute',
    name: '部族纳贡',
    desc: '要求部族首领定期进奉，以自治换取贡金。',
    category: 'social',
    unlockEpoch: 0,
    cost: {},
    effects: ['每日 +5 银币贡金', '居民需求 -3%'],
    drawbacks: ['每日 -4 食物祭品'],
    modifiers: {
      passive: { silver: 5, food: -4 },
      needsReduction: 0.03,
    },
    active: false,
  },
  {
    id: 'workers_compact',
    name: '工人公约',
    desc: '工匠与王室签订协议，限制工时换取保障。',
    category: 'social',
    unlockEpoch: 2,
    cost: {},
    effects: ['工业产出 +6%', '居民需求 -4%'],
    drawbacks: ['每日 -3 银币津贴'],
    modifiers: {
      categories: { industry: 0.06 },
      needsReduction: 0.04,
      passive: { silver: -3 },
    },
    active: false,
  },
];
