/**
 * 全新政令配置
 * 侧重于强力效果与高昂代价
 */
export const DECREES = [
  {
    id: 'emergency_rationing',
    name: "紧急配给",
    desc: "强行限制物资分配。所有阶层需求 -30%，但稳定度 -15，全阶层好感 -20。",
    category: 'social',
    unlockEpoch: 0,
    cost: { admin: 10 },
    effects: ["所有阶层资源需求 -30%"],
    drawbacks: ["稳定度 -15", "全阶层好感 -20"],
    modifiers: { needsReduction: 0.3, stability: -0.15, classApproval: { all: -20 } },
    active: false,
  },
  {
    id: 'clan_mobilization',
    name: "氏族总动员",
    desc: "动员所有劳动力采集资源。采集效率 +50%，但工业产出 -30%，科研停滞。",
    category: 'economy',
    unlockEpoch: 0,
    cost: { admin: 9 },
    effects: ["采集类建筑 +50% 产出"],
    drawbacks: ["工业类建筑 -30%", "科研停摆"],
    modifiers: { categories: { gather: 0.5, industry: -0.3 }, scienceBonus: -1.0 },
    active: false,
  },
  {
    id: 'theocracy',
    name: "祭司治国",
    desc: "神权至上。文化产出 +40%，稳定度 +20，但科研 -30%。",
    category: 'culture',
    unlockEpoch: 1,
    cost: { admin: 12 },
    effects: ["文化产出 +40%", "稳定度 +20"],
    drawbacks: ["科研 -30%"],
    modifiers: { cultureBonus: 0.4, stability: 0.2, scienceBonus: -0.3 },
    active: false,
  },
  {
    id: 'overtime_work',
    name: "强制加班",
    desc: "无视工人权益的高强度劳动。工业产出 +40%，但工人/工匠好感 -30，人口上限 -10%。",
    category: 'economy',
    unlockEpoch: 2,
    cost: { admin: 14 },
    effects: ["工业类建筑 +40%"],
    drawbacks: ["工人/工匠好感 -30", "人口上限 -10%"],
    modifiers: { categories: { industry: 0.4 }, classApproval: { worker: -30, artisan: -30 }, maxPop: -0.1 },
    active: false,
  },
  {
    id: 'currency_devaluation',
    name: "货币贬值",
    desc: "通过贬值刺激出口。贸易收入 +50%，但进口成本飙升，稳定度 -10。",
    category: 'economy',
    unlockEpoch: 3,
    cost: { admin: 13 },
    effects: ["贸易卖出收入 +50%"],
    drawbacks: ["进口成本大增", "稳定度 -10"],
    modifiers: { tradeIncome: 0.5, stability: -0.1 },
    active: false,
  },
  {
    id: 'praetorian_guard',
    name: "禁卫军制度",
    desc: "建立精锐卫队。军事力量 +30%，行政容量 +10，但每日消耗 10 银币。",
    category: 'military',
    unlockEpoch: 3,
    cost: { admin: 16 },
    effects: ["军事力量 +30%", "行政容量 +10"],
    drawbacks: ["每日 -10 银币"],
    modifiers: { militaryBonus: 0.3, admin: 10, passive: { silver: -10 } },
    active: false,
  },
];
